### ISSUE TITLE
Camera shakes even with still device on Android/chrome

### ISSUE THREAD

**Issue by maxi-camonapp** [aframevr/aframe#5053] opened 2022-05-05 14:57 UTC
**Description:**

- A-Frame Version: 1.0.3 / 1.0.4
- Platform / Device: Android 9 / LG Q60 / Chrome 101.0.4951.41
- Reproducible Code Snippet or URL: -

There´s an very noticeable shaking when executing any aframe example. This problem affects all Android devices on Chrome, but it is extremly noticeable on LG. 

https://user-images.githubusercontent.com/90636991/166951450-af8d33b2-67d1-4964-90ba-01ffefad7366.mp4

The problem is also visible in all other devices, but with much less notoriety

https://user-images.githubusercontent.com/90636991/166952061-23de3278-0267-44af-a4a3-f64b62b673d7.mp4

**Comment by dmarcos** [comment] 2022-05-09 07:30
Dupe of https://github.com/aframevr/aframe/issues/5036

A-Frame just [applies the pose coming](https://github.com/aframevr/aframe/blob/master/vendor/DeviceOrientationControls.js#L88) from the [DeviceOrientation API](https://w3c.github.io/deviceorientation/spec-source-orientation.html). Some devices seem to return noisy data. Not sure what can be done on the A-Frame side. Probably something that should be fixed at the browser / sensor / driver level.

**Comment by dmarcos** [comment] 2022-11-17 21:29
Closing this because I believe there's nothing we can do on the A-Frame side. Can reopen if necessary

**Closed by dmarcos** 2022-11-17 21:29 UTC
