### ISSUE TITLE
Add Cardboard lens Distortion

### ISSUE THREAD

**Issue by MrBokeh** [aframevr/aframe#1295] opened 2016-03-30 00:54 UTC
**Description:**
The video sphere doesn't have settings for lens Distortion for google cardboard v1/v2 etc.
 
- A-Frame Version: v0.20
- Platform/Device: iOS and Android

**Comment by cvan** [comment] 2016-03-31 19:31
Thanks for filing. I have a branch that updates to use the latest webvr-polyfill. There have been a few iOS bugs in the latest webvr-polyfill version so we've been holding off on updating: borismus/webvr-polyfill#46 and borismus/webvr-polyfill#57 Will be updating soon though, so stay tuned.

**Comment by MrBokeh** [comment] 2016-04-09 05:45
Any luck on this? Can we use the WebVRConfig json to add more buffer and add more referesh rate? the video is a bit slow, does it support stereoscopic spherical videos?

**Comment by dmarcos** [comment] 2016-06-03 01:34
Distortion is provided by the ```webvr-polyfill```.  @cvan Can we close this as an aframe issue?

**Comment by cvan** [comment] 2016-06-03 02:35
> Any luck on this? Can we use the WebVRConfig json to add more buffer and add more referesh rate? the video is a bit slow, does it support stereoscopic spherical videos?

You can set it yourself before you include `aframe.js`:

```html
  …
  <head>
    …
    <script>window.WebVRConfig = { … };</script>
    <script src="aframe.js"></script>
  </head>
  …
```

and we'll respect the config values set on `window.WebVRConfig`.

**Comment by MrBokeh** [comment] 2016-06-03 05:24
@cvan May I ask what's the setting to enable distortion?

**Comment by daoshengmu** [comment] 2016-06-03 06:03
I am looking for this as well!

**Comment by craigkeeling** [comment] 2016-06-12 01:12
This is concerning the ability to scan the QR code to set the proper focal distance? That's what I'm looking for if that's available.

**Comment by cvan** [comment] 2016-06-12 02:31
Should look at @borismus' https://github.com/borismus/webvr-polyfill#configuration

**Comment by allanweir** [comment] 2016-07-01 09:57
@cvan Hi Chris, am I right in reading that the latest WebVR polyfill contains the code for lens distortion and device configuration for different cardboard headsets? Do you know when aframe will update to the latest version or which branch we can get a preview from? Thanks for the help!

**Comment by cvan** [comment] 2016-07-01 10:03
> @cvan Hi Chris, am I right in reading that the latest WebVR polyfill contains the code for lens distortion and device configuration for different cardboard headsets? Do you know when aframe will update to the latest version or which branch we can get a preview from? Thanks for the help!

yes, it does. per [my comment above](https://github.com/aframevr/aframe/issues/1295#issuecomment-223476637), just set this:

```html
  …
  <head>
    …
    <script>window.WebVRConfig = {CARDBOARD_UI_DISABLED: false};</script>
    <script src="aframe.js"></script>
  </head>
  …
```

**Comment by allanweir** [comment] 2016-07-01 10:49
Thanks for quick response. I'm using Ionic and Browserify and I wasn't setting the config early enough it turns out. The back and settings button aren't responding to touch when I play a videosphere currently (iOS sim and device) - I'm going to experiment outside of Ionic and see if I have the same problem.

**Comment by allanweir** [comment] 2016-07-01 12:01
The cardboard UI controls aren't working using the current master of aframe - tested using iOS webview on sim, device and then just a plain project ran in Safari. Pressing the back button does nothing, pressing the settings cog dims the screen for the duration you hold down. Sorry if this is more of a polyfill issue? Let me know if I can help out in anyway too

**Comment by allanweir** [comment] 2016-07-01 13:43
To answer my own problem.. the version of the WebVR polyfill currently being used will not show the Cardboard UI, it's fixed in a newer version. The problem is in
`CardboardVRDisplay.prototype.beginPresent_ = function() {
...
if (this.carboardUI_) { //Should be cardboard not carboard
    this.cardboardUI_.listen(function() { 

  }
}`

**Closed** 2016-07-21 23:40 UTC
