### ISSUE TITLE
Black Screen in Oculus GO

### ISSUE THREAD

**Issue by andrewjones4** [aframevr/aframe#3656] opened 2018-06-20 19:54 UTC
When I try to view the 360 video example on the a-frame website with my Oculus Go, it works until I click the VR icon to go into true 360 format, and then all I get is a black screen. It was working this morning, so I am unsure what could have changed.

**Comment by WellanDraco** [comment] 2018-06-21 13:51
same issue with stereo 360 
bit.ly/test-stereo
this link show a correction of the stereo component and worked well in vr days ago.

**Comment by SteveX** [comment] 2018-06-27 19:53
I have seen this as well (working, then not working), wondered if the change might be caused by an update to the Go browser.

But it still works in some scenes even after emptying the Go browser cache, so I have some investigating to do.

**Comment by dmarcos** [comment] 2018-06-30 02:38
I was able to reproduce the problem with the THREE example as well: https://threejs.org/examples/webvr_video.html

It does not seem to be specific to A-Frame

**Comment by dmarcos** [comment] 2018-06-30 03:39
@DigiTec Any known problem with the Oculus Browser + Video on the Go? Problem not exclusive to A-Frame.

**Comment by DigiTec** [comment] 2018-06-30 04:40
Known issue. Fixed in 4.6.2. Caused by some issues when introducing foveated rendering.

**Comment by Artyom17** [comment] 2018-07-02 02:42
As workaround - disable Fixed foveation in chrome://flags (set it to None).

**Comment by WellanDraco** [comment] 2018-07-04 15:47
the workaround works, thanks!
Is there a way to fix it in production?

**Comment by Artyom17** [comment] 2018-07-04 19:36
Definitely, it will be fixed in the next release.

**Comment by VasuBhog** [comment] 2018-07-13 15:08
@Utopiah Where can disable foveation on Oculus Go (Oculus Browser) or A-Frame?

**Comment by WellanDraco** [comment] 2018-07-14 04:41
on the browser via the flags page... that's why I asked for a fix in production (cant ask every user to modify their flags)

**Comment by WellanDraco** [comment] 2018-07-14 04:43
@VasuBhog  On the browser, the reason why i asked for a fix for production (cant ask every GO user to set flags before accessing vr)...

**Comment by dmarcos** [comment] 2019-01-24 01:15
This should be fixed in latest Oculus Browser and A-Frame master.

**Closed by dmarcos** 2019-01-24 01:15 UTC
