### ISSUE TITLE
requestPresent from vrdisplayactivate is failing due to usage of wrong layer.

### ISSUE THREAD

**Issue by Artyom17** [aframevr/aframe#4198] opened 2019-06-06 19:59 UTC
**Description:**
The requestPresent from within the vrdisplayactivate is failing on Oculus Browser (and I bet on Chrome too) due to the wrong layer provided. The commit that introduced the issue is a3ac58e4084053c14706abc6ef37bde45086a33e. See https://github.com/aframevr/aframe/blob/b3ed182fefb883e36272401529a8b5a3b1a9ce5d/src/utils/device.js#L13: it creates a new non-gl canvas, and tries to use it as a layer, which is not going to work. Even in the nested requestPresents you must specify the ACTUAL GL canvas, not just a placeholder (https://immersive-web.github.io/webvr/spec/1.1/#dom-vrdisplay-requestpresent%E2%91%A0)

Seems like the previous version worked (or should have worked).

- A-Frame Version: 0.9.2 (master)
- Platform / Device: Oculus Browser / Chrome
- Reproducible Code Snippet or URL:
With connected Go or Quest, run this adb command:
adb shell am start -n com.oculus.vrshell/.MainActivity -d apk://com.oculus.browser -e uri "ovrweb://vr?uri=http%3A%2F%2Faframe.io%2Fexamples%2Fshowcase%2Fsky" (may replace the actual url to whatever is better for you).

**Comment by Artyom17** [comment] 2019-06-06 20:10
Changing it back to `window.addEventListener('vrdisplayactivate', function (evt) {
  // WebXR takes priority if available.
  if (navigator.xr) { return; }

  let sceneEl = document.querySelector('a-scene');
  let canvasEl = sceneEl.canvas;
  vrDisplay = evt.display;
  // Request present immediately. a-scene will be allowed to enter VR without user gesture.
  vrDisplay.requestPresent([{source: canvasEl}]).then(function () {}, function () {});
});` seems to fix the issue.

**Comment by dmarcos** [comment] 2019-06-06 20:11
@Artyom17 Thanks for taking a look, much appreciated. The placeholder canvas is passed to honor the time limit that WebVR implementations have to call requestPresent after vrdisplayactivate fires. At that point in time the scene and final canvas might not be initialized. Will initializing the webgl context with the placeholder canvas work? Does Oculus not support multiple calls to requestPresent with different canvases?

**Comment by dmarcos** [comment] 2019-06-06 20:12
Oh thanks for the suggestion. We just crossed comments and I didn’t see yours

**Comment by Artyom17** [comment] 2019-06-06 20:13
Yeah, Oculus does support multiple calls with different canvases (at least it should, I need to double test it). But the issue with the rejected requestPresent is that the canvas you provide is not the WebGL one.

**Comment by dmarcos** [comment] 2019-06-06 20:14
@Artyom17 your solution won’t work. That canvas might not be initialized when vrdisplayactivate fires.

**Comment by Artyom17** [comment] 2019-06-06 20:15
Yeah, understood, I am leaving this to you to figure out the proper solution ;) You just need to use the webgl-canvas, that is it (i.e. the webgl context should be associated with the canvas).

**Comment by dmarcos** [comment] 2019-06-06 20:16
Thanks. Would initializing a webgl context on the placeholder canvas work?

**Comment by Artyom17** [comment] 2019-06-06 20:17
It could.... I can try it really quick. But will you switch canvases later on to the actual one?

**Comment by Artyom17** [comment] 2019-06-06 20:20
Yeah, it works in terms of entering VR, but nothing renders (I assume, because the wrong canvas is used for the rendering).

**Comment by dmarcos** [comment] 2019-06-06 20:22
The idea is that when the scene is properly initialized we will call requestPresent again with the final canvas we will use to render the scene

**Comment by Artyom17** [comment] 2019-06-06 20:23
I see...But do you?

**Comment by dmarcos** [comment] 2019-06-06 20:24
Yes. here: https://github.com/aframevr/aframe/blob/master/src/core/scene/a-scene.js#L298

**Comment by Artyom17** [comment] 2019-06-06 20:30
Ok, let me check...

**Comment by Artyom17** [comment] 2019-06-06 21:11
Something weird is happening. If I put two requestPresent with different canvases in a row, one after another - everything works. 
When I call requestPresent in activedisplay and then from a-scene - only white background is rendered (i.e. some rendering occurs, such as clear)....

**Comment by dmarcos** [comment] 2019-06-06 21:13
@Artyom17 Does Firefox desktop works with the same code? That would probably help determine if the problem is in A-Frame or Oculus Browser side. Thanks for investigating this. I know it can be tricky to investigate.

**Comment by arpu** [comment] 2019-06-06 22:13
if it helps i tested https://a-frobot.github.io/aframe/examples/showcase/link-traversal/  on oculus go with Firefox Reality   and does not work ( black window after link traversal after resume white window)

**Comment by dmarcos** [comment] 2019-06-06 22:16
Not sure if VR navigation actually works on Firefox Reality. Firefox and Supermedium on desktop are the ones that do.

**Comment by Artyom17** [comment] 2019-06-06 23:19
LOL, I don't even have a Rift connected to my work desktop (should I mention that the main OS for me is Linux? ;) ) 
Anyway, the issue with rendering is caused by the cameras' viewports in renderObjects are not setup correctly (all NaNs).
Cameras viewports are not set correctly, because WebVRManager.renderWidth and renderHeight are not set correctly. Those supposed to be set in WebVRManager.onVRDisplayPresentChange. 
However, the method isPresenting() returns false, because WebVRManager.setDevice method wasn't called from the ondisplayactivate. Also, note, that even if the 'device' is set, the device.isPresenting property will be false till promise of the requestPresent is satisfied (and currently, this fact is completely ignored in ondisplayactivate).

**Comment by arpu** [comment] 2019-06-06 23:30
if i am not wrong it should be 
var sceneEl = document.querySelector('a-scene');
sceneEl.renderer.vr 

https://github.com/aframevr/aframe/blob/master/src/core/scene/a-scene.js#L258

**Comment by Artyom17** [comment] 2019-06-06 23:35
Ok, in this case this rough mod makes things to render in Oculus Browser with deeplinking / navigation:

`window.addEventListener('vrdisplayactivate', function (evt) {
  // WebXR takes priority if available.
  if (navigator.xr) { return; }
  let canvasEl = document.createElement('canvas');
  let vrDisplay = evt.display;
  // Request present immediately. a-scene will be allowed to enter VR without user gesture.
  let glAttribs = {
        alpha: false,
        antialias: true
  };
  canvasEl.getContext("webgl", glAttribs);
  vrDisplay.requestPresent([{source: canvasEl}]).then(function () {
      let sceneEl = document.querySelector('a-scene');
      sceneEl.renderer.vr.setDevice(vrDisplay);
  }, function () {});
});`

**Comment by dmarcos** [comment] 2019-06-06 23:40
Problem is similar there. We cannot rely on `sceneEl.renderer` to be ready when `vrdisplayactivate` fires the first time. My understanding is that the root issue is that `vrdisplaypresentchange` only fires once after the first `requestPresent` call and we're missing the event later on, resulting in WebVRManager not setting renderWidth  / renderHeight accordingly.

**Comment by Artyom17** [comment] 2019-06-06 23:40
Yes, it does fire only once, you are right.

**Comment by dmarcos** [comment] 2019-06-06 23:42
Not sure what would be the spec compliant behavior. Should `vrdisplaypresentchange` fire for all succesful calls to `requestPresent`?

**Comment by Artyom17** [comment] 2019-06-06 23:44
>onvrdisplaypresentchange A user agent MUST dispatch this event type to indicate that a VRDisplay has begun or ended VR presentation. This event should not fire on subsequent calls to requestPresent() after the VRDisplay has already begun VR presentation.

(https://immersive-web.github.io/webvr/spec/1.1/#window-vrdisplaypresentchange-event)

**Comment by dmarcos** [comment] 2019-06-06 23:47
Ok, thanks. It seems ww need to find a way to run the logic from `onVRDisplayPresentChange` in WebVRManager after the second call to `requestPresent`. That and initializing a webgl context on the first dummy canvas should fix the issues.

**Comment by dmarcos** [comment] 2019-06-06 23:49
If you have the code handy. Can you try emitting a synthetic event?
```
  var event = new CustomEvent('vrdisplaypresentchange', { detail: { display:  display} });
  window.dispatchEvent(event);
```

**Comment by Artyom17** [comment] 2019-06-06 23:54
k, let me try

**Comment by Artyom17** [comment] 2019-06-06 23:58
@dmarcos - yup, seems like that made the trick. Do you want me to create PR with both of these changes, or you'll do it yourself?

**Comment by dmarcos** [comment] 2019-06-07 00:00
Yeah feel free to open a PR. It will be super appreciated. Thank you very much.

**Comment by dmarcos** [comment] 2019-06-07 14:00
Fixed by https://github.com/aframevr/aframe/pull/4199

**Closed by dmarcos** 2019-06-07 14:00 UTC
