### ISSUE TITLE
Gyroscope works except for Image Gallery on Mobile Android

### ISSUE THREAD

**Issue by Xrispy7** [aframevr/aframe#3663] opened 2018-06-23 09:05 UTC
Hello! I am experiencing a gyro problem on 2 phones except they are accessing the gyro but with either random input, or very very sensitive input. If i keep my hand still and don't move it is almost still but i can see the micromovements on screen with my hand's micro shaking.

The Gyro works 100% fine with this link:

https://aframe.io/examples/showcase/sky/

but not the image gallery:
https://aframe.io/examples/showcase/360-image-gallery/

Honor 6x | Android 7.0 EMUI 5.0.2 / Google Chrome 67.0.3396.87 / aframe 0.8.2
&
Samsung S8 | Android / Google Chrome 67.0.3396.87 / aframe 0.8.2

Thanks!

P.S I noticed a different thread had a "No gyro working issue" that was fixed recently, with aframe.io 8.0.2, chrome 65 Samsung S8 so I believe this is a different problem.

**Comment by sepehr-laal** [comment] 2018-06-26 04:37
I also wanted to confirm that non of the examples using AFrame 0.8.2 are working on my Pixel with Chrome 67. Gyro does not work at all. Oddly enough, my own project that uses AFrame 0.7 and this example: https://aframe.io/examples/showcase/animation/ which uses AFrame 0.5 work great.

I upgraded my project to AFrame 0.8.2 to work around the Android m65 issue, seems like 0.8.2 has its own problems.

**Comment by dmarcos** [comment] 2018-06-30 03:01
@Xrispy7 This should have fixed by https://github.com/aframevr/aframe/commit/aaa3bf0bf4e0dfc744e2964dc4c8f11b24620333

You can try the examples in master to verify: https://rawgit.com/aframevr/aframe/master/examples/

I'm closing but will reopen if the problem is not fixed

**Closed by dmarcos** 2018-06-30 03:01 UTC
