### ISSUE TITLE
setAttribute on text geometry not working

### ISSUE THREAD

**Issue by vrimaginar** [aframevr/aframe#2837] opened 2017-07-03 12:41 UTC
When trying to set setAttribute('geometry',{primitive: "plane", height: "auto", width: "auto"}); on `<a-entity text>` the plane is not being drawn. However if you change the wrap count programaticaly afterwards the plane is showing. The plane will not update it's width and height if you change the wrap count again.

- A-Frame Version: 0.6.0 master (8d60730)
- Platform / Device: PC

**Comment by dmarcos** [comment] 2017-07-04 06:24
Can you provide a link to an example that reproduces the issue?

**Comment by dmarcos** [comment] 2017-07-14 05:24
A fix for `setAttribute` has landed on master (https://github.com/aframevr/aframe/pull/2840). I cannot reproduce this bug on the text example.  Please let us know if you are still affected and can provide an example to reproduce

**Closed by dmarcos** 2017-07-14 05:24 UTC

**Comment by vrimaginar** [comment] 2017-07-16 20:57
Hi @dmarcos, we still have the problem;

`var text = document.querySelector('#af-text');
text.setAttribute('geometry',{primitive: "plane", height: "auto", width: "auto"});`

Will not work, but when we change the e.g. wrapCount the textbox will appear.

**Comment by dmarcos** [comment] 2017-07-17 15:40
@vrimaginar are you trying with the master branch?

**Comment by machenmusik** [comment] 2017-07-17 15:47
IiRC, the support for auto width and height is on text component, not geometry component...

**Comment by vrimaginar** [comment] 2017-07-17 23:06
@dmarcos, yes I am on the master branche as per your suggestion.

@machenmusik, the auto width and height are on the geometry component see:

https://aframe.io/docs/0.6.0/components/text.html

`<a-entity
  geometry="primitive: plane; height: auto; width: auto"
  material="color: blue"
  text="width: 4; value: This text will be 4 units wide."></a-entity>`

The thing is, after creating the entity component with:

`<a-entity text="width: 4; color: #000; value: test text" id-text></a-entity>`

and adding `geometry="primitive: plane; height: auto; width: auto;" material="color: red"`
in the console nothing happens. But when you change anything in the text="" section, the plane appears. Even doing:

`text = document.querySelector('#text);
text.setAttribute('text','bla',1);`

will work.

**Comment by dmarcos** [comment] 2017-07-17 23:22
That's an error in the documentation. Geometry does not have auto height and width properties. I tested on the [text example](https://a-frobot.github.io/aframe/examples/test/text/) and it works fine to me (see the fucsia plane in the middle) by doing:
```javascript
el.setAttribute('geometry', 'primitive: plane; height: 1; width: .5')
```
![test](https://d3vv6lp55qjaqc.cloudfront.net/items/1o2s3N3d1M2s0b293j0M/Image%202017-07-17%20at%204.20.01%20PM.png?X-CloudApp-Visitor-Id=4ef42a89e08bc241f872ecc16ec4e51f&v=83ed0c9e)

**Comment by vrimaginar** [comment] 2017-07-17 23:31
Setting the geometry width and height to an integer indeed works but I need autoscaling. the documentation says:

> Scaling Geometry to Fit Text
To have the geometry automatically scale with the text, set the geometry component’s width and height properties to auto, and set the text component’s width as desired. In this example, the plane’s width will be set to 4 units, and its height will be set to match the actual height of the text:

And it works as intended in 0.5.0 and 0.6.0, but not when we set it programmatically.

So, I doubt it's an error in the documentation.

**Comment by dmarcos** [comment] 2017-07-18 00:33
I'm surprised that was working at all. `auto` is not a valid value for the geometry `width` and `height` it will be parsed as an integer resulting in a `NaN`. The `text` component does not check anywhere for `auto` values either. I think the text component should have a `backgroundEnabled` property and manage its own geometry instead of relying on user doing any sort of manual configuration. @machenmusik any ideas?

**Comment by vrimaginar** [comment] 2017-07-18 00:40
Well @ngokevin mentions `<a-entity text geometry="primitive: plane; height: auto" material>` in #2764

**Comment by machenmusik** [comment] 2017-07-18 04:40
The mystical processing of `auto` is here: https://github.com/aframevr/aframe/blob/master/src/components/text.js#L270

'auto' was more memorable and descriptive than `0`

I think the problem here is that adding the geometry component is not triggering layout update.  But if you do anything that causes the text component to recompute, the geometry component values are then set.

Apologies that my prior comment was not clearer.

**Comment by machenmusik** [comment] 2017-07-18 04:44
@dmarcos the text component does manage its own internal geometry, but does not include background (nor padding/margin); one issue that would arise with deprecating the magic geometry handling and replacing with a fixed background plane is that you don't always want a plane as background.

**Comment by dmarcos** [comment] 2017-07-18 05:12
`auto` ends up being a `NaN` when it is parsed as a `Number`. I would constraint the background to a plane handled within the component and for other kinds of geometry as a background the user can handle that externally. I don't think resizing automatically a random geometry is going to end up producing the results you expect.

**Comment by machenmusik** [comment] 2017-07-18 05:28
Yeah I think there were issues with explicit zero being mistaken to mean default (which is nonzero)

I am on the fence w.r.t. background, IMO without padding / margin the background may not be so helpful since it may look wrong; not sure change in behavior is worth breaking backward compatibility...

**Comment by dmarcos** [comment] 2017-07-18 05:34
The change will ship on 0.8.0. I'm not concerned about backwards compatibility.

**Comment by dmarcos** [comment] 2017-07-18 05:38
I think is better to evolve the API and ensure good ergonomics rather than being worried about backward compatibility. At the of the day we're still in 0.X.Y versions.

**Comment by machenmusik** [comment] 2017-07-18 06:33
The original idea was to be able to use text to label a plane or box or anything that had a width and height.  But that was rather early on, I don't think I realized that model loaders like obj and glTF were not considered geometry, so maybe that hasn't ended up being as useful as hoped.

**Comment by dmarcos** [comment] 2017-07-18 06:41
What about adding a `backgroundEnabled` flag and the components sets the plane geometry internally?

**Comment by machenmusik** [comment] 2017-07-18 07:39
maybe call the new flag `backgroundPlane` and have it forcibly `setAttribute('geometry', {primitive: plane; width: __, height: __})` -- and if false (default), continue existing behavior for backward compatibility?

**Comment by machenmusik** [comment] 2017-07-18 07:40
or it could be `background: plane` (so in theory you could also use box or other primitive)

**Comment by dmarcos** [comment] 2017-07-18 14:57
I would start with just a plane and make it work really well. Expanding to any geometry is too much ground to cover.

**Comment by dmarcos** [comment] 2017-07-18 14:58
I would probably not use the geometry component but create a custom geometry internally with THREE

**Comment by leo-nerd** [comment] 2021-02-23 18:14
How would we go about re-autosizing when the text contents have changed? `setAttribute("geometry", { width: auto})` is indeed parsed as a NaN. Should `geometry `be detached and re-attached?
