### ISSUE TITLE
surface touch event causes console error

### ISSUE THREAD

**Issue by mikemainguy** [aframevr/aframe#5245] opened 2023-02-14 15:42 UTC
**Description:**
on master, surface touch events are not mapped properly with original color causing an error to be dumped on console.  As far as I can tell there's no functional impact (other than surface color doesn't change on touch event).

- A-Frame Version:
- 1.4.1
- Platform / Device:
- Oculus Quest 2 with touch controllers
- Reproducible Code Snippet or URL:
- https://www.immersiveidea.com/worlds/aframevr
- Go into immersive vr mode and touch one of the touchpads

Uncaught TypeError: Cannot read properties of undefined (reading 'originalColor')
    at NewComponent.updateButtonModel (aframe-master.js:18543:1)
    at NewComponent.updateModel (aframe-master.js:18538:1)
    at module.exports.onButtonEvent (aframe-master.js:34721:1)
    at AEntity.onButtonTouchEnd (aframe-master.js:18275:1)
    at AEntity.nrWrapper (ctr:24:29524)
    at AEntity.emit (aframe-master.js:25832:1)
    at NewComponent.handleTouch (aframe-master.js:22516:1)
    at NewComponent.handleButton (aframe-master.js:22442:1)
    at NewComponent.updateButtons (aframe-master.js:22428:1)
    at NewComponent.tick (aframe-master.js:22387:1)

ctr:24 Uncaught TypeError: Cannot read properties of undefined (reading 'originalColor')
    at NewComponent.updateButtonModel (aframe-master.js:18543:1)
    at NewComponent.updateModel (aframe-master.js:18538:1)
    at module.exports.onButtonEvent (aframe-master.js:34721:1)
    at AEntity.onButtonTouchEnd (aframe-master.js:18275:1)
    at AEntity.nrWrapper (ctr:24:29524)
    at AEntity.emit (aframe-master.js:25832:1)
    at NewComponent.handleTouch (aframe-master.js:22516:1)
    at NewComponent.handleButton (aframe-master.js:22442:1)
    at NewComponent.updateButtons (aframe-master.js:22428:1)
    at NewComponent.tick (aframe-master.js:22387:1)

**Comment by dmarcos** [comment] 2023-02-14 23:30
Can you please share a simple example to reproduce with https://glitch.com/~aframe?

**Comment by vincentfretin** [comment] 2023-02-15 08:59
duplicate of #5212

**Comment by dmarcos** [comment] 2023-11-03 10:21
Closing as dup of https://github.com/aframevr/aframe/issues/5212

**Closed by dmarcos** 2023-11-03 10:21 UTC
