### ISSUE TITLE
Problem in setting Camera Position in vr mode

### ISSUE THREAD

**Issue by DYBDDY** [aframevr/aframe#5576] opened 2024-09-15 09:59 UTC
When entering VR mode, the Y-axis position of the camera is forcibly set to 1.7. I have tried modifying the code in aframe.min.js, but the result remains the same when entering VR mode.By the way I'm using meta quest 3.

   <a-entity id="rig" position="3.402 0.500 -1.955" rotation="0 87.255 0">
      <a-camera id="camera" wasd-controls="acceleration: 10" look-controls position="-0.958 0.683 1.138">
      </a-camera>
    </a-entity>

**Comment by dmarcos** [comment] 2024-09-16 00:11
Can you share a link that reproduce the issue? Make sure you are using A-Frame 1.6.0. If you want to position the camera in VR use a camera rig https://aframe.io/docs/1.6.0/components/camera.html#examples

**Comment by DYBDDY** [comment] 2024-09-16 10:03
I

**Comment by DYBDDY** [comment] 2024-09-16 10:04
I manage to figure out , just by changing a-camera position,thanks for the help.

**Comment by DYBDDY** [comment] 2024-09-16 11:23
The position was set in 2D mode,everything went will until entering vr mode,In developer mode after entering vr mode, I checked the rig position, it was as same as in 2d mode which were 0 1.264 2.704.However,it doesn't look like that.
[](https://dybddy.github.io/vristraining/)

   <a-entity id="rig" position="0 1.264 2.704" rotation="0 0 0">
      <a-entity  id="camera" camera wasd-controls="acceleration: 10" look-controls>
      </a-entity>
      <a-entity oculus-touch-controls="hand: left" laser-controls="hand: left" model="true"
        raycaster="objects: .raycastable" thumbstick-logging-move></a-entity>
      <a-entity oculus-touch-controls="hand: right" laser-controls="hand: right" model="true"
        raycaster="objects: .raycastable" thumbstick-logging-look></a-entity>
    </a-entity>

**Comment by dmarcos** [comment] 2024-09-16 15:21
Not sure I understand. Can you elaborate what you get vs what you expect and provide some simple code to illustrate with Glitch: https://glitch.com/~aframe ?

Thanks

**Comment by DYBDDY** [comment] 2024-09-17 05:11
Thankyou for your response,I think image might tell you what I'm meaning.
As you can see,the height in vr mode changed. I forgot to mention that  I'm using "Immersive Web Emulator WebXR Emulator for Meta Quest devices" extension for chrome.

Expected angle(not in vr mode)
![expected_angle](https://github.com/user-attachments/assets/5d93fb70-6e9a-485e-bee2-262d382682a8)

After enter VR mode
![angle_in_vrmode](https://github.com/user-attachments/assets/1ea26f0a-6ce0-40b6-9a86-c99a71f3b1e8)

**Comment by vincentfretin** [comment] 2024-09-17 07:54
You have an extra `</a-entity>` line 79 that shouldn't be there. Probably not related to your issue, but having mismatching end tags can do really weird things.

**Comment by vincentfretin** [comment] 2024-09-17 07:59
Ah your issue is that is doesn't stay at 1.264 in VR, yeah that's a feature, it uses the detected height in VR and override the y position of the rig. Not sure we can disable that behavior.
If you don't have a rig does it overrides the y position while in VR?

**Comment by DYBDDY** [comment] 2024-09-17 10:28
Unfortunately if I remove rig the result stays the same,any other ways?

**Comment by mrxz** [comment] 2024-09-17 12:01
The camera represents the user's head. By default A-Frame will place it 1.6m above the ground to simulate a person standing. When entering VR the actual tracked position of the HMD is used instead. Since you can't control the physical position of the user's head, a camera rig needs to be used to move and position the user in the virtual world. The rig's position represents the point on the floor the user is standing on.

In other words, you should not use the rig to get the camera at the right eye-height, but only at the right location in the virtual world. The eye-height should be handled by the position of the camera entity when in 2D and the WebXR data when in VR.

There are two options depending on your needs, either:
- Reduce the Y coordinate of your rig by 1.6 and keep the Y coordinate of the camera at the default 1.6
- Switch the reference space to `local` instead of `local-floor` (e.g. `<a-scene webxr="referenceSpaceType: local">`)

The first option has the benefit that you can ensure the virtual floor will match the physical floor of the user. In some cases it's more important to have the users head match a virtual position (e.g. simulating sitting while the user is actually standing or vice versa), in which case the second option should do what you need. Just be aware that the mismatch between physical floor and virtual floor can be confusing to some.

Either way, it's important that the scale of the virtual world matches real-life units. That is to say 1 unit should match 1 meter in your scene. Otherwise the virtual world will feel off, being either too large or too cramped.

**Comment by DYBDDY** [comment] 2024-09-17 13:54
Thanks for the response.
If I take the first option , my rig was position="0 1.264 2.704",so I need to changed into position="0  -0.336  2.704" ?

**Comment by mrxz** [comment] 2024-09-17 14:14
> If I take the first option , my rig was position="0 1.264 2.704",so I need to changed into position="0 -0.336 2.704" ?

Yes, that way when the default camera height of 1.6 is added it should work out to "0 1.264 2.807" in your scene. When entering VR this should roughly line up as well (when standing up-right). There will be slight differences as people naturally differ in height.

Note that this implies the (virtual) floor in your scene should be at y=-0.336. If it isn't the user might get the feeling they are floating (if the virtual floor is lower) or that their feet are sunken into the ground (if the virtual floor is higher). Whether that will be an issue varies from scene to scene, so best to just try it out and see.

**Comment by DYBDDY** [comment] 2024-09-18 13:50
Thanks for the help,I guess I have to think about it,appreciate your guide.

**Comment by dmarcos** [comment] 2024-11-20 01:28
I think this is just a usage question and there's nothing actionable on the A-Frame side. Closing but can reopen if necessary

**Closed by dmarcos** 2024-11-20 01:28 UTC
