### ISSUE TITLE
a-asset component's init and update not work

### ISSUE THREAD

**Issue by runningo** [aframevr/aframe#2997] opened 2017-08-25 08:19 UTC
**Description:**

- A-Frame Version: 0.6.1
- Platform / Device: chrome
- Reproducible Code Snippet or URL:

Hello,
I want to make a asset component.

First, I set a    `<a-assets id="assets"></a-assets>`  element that did not have a child.
Second, added img source element by assets.appendChild(imgSource). 
And then assets.setAttribute('component','');
The attribute added well when i checked browser developer console.
But the component's init and update function did not work.

Does component can not be applied to `<a-assets>` element?
Anyone know?
thanks.

**Comment by dmarcos** [comment] 2017-08-25 18:44
`a-assets` is not an entity hence it does not take components. There's probably a different way to do what you're trying to achieve. I'm closing this since it's not a bug. You're welcome to open a StackOverflow question or swing by the Slack channels if you need help.

**Closed by dmarcos** 2017-08-25 18:44 UTC
