### ISSUE TITLE
Daydream controller doesnt work and entering VR mode throws a critical error

### ISSUE THREAD

**Issue by intensr** [aframevr/aframe#2769] opened 2017-06-13 07:28 UTC
**Description:**
Daydream controller doesnt work and entering VR Mode throws a critical error, somehow it works in custom builds and older versions of Aframe.

- A-Frame Version:
Tried various ones, first ofc the latest one 0.5.0 (master/f850c2f),
then some of the last 2 days 0.5.0 (master/9266cfd) and so on,
then I bundled an A-frame version with an older VR Polyfill (0. which PlayCanvas uses in their [WebVR example](https://playcanv.as/p/sAsiDvtC/) because this somehow still works including the Daydream controller,
nothing worked.

- Platform / Device:
**Hardware** ZTE Axon 7 + Google Daydream View
**OS** LineageOS 14.1 running Android 7.1.2 (lineage-14.1-20170612-nightly-axon7-signed) 2017-06-12 10:29:17 
**UA** Mozilla/5.0 (Linux; Android 7.1.2; ZTE A2017U Build/N2G47O) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.92 Mobile Safari/537.36

Yes its flashed, because ZTE just released a working 7.1 Nougat/Daydream version some days/weeks ago and there was no official version which supported daydream in February. I will also test if the error still occurs with the manufacturer stock version soon, but since it works on PlayCanvas and older A-frame examples i think this _makes no difference_.

- Main error:
Uncaught (in promise) Error: Failed to enter VR mode ('requestPresent'): Presentation request was denied
-> after triggering the VR mode button and thus the Daydream (Pls insert your device) screen never appears.

- Reproducible Code Snippet or URL:
Every **current** example from A-Frame on the mainpage and from private projects using current versions, too i.e. [ground control vr](https://github.com/aframe-capstone/ground-control-vr).
[Codepen](https://codepen.io/intenser/pen/gRMGBq)

- Working examples are:
-- [webvr.yoga](http://webvr.yoga) (working daydream controller)
-- [webvr.playcanvas.com](https://playcanv.as/p/sAsiDvtC/) (even tho it throws other errors and its not completly compareable it still shows the controller works in web with my setup)
-- https://webvr.info/samples/XX-vr-controllers.html?polyfill=1 (this works as intended like in gaze is no controller interaction just by touch you can change the background, then I enter VR mode the daydream window pops up and the controller is able to change the background on click)

- Screens
-- webvr.yoga which works
![aframe-webvryoga-test](https://user-images.githubusercontent.com/6901764/27070212-5348a388-5018-11e7-81cd-36d937f86b30.jpg)
-- aframe boilerplate with aframe master branch
![aframe-boilerplate-test](https://user-images.githubusercontent.com/6901764/27070213-534a0d2c-5018-11e7-8496-eb04d510be6b.jpg)
-- aframe boilerplate with aframe master branch and old polyfill (9.0.25 -> which is the same playcanvas uses atm)
![aframe-boilerplate-old-poly-test](https://user-images.githubusercontent.com/6901764/27070214-534e571a-5018-11e7-9504-42f7ca956836.jpg)

**Comment by machenmusik** [comment] 2017-06-13 12:16
If you are trying to use the recently added core daydream controller support, the component name is `daydream-controls` if I recall correctly - not `daydream-controller`

**Comment by machenmusik** [comment] 2017-06-13 13:10
Does using WebVR API in Chrome on Daydream still need either origin trial token or explicit WebVR feature flag enable?  If so, and you haven't done either, then I would expect requestPresent to fail due to browser denying permission.

**Comment by intensr** [comment] 2017-06-13 14:20
Iam so stupid sorry, you're right both times. I didnt find any deeper description about how to implement the controller because daydream component site is [not ready yet](https://aframe.io/docs/0.5.0/components/daydream-controls.html) (I guess?!) so i ripped it from another repo. I updated the pen however, still not sure if thats the _best_ implementation for testing if the controller works or not, but since the default daydream VR mode is not starting thats my first indicator.

About the flags: I disabled the following chrome://flags/ (WebVR, WebVR experimental rendering optimizations and Chrome VR). Now Aframe is switching to stereoscopic view but the daydream application is still not starting to enable the controller. Errors ahead:

![errors](https://user-images.githubusercontent.com/6901764/27086981-1826020a-5054-11e7-93a0-0bef5e11eae8.jpg)

The PlayCanvas example still works however, the webyoga site is now broken, too (just stereoscopic gaze view without controller) and the webvr xx controller example still works.

**Comment by machenmusik** [comment] 2017-06-14 07:05
So wait, if you turn OFF WebVR support (and then are presumably using polyfill not Daydream mode) then I don't think the controller will work.  My understanding is that you have to be in Daydream mode (WebVR enabled) for the controller to do its job.

**Comment by cvan** [comment] 2017-06-14 10:07
@intensr @caseyyee: this appears to be a dupe of issue #2677. we should close one of the bugs and  address this issue.

**Comment by machenmusik** [comment] 2017-06-14 12:39
A little testing of my own...

After a host of updates to Pixel phone and controller (all now on latest), and using Chrome beta (webvr enabled so no origin trial token dependency) with controller example codepen:
 https://codepen.io/machenmusik/pen/gWdgMy
Once you enter VR and click the track pad, since for security the Gamepad API will not provide controller data until the controller is used, the controller is visible (although it required re-home position).

Not sure everything is quite right though (I think button clicks were supposed to turn selected box blue)

**Comment by machenmusik** [comment] 2017-06-14 12:48
@cvan we probably want to work issues with official phone and controller firmware first, then come back to see if that fixes this one

**Comment by intensr** [comment] 2017-06-14 15:55
@cvan Yes its the same problem or at least close to it. I was not sure about it while opening the issue, thanks for the reference.
@machenmusik The thing that confused me with the polyfill is that while the WebVR flag is activated, the polyfill seems to be still active partly. However i tried various chrome browsers (beta, canary, etc.), versions and also Aframe (master) and vrpoly configurations (0.9.24-latest) and nothing seems to "work".

Just for clarification of a "working" daydream component / webvr application with a Daydream mobile device:
1. Loading site (your latest example for instance) on mobile device in gaze view (fixed crosshair to view)
2. Clicking VR button in lower right corner to enter "VR mode"
3. Enter Daydream ["Put your Phone in Room" ](http://i-cdn.phonearena.com/images/reviews/201314-image/Daydream-View-Review-014.jpg)
4. [ Pair Daydream controller Room](https://www.vrheads.com/sites/vrheads.com/files/styles/larger/public/field/image/2016/11/daydream-controller-failure.jpg?itok=pW1er5Vf)
5. Come back to site in stereoscopic view including [a visible controller](https://developers.google.com/web/showcase/2017/images/playcanvas/activate.png)

What happens in my case is 1. -> 2. -> 3. -> 4.  but then come back to stereoscopic view and the controller does not appear. But as I said before this works in several other WebVr applications even with poly or/and webvr flag, it does not matter. Also the controller is theoretically available, same as the daydream view, tested here:

<img width="715" alt="screen shot 2017-06-14 at 14 05 45" src="https://user-images.githubusercontent.com/6901764/27141037-683042d2-5127-11e7-9d11-ddf134f5bcb1.png">

[code here](https://codepen.io/intenser/pen/dRpmoe) (its not clean cause I tried a lot various stuff with a friend this morning)

I completely understand that you want to focus on officially supported devices, but the thing is the ZTE Axon 7 which I use is one of the [first supported Daydream devices](https://vr.google.com/daydream/smartphonevr/phones/) and should therefor be considered. I'm not the best developer but I'm pretty sure its just a minor issue regarding the adjustment of code once the problem is detected.

**Comment by machenmusik** [comment] 2017-06-14 16:02
@intensr the Axon 7 is an official Daydream device, but from original post I understood you were not using the production firmware ("yes its flashed") which I think would be the important Axon variant to support (complicated by the fact that AFAIK no one on current A-Frame team has one).  Using my Pixel that just updated itself and controller to 7.1.2, and Chrome beta with the WebVR flag thrown to work around the codepen-has-no-origin-trial-token issue, the Codepen I mentioned worked as expected with Daydream controller.

**Comment by intensr** [comment] 2017-06-14 16:12
Ok the flashed OS thing is not much of a difference since my brother has the same phone with original OS and its not working there, too. But sure you are right if no one can debug it since the lack of the hardware it wont work out. *cries deeply*

**Comment by caseyyee** [comment] 2017-06-14 17:00
Hey there, as an extra data point.

Here's my tests and what I saw with the Pixel XL this morning:

https://codepen.io/machenmusik/pen/YQGrWQ
https://iridescent-team.glitch.me/
https://threejs.org/examples/?q=day#webvr_daydream

For all examples:
- Does't work with standard Chrome.  No controller at all.
- Controller only works after interacting or letting it sit for some time (consistent with testing per Issue 2677) before becoming active with  both Canary and Beta.

**Comment by caseyyee** [comment] 2017-06-14 17:03
edit: there seems to be other issues here at play.

I'll post testing summary for just controller issue into 2677

**Comment by machenmusik** [comment] 2017-06-14 20:55
@intense if the page you are using is insecure or lacks origin trial token (which is true for Codepen) I think the WebVR flag must be manually enabled, and you need to touch button on the controller after entering VR for it to appear

**Comment by intensr** [comment] 2017-06-14 21:14
@machenmusik if the page is insecure it usually shows even in vr mode that the page is "not safe", however I tested everything, including the flag/token and without it I also pressed every button multiple times while in stereoscopic view its strange the controller seems to be there codewise but it simply doesnt work. I can confirm that the regular chrome browser does not work in every case, just canary or beta. The problem is I get no specific error or like no informative error which shows up that is different from playcanvas or the webvr.info examples which still work (like there are warnings and errors regarding dpdb and device size but thats it). In your example on codepen I only have gaze view BUT the webvr mode kicks in after pressing the vr button, otherwise the 3. "Put your Phone into the Daydream View" part from the post above would not start cause of the missing token/flag. 

Regarding the flashed OS I will visit my brother tomorrow and try it with his phone (I already did that but I missed the flags I guess). Problem with ZTE is their shipping of updates, so it only has 7.1.1 and I guess that will make a huge difference to the current Pixel Android builds but we will see.

**Comment by machenmusik** [comment] 2017-06-14 21:25
@intensr sorry if this is obvious but just to make sure w.r.t. the WebVR enable flag you have done  https://webvr.rocks/chromium

**Comment by dmarcos** [comment] 2017-06-14 22:38
In Chrome release channel one has to enable the GamepadExtensions in chrome://flags (besides WebVR) in order for the Daydream controller to show up. In Canary this is not necessary. In both cases, Chrome + GampeadExtensions and Canaray the controller shows up consistently on https://webvr.info/samples/XX-vr-controllers.html, https://threejs.org/examples/#webvr_daydream and also aframe laser-controls from master when run locally on my machine https://github.com/aframevr/aframe/tree/master/examples/test/laser-controls

@intensr Please use Chrome with WebVR and GamepadExtensions enabled on chrome://flags or Canary. The example included in master should work. https://github.com/aframevr/aframe/tree/master/examples/test/laser-controls

Please reopen if it does not.

**Comment by fernandojsg** [comment] 2017-10-22 19:13
I'm running into the same issue here. Daydream controller works on the webvr.info and threejs.org examples but not on the aframe examples.
Adding the controller to the hello-world example, I got the following state
![image](https://user-images.githubusercontent.com/782511/31865332-c5fa284a-b76d-11e7-8af0-f411426cd096.png)

**Comment by fernandojsg** [comment] 2017-10-22 19:23
It looks like some async problem maybe? As If I'm adding breakpoints that slow down the initialization sometimes it works and the controller appears

**Comment by dmarcos** [comment] 2017-10-22 19:59
Is that master or 0.7.1?

**Comment by fernandojsg** [comment] 2017-10-22 19:59
Both

**Comment by dmarcos** [comment] 2017-10-22 20:01
Something must have changed on the chrome side

**Comment by fernandojsg** [comment] 2017-10-22 20:04
@dmarcos could you reproduce it too?

**Comment by dmarcos** [comment] 2017-10-22 20:09
I don’t have a daydream around today

**Comment by fernandojsg** [comment] 2017-10-22 20:29
Go home get one! Everything is on fire!

**Comment by machenmusik** [comment] 2017-10-22 23:42
Do either of these work?
You'd have to manually enable WebVR and Gamepad Extensions in chrome://flags due to Codepen as per https://github.com/aframevr/aframe/issues/2769#issuecomment-308418328
 
https://codepen.io/machenmusik/pen/VMNgzg (aframe master)

https://codepen.io/machenmusik/pen/NggmZW (older pre-0.7.0-derived)

**Comment by fernandojsg** [comment] 2017-10-23 10:33
@machenmusik the first link doesn't work but the second one yep

**Comment by machenmusik** [comment] 2017-10-23 13:47
Then it seems like a 0.7.0 regression...

**Comment by fernandojsg** [comment] 2017-10-23 16:20
Git bisecting it right now... :\

**Comment by fernandojsg** [comment] 2017-10-23 16:43
It's some kind of async issue, as after getting an absurd bisect commit, I went through your two codepen examples and I reload them several times and I got both of them working and not working.

**Comment by dmarcos** [comment] 2017-10-23 16:57
I spent ours testing daydream for 0.7.0 and the laser controls example was working rock solid. I’m almost certain that something must have changed on the chrome side

**Comment by dmarcos** [comment] 2017-10-23 17:00
Testing on Canary: https://aframe.io/aframe/examples/test/laser-controls/ works fine for me

**Comment by dmarcos** [comment] 2017-10-23 17:02
FYI `hand-controls` does not support 3DOF anymore. `laser-controls` is the recommended responsive input.

**Comment by fernandojsg** [comment] 2017-10-23 19:11
@dmarcos yep I'm not using `hand-controls` I'm testing always against `laser-controls` and I'm still getting random failures :\ I'll post if I find something

**Comment by fernandojsg** [comment] 2017-10-23 20:00
Reproducing the issue: https://www.youtube.com/watch?v=OvODqJ9l_Yc

**Closed** 2017-10-27 04:31 UTC
