### ISSUE TITLE
This data is empty

### ISSUE THREAD

**Issue by a0m0rajab** [aframevr/aframe#4958] opened 2021-11-11 07:28 UTC
**Description:**

- A-Frame Version: 1.2.0
- Platform / Device: Windows/Laptop
- Reproducible Code Snippet or URL: 

# The issue: 

Using a component that have default data without typing them in the entity, returns the data as Boolean rather than an object. 

The code:
```javascript
AFRAME.registerComponent("rotate", {
  schema: {
    lookUp: { type:'string' ,default: "ArrowUp" },
    lookDown: { type:'string' ,default: "ArrowDown" },
    lookLeft: { type:'string',default: "ArrowLeft" },
    lookRight: { type:'string',default: "ArrowRight" },
    maxLookgAngle: { type:'number'  ,default: 60 },
  },
  convertKeyName: function (keyName) {
    if (keyName == " ")
      return "Space";
    else if (keyName.length == 1)
      return keyName.toUpperCase();
    else
      return keyName;
  },

  registerKeyDown: function (keyName) {
    // avoid adding duplicates of keys
    if (!this.keyPressedSet.has(keyName))
      this.keyPressedSet.add(keyName);
  },

  registerKeyUp: function (keyName) {
    this.keyPressedSet.delete(keyName);
  },

  isKeyPressed: function (keyName) {
    return this.keyPressedSet.has(keyName);
  },
  init: function () {
    console.log("İnited Rotation");
    console.log(this,"inited"); // Here you can check the results
    let lookControls = this.el.components["look-controls"]
    window.lookControls = lookControls;
    console.log(window.lookControls);
    // Keep track of pressed keys.
    this.keyPressedSet = new Set();
    this.maxLookgAngle = THREE.Math.degToRad(this.data.maxLookgAngle);
    let self = this;
    self.lookControls = lookControls;
    document.addEventListener("keydown",
      function (eventData) {
        self.registerKeyDown(self.convertKeyName(eventData.key));
      }
    );

    document.addEventListener("keyup",
      function (eventData) {
        self.registerKeyUp(self.convertKeyName(eventData.key));
      }
    );
  },
  tick: function () {
    // console.log("Ticked Rotation");
    let checkLookingUp = this.lookControls.yawObject.children[0].rotation.x
    if (this.isKeyPressed(this.data.lookRight))
      this.lookControls.yawObject.rotation.y -= 0.05
    if (this.isKeyPressed(this.data.lookLeft))
      this.lookControls.yawObject.rotation.y += 0.05
    if (this.isKeyPressed(this.data.lookUp))
      this.lookControls.yawObject.children[0].rotation.x += 0.05
    if (this.isKeyPressed(this.data.lookDown))
      this.lookControls.yawObject.children[0].rotation.x -= 0.05
    if (checkLookingUp > this.maxLookgAngle)
      this.lookControls.yawObject.children[0].rotation.x = this.maxLookgAngle
    if (checkLookingUp < -this.maxLookgAngle)
      this.lookControls.yawObject.children[0].rotation.x = - this.maxLookgAngle
  }
});
```

The result
```javascript
NewComponent {el: a-entity#camera, id: undefined, attrName: 'rotate', evtDetail: {…}, initialized: false, …}attrName: "rotate"attrValue: "true"
data: "true"
el: a-entity#cameraevents: {}evtDetail: {id: undefined, name: 'rotate'}id: undefinedinitialized: trueisObjectBased: trueisPlaying: trueisSingleProperty: falseisSinglePropertyObject: falsekeyPressedSet: Set(0) {size: 0}lookControls: NewComponent {el: a-entity#camera, id: undefined, attrName: 'look-controls', evtDetail: {…}, initialized: true, …}maxLookgAngle: NaN
nextData: {lookUp: 'ArrowUp', lookDown: 'ArrowDown', lookLeft: 'ArrowLeft', lookRight: 'ArrowRight', maxLookgAngle: 60}objectPool: {pool: Array(10), grow: ƒ, recycle: ƒ, size: ƒ, use: ƒ}
oldData: "true"
parsingAttrValue: {"": 'true'}
previousOldData: {}
throttledEmitComponentChanged: ƒ ()[[Prototype]]: Object 'inited'
```

The needed property values are returned in the nextData property. 

I was expecting to have an object of the data to play around and use them, as how the introduction explained.  [Handling Data](https://aframe.io/docs/master/introduction/writing-a-component.html#handling-property-updates)

**Comment by a0m0rajab** [comment] 2021-11-11 07:33
The issue could be solved when I use the nextData property, yet I wanted to know if there is any change in the API to update the docs :) or if there is something missed.

**Comment by dmarcos** [comment] 2021-11-11 21:42
Can you provide a [simple glitch](https://glitch.com/~aframe) to reproduce?

**Comment by dmarcos** [comment] 2021-11-11 22:01
An example on glitch: https://glitch.com/edit/#!/amethyst-unleashed-quokka?path=index.html%3A9%3A73

I might not be understanding the issue

**Comment by dmarcos** [comment] 2021-11-11 22:02
An example on glitch: https://glitch.com/edit/#!/amethyst-unleashed-quokka?path=index.html%3A9%3A73

I might not be understanding the issue

**Comment by a0m0rajab** [comment] 2021-11-12 14:24
it's confusing to me as well, 

Here is the error reproduction code: 
https://glitch.com/edit/#!/aframe-data-true

we are using react and the npm package, would that be the reason for the issue?

**Comment by dmarcos** [comment] 2021-11-12 14:32
Not sure what the expected behavior is vs what you get. Can you elaborate?

Related to React. Unlikely but not familiar with it. Can you provide a simple example only with A-Frame that illustrates the issue?

**Comment by a0m0rajab** [comment] 2021-11-12 14:38
Sure, I am expecting the data to be an object to reach the properties from it, yet the behavior right now is only giving a "true" message. 

This is the simplest example that I could provide for react, it's generated from the main template. 

in the src/App.js, you can find the A-Frame code and the files imported, in the src/aframe.js you can find the component that I am trying to use. 

I have exposed the component to the window to test it , and logged the input there you can see that it's logging only true.

**Comment by a0m0rajab** [comment] 2021-11-12 14:44
I am expecting to be able to get the this.data.test result as 1, rather than just a true.

**Comment by arpu** [comment] 2021-11-12 14:49
try to set the component with ```rotate=""```does this works?

**Comment by a0m0rajab** [comment] 2021-11-12 14:51
@arpu, yes it worked! 🎉 
could you explain what was the issue? 🤔

**Comment by a0m0rajab** [comment] 2021-11-12 14:53
for future googlers, 

here is the code that causing the issue: 

```javascript
 <a-entity id="camera" camera
          position="0 1.6 0"
          rotate>
        </a-entity>
```
initializing the rotate as the previous comment solved the issue.

**Comment by arpu** [comment] 2021-11-12 15:36
not sure what the problem here is maybe @dmarcos  has more idea

**Comment by vincentfretin** [comment] 2021-11-12 16:11
As far as I know in react writing just `rotate` is equivalent of `rotate={true}` that is why you get a boolean instead of default object.

**Comment by dmarcos** [comment] 2021-11-12 16:24
Thanks @arpu @vincentfretin! React experts in da haus.

Mistery solved. Closing this because there’s no further action on a-frame side.

**Closed by dmarcos** 2021-11-12 16:24 UTC
