### ISSUE TITLE
Edge on WMR doesn't enter immersive mode on 0.9.2 helloworld

### ISSUE THREAD

**Issue by Utopiah** [aframevr/aframe#4253] opened 2019-08-09 08:35 UTC
**Description:** Edge on WMR doesn't enter immersive mode on 0.9.2 helloworld

- A-Frame Version: 0.9.2
- Platform / Device: Edge 42.17134.1.0 with Odyssey+
- Reproducible Code Snippet or URL: https://aframe.io/examples/showcase/a-painter/ (0.7) works but https://aframe.io/examples/showcase/helloworld/ 0.9.2 doesn't, only getting in fullscreen.

**Comment by dmarcos** [comment] 2019-08-13 18:02
I need to grab a WMR headset. If anyone can debug it will be helpful. I would start stepping over this code: https://github.com/aframevr/aframe/blob/master/src/core/scene/a-scene.js#L262

**Comment by SamiraAtMicrosoft** [comment] 2019-10-02 17:56
Thanks for the report! I gave this a try and was only able to repro this once (where HelloWorld entered fullscreen instead of entering immersive mode). Upon debugging and subsequent re-tries I can no longer reproduce this. 

The intermittence might suggest a timing problem between when the vrDisplay in utils.device has been assigned and when checkHeadsetConnected() is called from enterVR(). 

Will try to debug further as soon as I can grab a repro again.

**Comment by dmarcos** [comment] 2020-10-23 23:19
I think this is no longer a problem. Edge and Windows MR have moved to WebXR / OpenXR and [A-Frame examples](https://aframe.io/aframe/examples/) should work. Version older than 1.0.4 might not work since are not compliant with the final WebXR spec. Closing but can reopen if necessary

**Closed by dmarcos** 2020-10-23 23:19 UTC
