### ISSUE TITLE
a-frame scene is black

### ISSUE THREAD

**Issue by igorroman777** [aframevr/aframe#4536] opened 2020-03-30 18:14 UTC
**On my page www.artwista.com I have in VR in i-frame 
built-in. In chrome browser on Galaxy Tab A and android see 
I mean a-frrame scene But almost everything is **black**.:**

- A-Frame Version: 1.0.4
- Platform / Device: Android 7.1 / Chrome 80.0.3987.149 / Galaxy Tab A 
- Reproducible Code Snippet or URL: www.artwista.com

**Comment by dmarcos** [comment] 2020-04-01 21:12
Any errors on console? FYI, there's known issues on old devices and shaders using `highp` and Adreno 300 series GPU. More info:

https://github.com/mrdoob/three.js/issues/14570

https://github.com/aframevr/aframe/pull/3977

**Comment by igorroman777** [comment] 2020-04-02 19:18
no errors on console

**Comment by dmarcos** [comment] 2020-10-23 22:54
Closing due to lack of info to reproduce. We can reopen if necessary

**Closed by dmarcos** 2020-10-23 22:54 UTC
