### ISSUE TITLE
blank screen when using iframes in Safari(iOS)

### ISSUE THREAD

**Issue by a10k** [aframevr/aframe#964] opened 2016-02-12 11:49 UTC
Works fine when opened on its own in the browser, but when inserted as an iframe in another page only the fullscreen icon and cursor are shown on mobile safari (iOS) the same works fine on desktop.

Note: The elements in the scene flash for a second before they disappear when the iframe is loaded.

**Comment by dmarcos** [comment] 2019-02-01 07:07
Closing due to lack of info / link to reproduce. [A-Frame examples](aframe.io) are hosted in iframes and render as expected. If you’re still affected, please reopen an issue with a link to an example that reproduces the bug

**Closed by dmarcos** 2019-02-01 07:07 UTC
Labels: mobile
