### ISSUE TITLE
positions in Inspector does not match in actual scene

### ISSUE THREAD

**Issue by EasonSun** [aframevr/aframe#4529] opened 2020-03-24 01:01 UTC
**Description:**
The coordinates or view point of the inspector and the real website is different. I would like to use the inspector to place a button (red dot) on a certain place and get the coordinates so that I can place it in code. Thx

On web:
<img width="1680" alt="Screen Shot 2020-03-23 at 5 51 52 PM" src="https://user-images.githubusercontent.com/9789748/77377256-cbe69c00-6d2f-11ea-8646-c98422b85a1a.png">

On Inspector
<img width="1680" alt="Screen Shot 2020-03-23 at 5 52 04 PM" src="https://user-images.githubusercontent.com/9789748/77377260-cf7a2300-6d2f-11ea-8465-9234497b33f9.png">

- A-Frame Version: 1.0.0
- Platform / Device: chrome 80.0.3987.132 / Safari 13.0.5 on macbook
- Reproducible Code Snippet or URL: 

```
import React from "react";
import Button from "@material-ui/core/Button";
import withStyles from "@material-ui/core/styles/withStyles";
import "aframe";

const styles = theme => ({
  button: {
    fontSize: "12px",
    // margin: theme.spacing.unit,
    minWidth: 350
  }
});

class Interior extends React.Component {
  constructor(props) {
    super(props);

    this.state = {
      menOne: "red",
      ball: "blue",
      weurfel: "green",
      zylinder: "orange",
      eins:
        "https://uploads.codesandbox.io/uploads/user/b6cae962-6437-42df-9d45-264020196e51/Ducs-sky360.jpg",
      zwei: "skyZwei.jpg",
      drei: "skyDrei.jpg"
    };
  }

  Eventhandler1 = () => {
    alert("1");
  };

  Eventhandler2 = () => {
    alert("2");
  };

  Eventhandler3 = () => {
    alert("3");
  };

  render() {
    return (
      <div className="Interior">
        <a-scene>
          <a-entity laser-controls="hand: right" />
          <a-entity
            position="0 0.809 0"
            camera="active:false;userHeight:1.6"
            wasd-controls=""
            look-controls=""
            aframe-injected=""
            data-aframe-inspector-original-camera=""
            data-aframe-inspector="default-camera"
          />
          <a-entity cursor="rayOrigin: mouse" />

          <a-plane
            color={this.state.menOne}
            position="-1.4 2.04665 -1.984"
            // left/right, up/down, front/back
            scale="0.05 0.05 0.05"
            rotation=""
            radius="1"
            material=""
            geometry="primitive: circle"
            onClick={this.Eventhandler1}
          />

          <a-plane
            color={this.state.menOne}
            position="0 2.04665 -1.984"
            // left/right, up/down, front/back
            scale="0.05 0.05 0.05"
            rotation=""
            radius="1"
            material=""
            geometry="primitive: circle"
            onClick={this.Eventhandler2}
          />

          <a-plane
            color={this.state.menOne}
            position="0 1 -1.984"
            // left/right, up/down, front/back
            scale="0.05 0.05 0.05"
            rotation=""
            radius="1"
            material=""
            geometry="primitive: circle"
            onClick={this.Eventhandler3}
          />

          <a-sky id="sky" src={this.state.eins} rotation="0 -90 -15" />
          {/* This rotation will change the position of the buttons; the position is relative to the initial angle of this */}
        </a-scene>
      </div>
    );
  }
}

export default withStyles(styles)(Interior);

```

**Comment by dmarcos** [comment] 2020-03-26 21:11
Better if you can provide a link to reproduce. Glitch is a good option https://glitch.com/~aframe

**Comment by dmarcos** [comment] 2020-10-23 22:31
Closing due to lack of info to reproduce.

**Closed by dmarcos** 2020-10-23 22:31 UTC
