### ISSUE TITLE
Design a prettier icon for AR mode.

### ISSUE THREAD

**Issue by dmarcos** [aframevr/aframe#4326] opened 2019-11-21 21:52 UTC
We know have an [awesome AR mode](https://twitter.com/dmarcos/status/1188990196525584384?s=20) for Chrome and ARCore devices thanks to @klausw I personally like the icon he made but some think it could prettier. If there are designers out there interested in contributing one to the community it will be greatly appreciated. Current icon below and [inkscape svg](https://drive.google.com/file/d/1ERGDFxHC5urje5rC5P1H0YCDAxsQgC_m/view?usp=sharing) and [ optimized svg](https://drive.google.com/open?id=1c8GoqWWb3POpsR6HhCxoDl_aNRC2l7T0) files for reference

![enter-ar-screen2](https://user-images.githubusercontent.com/39342/69379316-19a9a580-0c65-11ea-8fb1-b580af0d4b6d.png)

**Comment by thedart76** [comment] 2019-11-22 13:16
More than happy to give a hand with this 🙂
Here is my proposal, consistent with the VR mode icon:
![A-Frame-Enter-WebXR](https://user-images.githubusercontent.com/30973948/69428683-bcc3f300-0d29-11ea-9b3a-c8ae2fc6b33a.png)
which would render like this:
![A-Frame-Enter-WebAR](https://user-images.githubusercontent.com/30973948/69428717-cf3e2c80-0d29-11ea-90b2-96ae20bdbd83.png)
Let me know if you like and decide to go for it. I will then share the source file (.ai and .svg)

**Comment by dyarosla** [comment] 2019-11-22 16:38
So long as WebXR is mostly applicable to overlay-AR via mobile devices, maybe something like

https://www.iconfinder.com/icons/4143712/ar_augmented_reality_mobile_icon

**Comment by thedart76** [comment] 2019-11-22 16:41
Sharing rendering also on light bg:
![aframe-xr-modes-light-bg](https://user-images.githubusercontent.com/30973948/69443706-dde70c80-0d46-11ea-9e55-ec74f348c354.png)

**Comment by thedart76** [comment] 2019-11-22 16:43
This is design option v2, instead.
Sharing icon + rendering on light and dark bg:

![A-Frame-Enter-WebXR-v2](https://user-images.githubusercontent.com/30973948/69443800-0a028d80-0d47-11ea-879d-4479539d3742.png)

![aframe-xr-modes-v2-light-bg](https://user-images.githubusercontent.com/30973948/69443824-171f7c80-0d47-11ea-83de-fa39f7cc1f35.png)

![aframe-xr-modes-v2-dark-bg](https://user-images.githubusercontent.com/30973948/69443844-20104e00-0d47-11ea-8b6a-aceecd1e4474.png)

**Comment by klausw** [comment] 2019-11-22 19:00
In case it helps, here's some background information and random thoughts.

The buttons get shown conditionally, based on detected capabilities, so a given device may show none, one of them, or both. The "AR" button only appears if the devices indicates that it supports the "immersive-ar" WebXR mode.

The effect of the two buttons is something like this:

- "enter VR" - be as immersive as possible, hiding the real world and focusing on the virtual scene which supplies its own background.

- "enter AR" - show the virtual objects, but integrate it with the real world. The virtual scene should use a transparent background.

Currently, in Chrome on an Android smartphone, the VR button would launch Cardboard or Daydream View mode, and the AR button (if available) would use ARCore for a handheld AR mode using the phone camera.

A VR headset could choose to support AR mode if it can enable a passthrough camera that shows a 3D view of the environment.

On a see-through AR headset, VR and AR modes may be similar if the headset optics can't draw opaque black to hide the environment. There's still a difference though. In VR mode, the application would draw its own background, while in AR mode it should not try to draw a background, letting the scene merge with the real-world environment.

Since the AR mode supports both headsets and smartphone handheld AR, it seems tricky to express this through an icon that shows what the device looks like, especially since a smartphone isn't a very distinct shape on its own. Would it work to have a split icon, showing half a smartphone on one side and half of an AR headset on the other side?

Alternatively, is there a way to get across the "draw scene background" vs "integrate with environment" aspect in the icon?

Currently there's no standard way to tell if the WebXR "immersive-ar" mode is headset based or handheld before starting a session, and that's largely intentional to avoid splitting the already-small ecosystem even further. I guess it may be possible to use heuristics to choose the most-likely-appropriate icon based on user agent information, and guessing wrong wouldn't be too bad since the button would still do the same thing, but I'm not convinced it would be a good idea to go down that path.

**Comment by brendanciccone** [comment] 2019-11-22 20:11
In my opinion, the AR mode icon should be as universal and understandable as possible, within reason. Showing just the demo shapes from A-Frame is showing people something that they would only understand if they worked with A-Frame. Also, if they aren't familiar with certain headset, like the Hololens, then average users may be perplexed by this second icon.

People are at least moderately accustomed to the VR cardboard icon and get it right away. When I show people prototypes or things in A-Frame they know to click that button.

I think that AR mainly exists in a different context too, where the main place people experience it is through mobile devices. I think that the icon should reflect that via a cube or some sort of 3D figure coming out of a non-descript shape, so it's not limited to just mobile. 

Anyways, here is my attempt based upon this reasoning.

![1 Icon](https://user-images.githubusercontent.com/39386738/69457087-44b1f900-0d3a-11ea-8444-dc5b6da753e2.png)

![2 Mockup](https://user-images.githubusercontent.com/39386738/69457088-44b1f900-0d3a-11ea-8937-f85ad74f944f.png)

**Comment by thedart76** [comment] 2019-11-23 00:23
Design option v3: minimal and device agnostic.

![A-Frame-Enter-WebXR-v3](https://user-images.githubusercontent.com/30973948/69469196-72715f00-0d87-11ea-9c8b-05eb4c5bbca0.png)

![aframe-xr-modes-v3-light-bg](https://user-images.githubusercontent.com/30973948/69469200-78ffd680-0d87-11ea-87dd-9a9b8cf655fd.png)

![aframe-xr-modes-v3-dark-bg](https://user-images.githubusercontent.com/30973948/69469206-81f0a800-0d87-11ea-85ac-b46c8a6f532f.png)

**Comment by brendanciccone** [comment] 2019-11-23 00:52
@thedart76 I personally love it, awesome work!

**Comment by dmarcos** [comment] 2019-11-23 01:21
@brendanciccone @thedart76 Thank you! I love how you build on top of each other ideas 👍 I also like the cube a lot. Only problem is when a stylized cube is shown in perspective is hard to identify it as a cube, in particular when small. Maybe not a big issue.

**Comment by brendanciccone** [comment] 2019-11-23 01:30
@dmarcos the visibility on, let’s say a smaller device like a phone, is actually my biggest concern with my design. I think the solid filled cube that @thedart76 made makes it clear there’s two dimensions/realities/whatever even to someone unfamiliar with VR/AR.

**Comment by ngokevin** [comment] 2019-11-23 01:47
The simplest way to indicate AR might be an icon that just says AR. It's not as slick, but I think that might more clear.

**Comment by dmarcos** [comment] 2019-11-23 01:51
Following same concept but the idea might get lost

![Image from iOS (3)](https://user-images.githubusercontent.com/39342/69471117-b72dd380-0d50-11ea-8766-3709133c6f28.jpg)

**Comment by thedart76** [comment] 2019-11-23 05:25
@brendanciccone Thanks! It's an iteration of your concept 😉 
Design option v4 following on @ngokevin 's feedback and @dmarcos 's sketch:

![A-Frame-Enter-WebXR-v4](https://user-images.githubusercontent.com/30973948/69473895-93e74080-0db1-11ea-9918-7a0600d4879e.png)

![aframe-xr-modes-v4-light-bg](https://user-images.githubusercontent.com/30973948/69473900-9a75b800-0db1-11ea-976d-2720c30220ee.png)

![aframe-xr-modes-v4-dark-bg](https://user-images.githubusercontent.com/30973948/69473903-9fd30280-0db1-11ea-9517-90bf0b31cf58.png)

**Comment by dmarcos** [comment] 2019-11-23 16:05
@thedart76 Thanks for the quick turn around. I think your cube idea is much sleeker. The `AR` button likely convey functionality better. Maybe centering A and R letters in the boxes makes the icon cleaner but the original idea gets lost a bit.

**Comment by thedart76** [comment] 2019-11-23 16:44
@dmarcos We can give it a shot, I will share this new version soon 👍
My only concern is that, by centering the A and the R letters in the boxes, the AR acronym might get split up making the button look like a toggle for 2 different A / R states. Let's see...

**Comment by brendanciccone** [comment] 2019-11-23 17:02
That is my concern as well about using the ‘AR' rather than the cube. I think that new users may think it is something totally different than AR. Could always get user feedback though and see what someone brand new to AR/VR thinks. 🤷‍♂️

**Comment by dmarcos** [comment] 2019-11-23 17:51
We can do a twitter poll to collect some opinions

**Comment by thedart76** [comment] 2019-11-23 18:04
@dmarcos Here is the updated **AR version**:

![01a-aframe-enter-ar-letters](https://user-images.githubusercontent.com/30973948/69483097-0e987600-0e1b-11ea-8072-b1e06577caba.png)

![01b-aframe-enter-ar-letters-rendered-light](https://user-images.githubusercontent.com/30973948/69483098-135d2a00-0e1b-11ea-9378-7566bf02d118.png)

![01c-aframe-enter-ar-letters-rendered-dark](https://user-images.githubusercontent.com/30973948/69483101-18ba7480-0e1b-11ea-8574-434a6a88a51a.png)

**Comment by thedart76** [comment] 2019-11-23 18:05
This is an updated **Cube version** for better readability:

![02a-aframe-enter-ar-cube](https://user-images.githubusercontent.com/30973948/69483149-bca42000-0e1b-11ea-9b12-4fc9a5d5a00a.png)

![02b-aframe-enter-ar-cube-rendered-light](https://user-images.githubusercontent.com/30973948/69483152-c0d03d80-0e1b-11ea-9cec-1952485c0911.png)

![02c-aframe-enter-ar-cube-rendered-dark](https://user-images.githubusercontent.com/30973948/69483153-c463c480-0e1b-11ea-9420-c2b8dec76d9f.png)

**Comment by dmarcos** [comment] 2019-11-23 18:06
Thanks! Yeah it’s see what you meant. The AR button now it looks like a toggle.

**Comment by thedart76** [comment] 2019-11-23 18:09
Let me try to tweak the first version of the AR icon, maybe I can improve the readability while preserving the design concept.

**Comment by thedart76** [comment] 2019-11-23 18:10
In the meantime, which version of the Cube do you prefer, the previous or updated one?

**Comment by thedart76** [comment] 2019-11-23 21:22
@dmarcos I have finished doing the final tweaking to all the icons.
Sharing below the 3 design options we could use for the Twitter poll.

**Option 1**: 3D Cube v1

![01-aframe-enter-xr-3d-cube-v1](https://user-images.githubusercontent.com/30973948/69485409-f9314500-0e36-11ea-9162-fd92eb42e4d6.png)

**Option 2**: 3D Cube v2

![02-aframe-enter-xr-3d-cube-v2](https://user-images.githubusercontent.com/30973948/69485414-0a7a5180-0e37-11ea-839f-f9892c979d69.png)

**Option 3**: AR Letters

![03-aframe-enter-xr-ar-letters](https://user-images.githubusercontent.com/30973948/69485420-1d8d2180-0e37-11ea-980f-f5a77150a9f5.png)

**Comment by thedart76** [comment] 2019-11-23 21:26
**PS**: You may want to create a 4-tweet thread so people will not get confused with "which is which". I mean something like this (unless you already have in mind something else):

----- Thread Start -----
**Poll Text**
Lorem Ipsum...
Vote:
• Option 1
• Option 2
• Option 3
1/4
-------- Tweet 2 --------
**Title**
Option 1: 3D Cube v1
(image Option 1)
2/4
-------- Tweet 3 --------
**Title**
Option 2: 3D Cube v2
(image Option 2)
3/4
-------- Tweet 4 --------
**Title**
Option 3: AR Letters
(image Option 3)
4/4
----- Thread End -----

**Comment by thedart76** [comment] 2019-11-23 22:20
@dmarcos I forgot to mention that I deliberately scaled down the above icons to test and show their (approximate) readability when being displayed on mobile devices.

I'm sharing the ones at standard size as well should you prefer to use them in the Twitter poll (average Desktop monitors are not as good as mobile phones' displays):

**Option 1**: 3D Cube v1 (normal size)

![01-aframe-enter-xr-3d-cube-v1-normal](https://user-images.githubusercontent.com/30973948/69486048-46b1b000-0e3f-11ea-91be-bb5bfcd20454.png)

**Option 2**: 3D Cube v2 (normal size)

![02-aframe-enter-xr-3d-cube-v2-normal](https://user-images.githubusercontent.com/30973948/69486055-60eb8e00-0e3f-11ea-8930-2194a7b4ee9c.png)

**Option 3**: AR Letters (normal size)

![03-aframe-enter-xr-ar-letters-normal](https://user-images.githubusercontent.com/30973948/69486061-7365c780-0e3f-11ea-9e8c-9aa36a864bf8.png)

**Comment by thedart76** [comment] 2019-11-23 22:29
Or maybe you could use both the sizes for each design option in the poll like this (with reference to the Twitter thread structure above):

...
1/4
-------- Tweet 2 --------
Option 1: 3D Cube v1
(image Option 1 normal)
(image Option 1 small)
2/4
-------- Tweet 3 --------
Option 2: 3D Cube v2
(image Option 2 normal)
(image Option 2 small)
3/4
...

**Comment by dmarcos** [comment] 2019-11-23 23:00
This looks awesome. Thanks for all the work. I’ll tweet from the A-Frame account on Monday. We would get less feedback during the weekend.

**Comment by thedart76** [comment] 2019-11-24 05:41
Thanks. Yeah, wise choice. Let's see what people say. You can count on my availability should we need to further iterate and make any adjustments.

**Comment by dmarcos** [comment] 2019-11-25 18:33
Retweets appreciated: https://twitter.com/aframevr/status/1199031334674554880
Thanks everybody for helping with this 🙇

**Comment by alfa256** [comment] 2019-11-25 18:43
I'd like to differentiate modes a bit more with a finger or hand on the AR icon. It's hard to know which difference it'd make for the user already viewing the scene on a phone as it's already 3D.

**Comment by klausw** [comment] 2019-11-25 18:57
I like all of the suggested options, thank you for all the contributions.

One part I'm wondering about is that in the "AR" text, it looks as if the "R" directly continues the left half's white rectangle, with no visible left edge to the "R", and while that may be intentional, I find it a bit visually confusing. Have you tried slightly adjusting the position of the "R" to leave just a bit of transparent border on its left? (I agree that the centered letters look too much like an "A vs R" toggle.) Or maybe make the letter colors a bit less intense, i.e. dark/light gray instead of black/white?

**Comment by thedart76** [comment] 2019-11-25 22:08
@klausw Yes, representing the "R" letter that way was intended for 2 reasons:
1) Readability: leaving a small gap between the left half's white background and the "R" letter creates "noise" especially when the icon is scaled down.
2) Concept: extending the "R" letter from the left half's white background represents the AR content overlapping the real-world layer.

**Comment by ngokevin** [comment] 2019-11-26 00:40
I sort of agree the R the way it is makes it slightly more difficult to read, although it's cool.

**Comment by thedart76** [comment] 2019-11-26 11:26
Happy and available to iterate on the R letter, will share the updated version soon 👍 
@ngokevin can you elaborate more on _"giving your text treatment to the VR icon as well"_?
Do you mean using the "VR" letters for that button instead of the current goggles icon?
If so, what about the background and how do you imagine it?

**Comment by ngokevin** [comment] 2019-11-26 11:45
Yeah, I feel certain just "AR" and "VR" text is the most clear. Those goggles I am pretty sure people outside WebVR won't know what it is. At least for English, though I think the acronym has transcended several languages.

For the background, I don't think the black/white represent anything. We could just have black text on white, or trasparent text on white, although I know that doesn't sound the most exciting and wastes some of your artistic vision. Perhaps we can get something interesting still. Thanks for being so rapid.

**Comment by thedart76** [comment] 2019-11-26 12:27
Thanks for your confirmation on the "AR" and "VR" text.
I agree with you about the background: the 2 halves wouldn't represent anything VR-related. I would use transparent "VR" letters on white background, because the other way around (fully white 'VR" letters on transparent background) sounds more appropriate for AR, where the content overlaps the real-world layer (no problem with creating and showing both the versions for us to make a decision, though).

About my artistic vision being wasted... Too many people are outside WebXR/XR yet, so I am here to help with some effective design favouring the icon's usefulness over its aesthetic; if we manage to include that factor as well then it will be even better, but I am ready to keep the Fine Art for my spare time 😉

Yeah, using some perspective and 3Dness on the letters, while trying to ensure the same level of readability, might be an idea worth exploring.

**Comment by ngokevin** [comment] 2019-11-26 13:54
Let's give it a shot. 'm okay just going simple and ignoring the 3D text idea.

**Comment by thedart76** [comment] 2019-11-26 14:46
So, to make both the options meaningful I followed the principle behind the XR acronym: given the "X" as the variable, the "R"eality is what both the buttons will share; hence the "R" letters' styling should be consistent, whereas the only letter highlighting the difference between AR and VR mode is going to be the "A".

Enough with the theory.
New versions below showing the buttons on a 3D background to stress the icon readability:

**Option 1**: "A" letter on transparent background

![01-aframe-enter-xr-icons-A-on-transparent](https://user-images.githubusercontent.com/30973948/69643495-560d4500-105b-11ea-89ba-f5e6a3c0f406.png)

**Option 2**: "A" letter on white background

![02-aframe-enter-xr-icons-A-on-white](https://user-images.githubusercontent.com/30973948/69643551-645b6100-105b-11ea-944b-5d3ce0bb123f.png)

As usual, feedback is very welcome.

**Comment by thedart76** [comment] 2019-11-26 14:53
**PS**: in the enter AR button, to make the "R" letter readable and cancel any "noise" I had to move it away from the "A" as much as possible. That is, IMO, the maximum distance acceptable between the 2 letters before ending up with the "A/B toggle" effect we already discussed yesterday.

**Comment by thedart76** [comment] 2019-11-26 15:07
@dmarcos In the next Twitter poll it might be useful to specify something like:
"Once you click on the images, make sure to do Right-Click > View Image to see the icons at 100% scale and avoid any blurring."
What are your thoughts?

**Comment by dmarcos** [comment] 2019-11-26 15:26
Awesome work! Only issue I see is that people are used to the VR icon. Not sure if it’s worth to change

About twitter poll. FWIW, on mobile image quality is good enough to evaluate. Is there a way to make them look better without extra action? I guess is a twitter thing.

**Comment by dmarcos** [comment] 2019-11-26 15:30
If we are going to do text. VR button with white background and AR button with transparent background are perhaps the most representative. AR is like VR but with video feed as background

**Comment by brendanciccone** [comment] 2019-11-26 16:55
My concern with the text is that unlike an icon, it is only letters and is representative of anything with that abbreviation. For those not in this industry, VR and AR could stand for a variety of things.

For example, AR could refer to everything from annual returns to rifles. VR isn't too bad though as it is most commonly used to refer to virtual reality. 

Also, visually they look perhaps too similar when they're both text-based and could cause people to misclick.

I think at this point when users see that cardboard icon they think goggles, virtual reality, headsets, etc. I think that the cube with added depth presents something different enough than the VR icon, but within context makes enough sense.

**Comment by thedart76** [comment] 2019-11-26 16:57
@dmarcos About the Twitter poll: yeah, I can increase the canvas size, so the images will not be scaled up. Twitter should display the magnifying-glass icon at that point, which will allow the user to simply click on the images and toggle between zoom-in and zoom-out (both the icon and the zooming action are surely more established patterns on Desktop).

About the icons: I like the idea of using all transparent background for the AR icon. You mean just like the VR button in today's new Option 2, right?

If so, we will have apparently filtered and selected the 3 new options:
1) All letters ("AR" on transparent background and "VR" on white background)
2) New AR button + current VR goggles icon (BTW, here still both the "AR" letters on transparent background or just the "A" letter on transparent background like in today's new Option 1?)
3) Shaded cube + current VR goggles icon (this option is leading the current poll)

I will work on them when I am back home later on tonight or maybe tomorrow, now I am about to go to a machine learning meetup.

**Comment by dmarcos** [comment] 2019-11-26 17:49
@thedart76 Yeah the AR button would be like the VR in Option 2. Your other designs are much much prettier. Letters are boring but more clear perhaps. Not sure if we need another poll. The decision is between turning both icons into letters or change the AR one to either letters or the shaded cube that is winning the poll.

@brendanciccone Yeah, I hear you. It's also hard to interpret functionality from icons. AR / VR acronyms are getting more popular and spread by Apple, Google and other new entrants. We can piggyback on the industry to evangelize over time vs having something custom for us.

**Comment by thedart76** [comment] 2019-11-27 00:40
@dmarcos Thanks for your confirmation. I believe you are right: considering the minor adjustments we have made, another poll wouldn't add that much to help make a decision.
Here are the new updated versions.

**Option 1**: AR + VR letters

![01-aframe-enter-xr-arvr-letters](https://user-images.githubusercontent.com/30973948/69683851-2a677a80-10ae-11ea-9c01-31500bfaa60c.png)

**Option 2**: AR letters + VR goggles

![02-aframe-enter-xr-arvrletters-vrgoggles](https://user-images.githubusercontent.com/30973948/69683858-35220f80-10ae-11ea-90dc-dcd6ecaa276b.png)

**Option 3**: Shaded cube + VR goggles

![03-aframe-enter-xr-shadedcube-vrgoggles](https://user-images.githubusercontent.com/30973948/69683869-3f440e00-10ae-11ea-8423-a2a07c6b2efe.png)

Sharing my thoughts:

**1)** AR + VR letters is the clearest option perhaps, and I appreciate its consistency. However, I am not a big fan of it because it denies all that the VR goggles icon has meant for A-Frame so far. It also reminds me of the "primary + ghost" buttons pattern, typical of the standard 2D web.

**2)** AR letters + VR goggles seems to be a good compromise. For this reason, though, it looks to me like a hybrid with the AR button doomed to stating the obvious once the user learns about its functionality after the first few interactions.

**3)** Shaded cube + VR goggles is probably my favourite option, even though it might require some users who have never heard of XR to find out what those 2 icons are for. On the other hand, I guess they will have to get familiar with the device itself before they can even think about how to enter and enjoy any XR experience.

**Comment by dmarcos** [comment] 2019-11-27 01:25
@thedart76 Thanks again 🙏 Totally agree with your points. I really love your cube icons. At the moment, I only have a slight preference towards letters. it feels more clear, consistent and future looking (future headsets won’t look like cardboard viewers, or I so hope 🙂)

**Comment by thedart76** [comment] 2019-11-27 07:10
@dmarcos It's a pleasure and an honor to help you guys with this, as you already know 🙂

Future form factors is something I hadn't considered, and I agree with you on the AR + VR letters option being device-agnostic. Ironically, on new cutting-edge hardware designs, this might also be the sleekest and most minimal option possible.

Let me know when you feel that all the different assets look ok, and I will share them either in **.ai** (Illustrator vector graphics) or **.svg** file format depending on your preferences.

Should you guys want to make any further changes or adjustments*****, even in the future, you can count on me 👍

***** (for example, using different fonts for the AR and VR letters, which you can preview and select yourself on the Google fonts website. I will then create the corresponding pixel-perfect icons.)

**Comment by dmarcos** [comment] 2019-11-27 16:28
[Twitter poll](https://twitter.com/aframevr/status/1199031334674554880?s=20) results with 241 votes are:

- Option 1 - Cube 18%
- Option 2 - Shaded Cube 43%
- Option 3 - AR Letters 39%

It seems decision comes down to abstract slick vs. letter icons

**Comment by ngokevin** [comment] 2019-11-27 18:10
We just got an issue report from maybe one of the most used WebVR sites by users, requesting text because they didn't know what the VR goggles icon while they were wearing an Oculus Quest. https://github.com/supermedium/moonrider/issues/85

**Comment by brendanciccone** [comment] 2019-11-27 18:12
@ngokevin well, considering that now, I'm all for text.

It also visually seems to be most clear on any background as well, from the mockups.

**Comment by thedart76** [comment] 2019-11-27 18:19
@ngokevin Empirical data from user testing is the best feedback we could receive 👌

**Comment by dmarcos** [comment] 2019-11-27 18:54
@thedart76 @brendanciccone Thanks for all the work and feedback. I think we can go ahead and open a PR replacing [current button](https://github.com/aframevr/aframe/blob/master/src/style/aframe.css#L156)

**Comment by LavP** [comment] 2019-11-28 00:44
I am very interest in this discussion.

I asked to my friends what they think about the AR icon I suggested to them.
Then my friend says, “I don't understand why AR is a cube.”

We know the object displayed in 3DCG software is a cube because we are creators.
For this reason we don’t see the AR like a cube. 

Probably, the best icon we can create is using letters. 

Who voted for A-frame's official Twitter because they are all developer. So, that's not useful.

**Comment by dmarcos** [comment] 2019-11-28 00:48
@LavP thanks for contributing. It seems we’re in agreement 🙂 We settled on the letters version. In the poll the shaded cube and the letters were almost even with 40%

**Comment by thedart76** [comment] 2019-11-28 10:15
@dmarcos @ngokevin Here are the 2 **.svg** files for the selected AR + VR letters option:
[enter-ar-mode.svg](https://drive.google.com/open?id=1dpn90MZJmEwuIc22YY-Fd4I2VXjOb_rs)
[enter-vr-mode.svg](https://drive.google.com/open?id=1P3Ff6b1QE0fh5usXoJFvz3KfbPhXJ_U5)
Thank you to everyone who gave their contribute, it's been great working together on this! 🙂

**Comment by thedart76** [comment] 2019-11-28 10:17
**PS**: if they don't render as we expect, feel free to ping me over Slack or DM me on Twitter.

**Comment by dmarcos** [comment] 2019-11-30 04:07
@thedart76 Thanks! Applied the new icon treatment to the CSS and this is what I got. What do you think? Something looks weird to me but maybe it's my eyes that are so used to the old icon. 

![new icons](https://decwap8ztgrry.cloudfront.net/items/2H2k2D2g2F2C1y3a3G2z/Image%202019-11-29%20at%2011.05.37%20PM.png?X-CloudApp-Visitor-Id=222920)

**Comment by brendanciccone** [comment] 2019-11-30 04:10
It’s probably because the border and bolding seems to make them visually off-balance. 

The border on the AR icon should probably mimic the VR icon and be around the border, rather than be a border inside the icon. Also, it looks like the AR letters are not as bold as the VR letters.

**Comment by dmarcos** [comment] 2019-11-30 04:34
I realized the icons have a small border in photoshop. Probably better to eliminate and can add padding border with CSS

![border](https://cl.ly/7b07da7d7767/Image%202019-11-29%20at%2011.33.38%20PM.png)

**Comment by dmarcos** [comment] 2019-11-30 04:42
@brendanciccone Thanks! Take 2️⃣ 

![new icons](https://cl.ly/51c3f4e2c570/Image%202019-11-29%20at%2011.41.16%20PM.png)

**Comment by thedart76** [comment] 2019-11-30 11:26
@dmarcos That border is not supposed to be there, and using padding should be the only way for you to set any extra space around the icons indeed.

If you drop the .SVGs in a browser window and change the page background color using the Developers Tools, you will see that the border is not there; you're right, though, as a border actually shows up in Photoshop and also once the icons are implemented.

I suspect this was caused by the Asset Export panel in Illustrator. I'll look into this and share the new .SVG without border soon.

About the icons themselves: are you keeping them that big?

@brendanciccone The VR letters are deliberately bolder than the AR letters. Once you scale the 2 icons down, the white background (being much brighter than the transparent background) will make them less readable as you can see in the above mockups.

Of course, the AR letters' weight is something we might have to adjust as we see how the 2 icons render at their final and actual size.

**Comment by thedart76** [comment] 2019-11-30 12:48
@dmarcos Sorted, the border is gone 🙂 I had to use "Export As..." and untick the "responsive" option in Illustrator instead of exporting the assets from the Asset Export panel.

I also tweaked both the tracking and the weight of the AR letters.

You can download the 2 new icons from here:
[Enter AR Mode (no border)](https://drive.google.com/open?id=1p0V49ljwmSYsCriESVNkaaOi-eNH8SYE)
[Enter VR Mode (no border)](https://drive.google.com/open?id=1ErAn8RXXICwCbaUTPwbzztnVcS8B0A21)

Matching the size and the padding of the current VR mode button (VR goggles), here is how the 2 icons should render on Desktop and Mobile:

![aframe-scene-xrbuttons-current-padding](https://user-images.githubusercontent.com/30973948/69900747-3766c100-136f-11ea-94c3-81db9e515ada.png)

**Button**: 80x56px
**Padding**: 12px
(so icon would be: 56x32px)

![aframe-scene-xricons-curren-padding-mobile](https://user-images.githubusercontent.com/30973948/69900757-506f7200-136f-11ea-826f-4e46a9f46c55.png)

**Button**: 48x32px
**Padding**: 6px
(so icon would be: 36x20px)

LMK if you are going to use different size/padding for the new buttons.
If so, more than happy to do any further adjustments accordingly to ensure readability 👍

**Comment by thedart76** [comment] 2019-11-30 16:38
@dmarcos In my last message I forgot to mention that I have made some minor adjustments to the VR letters as well, so you want to download and use both the 2 new assets.

**Comment by dmarcos** [comment] 2019-12-01 00:34
Thanks! Two options. Which one do you prefer?

Big Buttons:

![big buttons](https://decwap8ztgrry.cloudfront.net/items/2L1V3g1I1H1h182h1u2B/Image%202019-11-30%20at%207.27.58%20PM.png?X-CloudApp-Visitor-Id=222920)

Centered icons:

![centered icons](https://cl.ly/9d2e630e2ef4/Image%202019-11-30%20at%207.33.47%20PM.png)

**Comment by brendanciccone** [comment] 2019-12-01 00:36
Big buttons feel more like buttons IMO.

**Comment by thedart76** [comment] 2019-12-01 00:45
Options 2 made sense with the VR goggles.
With the new icons displaying the letters, I believe Option 1 is more appropriate.
Are you going to leave the buttons that size? They seem a bit too big IMO.
What are your thoughts?

**Comment by thedart76** [comment] 2019-12-01 00:49
**PS**: if they currently are 80px width, can you try and bring them down to 64px?

**Comment by thedart76** [comment] 2019-12-01 00:57
Actually, I just realised that we are testing them on a very basic and almost empty scene. On more crowded backgrounds with many objects and different colors it might be not so easy and immediate to spot them... I guess the only way to find that out is to give it a try.

**Comment by dmarcos** [comment] 2019-12-01 00:59
I usually prefer larger icons but can make them smaller. I can put a version online so you can try on device.

**Comment by thedart76** [comment] 2019-12-01 01:04
No need to, Diego, also because you have more XR devices than I do, so you will have the chance to see and judge better than me 🙂

**Comment by thedart76** [comment] 2019-12-01 01:13
@dmarcos I transferred your image to my iPad and had a look at it: you are right, that's perfect.

**Comment by dmarcos** [comment] 2019-12-01 01:36
You can try on device here: https://lyrical-khaan.glitch.me/

**Comment by thedart76** [comment] 2019-12-01 07:39
Their size is different from the 1:1 scale in your mockup, so now I can see how they actually render.
I like them a lot! Here is how I see them at actual scale:

**MacBook Pro** (1680x1050px)

![MacBook-Pro-1680x1050px](https://user-images.githubusercontent.com/30973948/69911044-4f8d1d80-140d-11ea-92f1-346e6206a3f9.png)

**iPad Pro** (2048x1536px - scaled down to 1024x768px for Desktop resolution):

![iPad-2048x1536px](https://user-images.githubusercontent.com/30973948/69911046-561b9500-140d-11ea-901d-5a36ba3d9361.png)

What do you guys think about them?

**Comment by thedart76** [comment] 2019-12-01 07:59
If we want to do some final pixel-pushing, I would try to bring the tracking down just a bit and place the letters closer to each other. I'm curious to see if they look even better that way.
With exact rendering references now I can create accurate mockups.
I will share for all of us to see later on today.

**Comment by thedart76** [comment] 2019-12-01 12:30
So, I exported the SVGs, uploaded them to Glitch, and then updated the url(s) of the buttons' icons in the Inspector (Developer Tools). Therefore what you see is not a mockup, but the icons being rendered in the browser using the CSS values that you set on the 2 buttons.

The below image is a section of a screenshot I took with my MacBook, so the icons are at 100% scale. (BTW, thanks for uploading that scene to Glitch!)

Which version do you prefer?
**Up** (currently online) or **Down** (reduced tracking)

![current-and-reduced-tracking](https://user-images.githubusercontent.com/30973948/69913914-ce964c00-1435-11ea-9073-425e50aeab72.png)

**Comment by dmarcos** [comment] 2019-12-01 15:08
Yeah 2nd looks better. Thank you. Super appreciated

**Comment by thedart76** [comment] 2019-12-01 15:20
I agree with you. A pleasure giving a hand. New downloadable assets here:
[AR Mode (reduced tracking)](https://drive.google.com/open?id=1mrqrtdEzD0K6JTu87AWnm-utBzbJ0M7l)
[VR Mode (reduced tracking)](https://drive.google.com/open?id=1MbwxYHqMfBbTPT_tO9jkIR9-gkRGZE-E)

**Comment by dmarcos** [comment] 2019-12-01 15:50
Great! Thanks. I’m looking at the icons after a night of sleep. I really like them but thought that the distinction between AR and VR might not be 100% clear. In the screenshot above with white background the AR button looks solid and the transparent background idea gets lost. I admit that this might be a moot point in the average scene and I’m possibly overthinking this 😋

**Comment by thedart76** [comment] 2019-12-01 16:26
Yeah, this is true for plain and desaturated backgrounds, so the whole range from white to black.
When overlapping plain and colored backgrounds, instead, the transparency of the AR button would be noticeable. Fortunately, we can rely on the AR and VR letters being extremely explicit.

The point is that _"from the moment you know enough to talk about a product, you know too much to tell if that product would be usable for someone who doesn't know it."_
(from a user testing book I read years ago)

So, the only way for us to find that out is to put the icons to test 🙂
This way, the users would also tell us why the distinction between the 2 might not be clear.

**Comment by dmarcos** [comment] 2019-12-01 18:12
Screenshot with latest icons iterations and a busier scene.

![new icons](https://cl.ly/511a99dde103/Image%202019-12-01%20at%201.07.45%20PM.png)

**Comment by thedart76** [comment] 2019-12-01 18:56
The letter-spacing in the 2 buttons looks better indeed. I like them more than I expected.

About the transparency: that's true, the AR mode button's background seems a dark solid grey in this case. Unfortunately, in some circumstances that "lack of transparency" effect will be unavoidable. For example, the same is happening in this scene to the rightmost UI element (the rectangle reading 20MS), even though its background has 0% opacity.

What are your thoughts?

**Comment by thedart76** [comment] 2019-12-01 19:06
**PS**: We could lower the background transparency just a bit... Not too much or, as you can imagine, it would compromise readability when the AR letters overlap white or light backgrounds.

**Closed** 2019-12-03 00:20 UTC
Labels: help wanted (easy)

**Comment by AkiroXR** [comment] 2020-04-30 05:51
Excuse me, I'm looking for the project with the car at the top of this page. Could someone please send me a link?

**Comment by klausw** [comment] 2020-04-30 07:05
https://klausw.github.io/a-frame-car-sample/index.html

**Comment by AkiroXR** [comment] 2020-05-01 16:56
Thank you ! ^^

**Comment by djamel2288** [comment] 2021-01-18 10:29
please, can I change VR button position?

**Comment by dmarcos** [comment] 2021-01-20 06:41
@djamel2288 You can specify your own enter VR / AR buttons: https://aframe.io/docs/1.1.0/components/vr-mode-ui.html#specifying-a-custom-enter-vr-button

**Comment by djamel2288** [comment] 2021-01-20 10:51
Thank you :D
