### ISSUE TITLE
firefox: uncaught TypeError: this.attributes.position is undefined / chrome: Uncaught TypeError: Cannot read property 'array' of undefined

### ISSUE THREAD

**Issue by quantumalchemy** [aframevr/aframe#4742] opened 2020-12-07 17:18 UTC
**Description:**

- A-Frame Version: 1.1.0  &  master 
- Platform / Device:  all firefox 81.0 (64-bit) and  Chromium  81.0.4044.92 (Developer Build) built on Debian 10.4, running on Debian 10.6 (64-bit)  linux
- Reproducible Code Snippet or URL:
https://artboxvr.com/brooklyn/

** Works NO ERRORs on A-Frame Version: 1.0.4

firefox:
Uncaught TypeError: this.attributes.position is undefined
    Aframe 13
        computeBoundingSphere
        raycast
        ki
        intersectObjects
        checkIntersections
        tock
        value
        onAfterRender
        render
        value
        exports
        u
        t
index.js:96:18
    Aframe 13
        computeBoundingSphere
        raycast
        ki
        intersectObjects
        checkIntersections
        tock
        value
        onAfterRender
        render
        value
        exports
        u
        t

chrome:
Uncaught TypeError: Cannot read property 'array' of undefined
    at TextGeometry.computeBoundingSphere (index.js:96)
    at P.raycast (three.js:8649)
    at ki (three.js:34685)
    at Ui.intersectObjects (three.js:34733)
    at i.checkIntersections (raycaster.js:227)
    at i.tock (raycaster.js:199)
    at HTMLElement.tock (a-scene.js:764)
    at e.object3D.onAfterRender (a-scene.js:53)
    at We.render (three.js:18659)
    at HTMLElement.render (a-scene.js:798)
   
   RE:  /issues/4618
I made all the suggested fixes but same error..
Thanks!

**Comment by quantumalchemy** [comment] 2020-12-07 22:17
Isolated  to the text attribute .. in v 1.0.4
Worked ok
Any info on this ?

**Comment by dmarcos** [comment] 2020-12-07 23:35
Hard to tell. The link provided is a pretty complex application. If you can provide a simple example to reproduce it will be easier to help. I recommend [glitch](https://glitch.com/~aframe)

**Comment by quantumalchemy** [comment] 2020-12-08 02:37
> Hard to tell. The link provided is a pretty complex application and hard to isolate the issue. If you can provide a simple example to reproduce it will be easier to help. I recommend [glitch](https://glitch.com/~aframe)

Yeah used the aframe basic bootstrap cant replicate the error weird. 
Just not working I'm my app.. 
Guess i can't use text 
Or keep using v 1.0.4 for now : <

**Comment by dmarcos** [comment] 2020-12-08 02:40
From the error message. It looks the problem comes from the raycaster and or cursor / laser controls. You'll need a simple test case that uses those to reproduce.

**Comment by quantumalchemy** [comment] 2020-12-08 03:55
Thanks will set that up.

**Comment by quantumalchemy** [comment] 2020-12-08 17:33
base aframe with reproduced error: Uncaught TypeError: this.attributes.position is undefined
https://jsfiddle.net/scriptgurus/kpaf1bhq/41/

(glitch.com console / debugger never loads / works for me )

**Comment by dmarcos** [comment] 2020-12-08 18:34
What are the steps to reproduce? What OS? What browser version?

I can't reproduce neither on Chrome 87 nor Firefox 83 on Windows X.

I tried to reload the page multiple times and click around and never got the error to appear.

**Comment by quantumalchemy** [comment] 2020-12-08 19:34
getting it on .. Chromium 81.0.4044.92 (Developer Build) built on Debian 10.4, running on Debian 10.6 (64-bit) linux

Firefox 81 linux only sometimes
very strange .. ill load up windows ..

**Comment by quantumalchemy** [comment] 2020-12-08 21:39
well by  remove all except login / psw stuff  / re-install firefox and chrome on my devel  machine  (linux Debian) 
The prev. error ->
(Cannot read property 'array' of undefined
at TextGeometry.computeBoundingSphere (index.js:96)..) is now gone!  
in my code I am updating a <a-text> ) value 
ex. .setAttribute('text', {value: info});
 so I knew this it was in the realm of the updated three js lib. with all the tracing error to three
in 1.1.0    very strange  - Thanks for your help!

**Comment by dmarcos** [comment] 2020-12-09 01:07
Well done! Not sure what could be causing `THREE.DirectGeometry: Faceless geometries are not supported` If you can reproduce on Windows I can look into it. Good luck.

**Comment by dmarcos** [comment] 2020-12-17 22:18
Is this still an issue? Can we close?

**Comment by KaiRo-at** [comment] 2020-12-28 01:24
It looks like I'm running into exactly this issue.

I have (basically) this snippet in my code (I set some attributes on `menu` as well, and some others on `menuitem`s added in a loop):
```
let menu = document.querySelector("#menu");
let normalTextColor = "#CCCCCC";
let optText = "Test";
var menuitem = document.createElement("a-box");
menuitem.setAttribute("text", {value: optText, color: normalTextColor, xOffset: 0.03});
menu.appendChild(menuitem);
```
where the HTML has this element in the `a-scene`:
```
<a-plane id="menu" color="#404040" position="0 2 -1" visible="false"></a-entity>
```
and I run into this error when the `menuitem.setAttribute("text", ...` line is in there but everything runs fine when it's not present.

The full code is at https://github.com/KaiRo-at/vrmap with the running example at https://vrmap.kairo.at/ which is broken with this issue right now (at least for me in Firefox Nightly).

**Comment by dmarcos** [comment] 2020-12-28 03:11
FWIW, your HTML should be `<a-plane id="menu" color="#404040" position="0 2 -1" visible="false"></a-entity>` Notice the non-matching closing tag.

**Comment by KaiRo-at** [comment] 2020-12-28 13:11
> FWIW, your HTML should be `<a-plane id="menu" color="#404040" position="0 2 -1" visible="false"></a-plane>` Notice the non-matching closing tag.

Thanks, that's a good point (interesting that it never caused an issue), but fixing that unfortunately doesn't change experiencing this bug.

**Comment by dmarcos** [comment] 2020-12-28 14:56
@KaiRo-at Happy to look at it if you can reproduce with a simpler example. A bit tight on time to debug the whole app. Best of luck

**Comment by KaiRo-at** [comment] 2020-12-29 00:25
I found a simple test case. The issue only is seen in connection with the raycaster I have so that it's seen which menu item is being clicked in that menu. Drop this into a `.html` file to reproduce:
```
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Issue 4742 Testcase</title>
    <meta name="description" content="VR Map">
    <script src="https://aframe.io/aframe/dist/aframe-master.min.js"></script>
    <script>
      window.onload = function() {
        // Load location presets and subdialog.
        let menu = document.querySelector("#menu");
        let mItemHeight = 0.1;
        let normalBgColor = "#404040";
        let normalTextColor = "#CCCCCC";
        let menuHeight = mItemHeight;
        menu.setAttribute("height", menuHeight);
        menu.setAttribute("position", {x: 0, y: 1.6 - menuHeight, z: -1});
        let optText = "Menu Test";
        // menu entity
        var menuitem = document.createElement("a-box");
        menuitem.setAttribute("class", "clickable");
        menuitem.setAttribute("height", mItemHeight);
        menuitem.setAttribute("depth", 0.001);
        menuitem.setAttribute("text", {value: optText, color: normalTextColor, xOffset: 0.03});
        menuitem.setAttribute("color", normalBgColor);
        menu.appendChild(menuitem);
      }
    </script>
  </head>
  <body>
    <a-scene background="color: #CFEBFD">
      <a-entity id="cameraRig" position="0 0 0">
        <!-- camera -->
        <a-entity id="head" camera="active: true" position="0 1.6 0"><a-entity cursor="rayOrigin: mouse;" raycaster="far: 2; objects: .clickable;"></a-entity></a-entity>
        <!-- menu -->
        <a-plane id="menu" color="#404040" position="0 2 -1"></a-plane>
      </a-entity>
    </a-scene>
  </body>
</html>
```
When either the `.setAttribute("text", ...)` line, or the `.setAttribute("class", "clickable");` or the `raycaster` in the HTML are removed/commented out, the issue goes away (but of course, functionality is lost in the full VR Map demo).

**Comment by kikoano** [comment] 2020-12-29 06:08
I have the same problem. When I use my Web2VR libary with aframe 1.1.0.  I use community aframe-keyboard component entity 
 when i add it to the scene i get the error on chrome. If i dont add it to the scene it wont crush. On firefox it only works sometimes after refreshing.

**Closed** 2020-12-30 01:26 UTC

**Comment by dmarcos** [comment] 2020-12-30 01:28
Thanks for reporting and the test case. The problem was that the font is loaded asynchronously and there might be cases where the raycaster tries to intersect on the text before it's completely initialized. It should be now fixed. If you can try the [master-build](https://cdn.jsdelivr.net/gh/aframevr/aframe@1a5f2348ffe8647e65e0c14788f5ae2bf27ed0cc/dist/aframe-master.min.js) and confirm the fix it will be greatly appreciated.

**Comment by KaiRo-at** [comment] 2020-12-30 11:45
> If you can try the [master-build](https://cdn.jsdelivr.net/gh/aframevr/aframe@1a5f2348ffe8647e65e0c14788f5ae2bf27ed0cc/dist/aframe-master.min.js) and confirm the fix it will be greatly appreciated.

A local copy of my full VR Map demo works with this build, thanks for the fix! :+1:

**Comment by ELI7VH** [comment] 2021-01-11 00:49
Hi. I just ran into this issue. the `master-build` link provided above fixed the problem for me. Any idea on an eta for this to be in a release?

**Comment by dmarcos** [comment] 2021-01-11 17:58
@ELI7VH No ETA at the moment. The master build I linked above is safe to use.

**Comment by marcelpi** [comment] 2021-01-21 16:02
It worked for me too. Thanks for posting it.
