### ISSUE TITLE
documentation: Warn against arrow functions in components.

### ISSUE THREAD

**Issue by ccrraaiigg** [aframevr/aframe#4857] opened 2021-05-12 20:11 UTC
If one uses an arrow function for the init() method of a component, then "this" will be bound to the window, not the component. This would be a good thing to mention in the documentation. Thanks!

**Comment by dmarcos** [comment] 2021-05-13 05:08
Is not that Javascript general knowledge?

**Comment by dmarcos** [comment] 2021-05-13 05:10
it’s the same for any component function

**Comment by dmarcos** [comment] 2021-05-14 20:01
I believe this problem is not specific to A-Frame and it's beyond the scope of the docs. Javascript developers should know the scoping differences between regular and arrow functions. The issue is not limited to the `init` method. We would have to add a note to any function / method where A-Frame expects a regular function. I'm closing this for now but can reopen if necessary. Thanks for filing.

**Closed by dmarcos** 2021-05-14 20:01 UTC
