### ISSUE TITLE
360 image black in webview

### ISSUE THREAD

**Issue by appsdevpk** [aframevr/aframe#3349] opened 2018-01-23 07:41 UTC
i am trying to build a 360 image viewer using phonegap and aframe. I tried a lot of code samples other than displaying 360 image and everything works fine but when i try to display 360 image there is nothing but a black screen

- A-Frame Version: 0.7.0
- Platform / Device: Amazon Fire Phone
I am using the following code.

```
<a-scene id="vrscene">
	<a-sky src="http://appsdevpk.com/360/naran.jpg" rotation="0 -130 0"></a-sky>
</a-scene>
```

**Comment by dmarcos** [comment] 2018-01-23 07:46
Does it work on a regular browser on the Amazon Fire?

**Comment by appsdevpk** [comment] 2018-01-23 07:46
Yes it does

**Comment by dmarcos** [comment] 2018-01-23 07:48
You will have to figure out how to access to the browser console for phonegap and see if there are any errors. I don't know much about Phonegap and I don't have access to an Amazon Fire phone.

**Comment by appsdevpk** [comment] 2018-01-23 07:48
i tried to debug it but there is no error in console

**Comment by dmarcos** [comment] 2018-03-11 00:21
I'm closing this since I'm unable to reproduce. We will reopen if there's additional information

**Closed by dmarcos** 2018-03-11 00:21 UTC
