### ISSUE TITLE
vive-controls not working on 0.8.0

### ISSUE THREAD

**Issue by etiennepinchon** [aframevr/aframe#3494] opened 2018-03-24 08:48 UTC
On 0.8.0 the `vive-controls` component no longer works. The controllers are not present on the scene. Code (tested on Nightly 60 with HTC vive):

```html
<a-entity vive-controls="hand: left"></a-entity>
<a-entity vive-controls="hand: right"></a-entity>
```

Thanks!

**Comment by christophermorse** [comment] 2018-03-26 10:25
I am also experiencing this same error—controllers are active (events fire) but models are not visible on screen.

**Comment by dmarcos** [comment] 2018-03-28 07:51
This is a duplicate of https://github.com/aframevr/aframe/issues/3441

**Closed by dmarcos** 2018-03-28 07:51 UTC

**Comment by christophermorse** [comment] 2018-03-28 09:39
The suggested changes to Three.js in #3441 do not fix the error. I found instead that by saving the object models locally and manually attaching them to the controllers is the only way to get them to appear.

**Comment by donmccurdy** [comment] 2018-03-28 14:12
When models do not appear, do you see network requests for them? Or any errors in the console?

**Comment by omolds** [comment] 2018-08-26 14:34
try super-hands!
