### ISSUE TITLE
GLTF-Model textures not correct rendered

### ISSUE THREAD

**Issue by Dirk-27** [aframevr/aframe#4819] opened 2021-03-11 13:02 UTC
**Description:**

- A-Frame Version: 1.1.0 up to 1.2.0
- Platform / Device: Browser, Windows 10 Enterprise, Firefox, Chrome
- Reproducible Code Snippet or URL: https://codepen.io/Dirk-27/pen/PobXEOw

The model doesn't have textures on some faces. Here it is shown in aframe version 1.0.4 (left) and 1.1.0 (right). In 1.2.0 this is the same.

![grafik](https://user-images.githubusercontent.com/45331389/110789641-648f6800-8270-11eb-9837-db6cf7d8ae1a.png)

Codepen:
* left - aframe 1.0.4: https://codepen.io/Dirk-27/pen/GRNPyQR
* right - aframe 1.1.0: https://codepen.io/Dirk-27/pen/PobXEOw

**Comment by dmarcos** [comment] 2021-03-11 18:27
@Dirk-27 Have you tried loading your model in the [gltf viewer](https://gltf-viewer.donmccurdy.com/)

We have not made any changes on how we handle the glTF models that I'm aware of

@donmccurdy Does the difference ring a bell? Possibly related to any changes made to the THREE glTF parser or format. Thank you!

**Comment by donmccurdy** [comment] 2021-03-11 19:03
It looks like the winding order (or `material.side`?) on the second model has been inverted... but i can't think of anything related that should have changed between these three.js versions.. 😕

**Comment by dmarcos** [comment] 2021-03-11 19:09
I think the problem is not only the missing texture. The z order of the model elements is not looking correct in the version with A-Frame 1.1.0+ plus. Maybe some change related on how transparency is handled?

**Comment by donmccurdy** [comment] 2021-03-11 23:18
Ah that's pretty much it, yes. I'd forgotten about https://github.com/mrdoob/three.js/pull/18235, it's been a long year. 🙂

Although most of this model _appears_ opaque, it is marked with `.transparent=true` (or `alphaMode=BLEND` in glTF terminology). The change in r114 was to disable depthWrite on transparent materials, which is generally a better choice.  I suspect this model could be edited by an artist to use alpha blending only where it really is transparent — this would reduce overdraw, too — but the easy workaround would be to edit the property after loading, like:

```js
object.traverse((o) => {
  if (o.isMesh && o.material.transparent) o.depthWrite = true;
});
```

**Comment by dmarcos** [comment] 2021-03-12 05:54
@donmccurdy Thanks for saving the day one more time.

@Dirk-27 You can do what Don said. You can either edit the model to use alpha blending only where it's really transparent or fix it in JS with the workaround mentioned above. I added it for you in this [glitch](https://glitch.com/edit/#!/outgoing-slow-arrow?path=set-depth-write.js%3A12%3A0)

**Comment by dmarcos** [comment] 2021-03-12 05:55
Closing because there's nothing actionable on the A-Frame side. Thanks for filing.

**Closed by dmarcos** 2021-03-12 05:55 UTC
