### ISSUE TITLE
Cursor component raycaster: Cannot read property 'distance' of null

### ISSUE THREAD

**Issue by Perhelion** [aframevr/aframe#3877] opened 2018-11-23 08:40 UTC
**Description:** 
If the cursor is a raycaster I get often this error on line 281 (in which seems  `intersection = evt.detail.intersections[index];` null)
- A-Frame Version: 0.8.2

`<a-cursor id="cursor"
	fuse="false"
	material="color: white; opacity:0.2; shader: flat"
	position="0 0 -0.8"
	raycaster="far: 8; interval: 400; objects: .collidable; recursive: false; near: 0.1"
	geometry="primitive: ring; radiusInner: 0.015; radiusOuter: 0.02; segmentsTheta: 4">`

It seems depending on how much objects could be target for the raycaster? 
https://github.com/aframevr/aframe/commit/8d79343eea8fe160d5bb26d0d3beeab26e3ba324

**Comment by dmarcos** [comment] 2018-11-24 03:31
Line 281 of what? Do you have a link to an example to reproduce?

**Comment by Perhelion** [comment] 2018-11-25 13:51
@dmarcos  Oh sorry, I've not, it seems this happens for sure if you have defined more than one raycaster!? I removed " `cursor="rayOrigin: mouse"` on a-scene (which was an example in a docu) and the error seems gone. It also appears if target and source object are raycaster. 

It is in  /cursor.js https://github.com/aframevr/aframe/commit/8d79343eea8fe160d5bb26d0d3beeab26e3ba324

**Comment by dmarcos** [comment] 2018-11-26 03:12
Have you tried with master? 
https://cdn.jsdelivr.net/gh/aframevr/aframe@efcc8a0a919811fe5bd4ab6fd60bfbb8e85a98a1/dist/aframe-master.min.js

**Comment by dmarcos** [comment] 2019-01-30 23:47
I don't know how to reproduce this. Closing due to lack of information.

**Closed by dmarcos** 2019-01-30 23:47 UTC
