### ISSUE TITLE
Using html2canvas can not add entity to camera behind

### ISSUE THREAD

**Issue by MallTo-Silence** [aframevr/aframe#3576] opened 2018-05-09 10:36 UTC
**Description:**
I customize a component and use html to render the canvas for three. I can't add components to the back of the camera once I use the html2canvas library. The effect of viewing through interactions is like this.
**normal**
![1721525861294_ pic_hd](https://user-images.githubusercontent.com/16772834/39810407-79fac3aa-53b7-11e8-8779-9cfdad807559.jpg)

**mine**
![1711525861293_ pic_hd](https://user-images.githubusercontent.com/16772834/39810442-998a2562-53b7-11e8-9601-376cc3ec4496.jpg)

**my components**
![image](https://user-images.githubusercontent.com/16772834/39810507-cb53ddb8-53b7-11e8-8bba-c2f0d833a4c5.png)

- A-Frame Version: 0.8.2
- Platform: Chrome

**Comment by MallTo-Silence** [comment] 2018-05-10 08:59
Calling html2canvas in the init method of AFRAME.registerComponent will cause this component to be created loop. this may be a bug.

**Comment by dmarcos** [comment] 2018-06-01 16:30
It's hard to unpack what you're seeing vs. what you're expecting with the given info. If you can share a simple runnable example that reproduces the problem it will be very helpful.

**Comment by dmarcos** [comment] 2018-06-30 03:16
I'm closing this due to the lack info. I will reopen if there are additional details

**Closed by dmarcos** 2018-06-30 03:16 UTC
