### ISSUE TITLE
WebXR mode broken on Vision Pro with A-Frame 1.6.0

### ISSUE THREAD

**Issue by JL-Vidinoti** [aframevr/aframe#5530] opened 2024-05-29 09:48 UTC
**Description:**

In WebXR mode (VR) using the Vision Pro, the gltf-model do not appear correctly. The ordering of the elements is wrong.
It was working fine with version 1.5.0 but the bug appears with the latest 1.6.0 version.

- A-Frame Version: 1.6.0
- Platform / Device: Apple Vision Pro
- Reproducible Code Snippet or URL: https://silver-fog-earl.glitch.me/ (https://glitch.com/edit/#!/silver-fog-earl?path=index.html%3A29%3A37)

In browser mode, it works properly.
![IMG_0030](https://github.com/aframevr/aframe/assets/35372626/712580db-1dca-484e-b246-c2d3662a2885)

The issue appears in VR mode 
![IMG_0031](https://github.com/aframevr/aframe/assets/35372626/ff2adb1d-66ab-4324-913e-80107c459231)

**Comment by mrxz** [comment] 2024-05-29 10:23
Sadly not in possession of an AVP to test. @dmarcos can you reproduce the issue?

The strange thing is that even when meshes are sorted incorrectly, the depth buffer should still prevent outcomes like this. For completion sake:
 - Are there any errors/warnings logged in the console?
 - Does the issue also happen without the gltf-model or only with the gltf-model?

Can't immediately think of a change in A-Frame that could cause this. I suspect that it's due to a change in Three.js. If you could `git bisect` between the v1.5.0 and v1.6.0 tags that would be awesome.

A stab in the dark, but could you try adding `renderer="stencil: true"` to `<a-scene>` and see if that changes anything?

**Comment by JL-Vidinoti** [comment] 2024-05-29 12:05
I have one error appearing in the console but I don't know if it's related.

![Screenshot 2024-05-29 at 13 56 46](https://github.com/aframevr/aframe/assets/35372626/31b12987-6576-4466-ab5d-e72199ead07a)

I only observed the issue with the gltf-model but I did only few tests.
However, while trying the code snippet shared earlier, I observed that the objects were disappearing when I was looking up. See recording below.

https://github.com/aframevr/aframe/assets/35372626/d0546a4b-2f5b-4134-a91d-393536eb26a2

I tried `renderer="stencil: true"` but the same problem occurs.

**Comment by dmarcos** [comment] 2024-05-29 15:48
Can you try a different simpler gltf model? Could be the shaders / materials of that model

**Comment by arpu** [comment] 2024-06-01 11:43
only idea is the soring change from https://github.com/aframevr/aframe/pull/5341

**Comment by mrxz** [comment] 2024-06-03 09:10
From the video it's clear that something is up with the depth buffer. It's as if it isn't being used, but the helmet seems fine, so perhaps it's somehow cleared/invalidated after each draw. The sorting is behaving as you'd expect, the closest objects are drawn first. Looking up most likely causes the sky to end up being drawn last, which makes the rest disappear.

Someone with an AVP really just needs to do a git bisect and we'll know the exact change causing this.

**Comment by JL-Vidinoti** [comment] 2024-06-05 13:04
I found the commit causing the issue: https://github.com/aframevr/aframe/commit/a6ec41728d643b54520ff7518bcd298bc70c1e4c

I also did some more tests and it is not related to the gltf-model.
The standard scene looks like that with the Vision Pro:
![visionpro](https://github.com/aframevr/aframe/assets/35372626/b83cbba1-ded3-4f11-8040-9aa2258750bd)
But it should look like that:
![desktop](https://github.com/aframevr/aframe/assets/35372626/98ad53a9-890d-4f14-a4c4-89861d9eb150)

**Comment by mrxz** [comment] 2024-06-05 13:14
@JL-Vidinoti Thanks for digging into this. That commit most likely causes the AVP to be considered mobile by A-Frame. The puzzling part is still how this in turn causes these weird rendering issues (as even on mobile devices things should just work).

One thing that differs is that antialiasing is disabled by default for mobile devices. 
Could you try if the problem persists when you explicitly enable antialiasing: `<a-scene renderer="antialias: true">`?

**Comment by JL-Vidinoti** [comment] 2024-06-07 09:09
Good catch! It works by enabling antialiasing.

**Comment by dmarcos** [comment] 2024-06-07 22:30
Thanks for investigating. Much appreciated. This means that `isTablet` `isIpad` return true on AVP after https://github.com/aframevr/aframe/commit/a6ec41728d643b54520ff7518bcd298bc70c1e4c ?

We gotta correct that then so antialising is enabled again by default on AVP

Gott understand why lack of antialising affects the rendering order but probably need to be handled in a separate issue.

**Comment by vincentfretin** [comment] 2024-06-08 11:12
If that helps, there is this link that was shared on [discord](https://discord.com/channels/758943204715659264/805647111625375764/1247607067968012348) a few days ago to detect if you're on Vision Pro:
https://github.com/danrossi/ios-detection-utils/tree/main

**Comment by Utopiah** [comment] 2024-06-14 15:01
Also had problems with models on Vision Pro that I didn't encounter before, wondering if it's related to Vision OS 1.2 rather than an AFrame update.

**Comment by dmarcos** [comment] 2024-09-17 23:35
Vision OS 2 has been released. Is this still a problem?

**Comment by Utopiah** [comment] 2024-09-24 09:54
Tried on Vision OS 2 today and everything worked as expected, including the initial Glitch shared to open the issue.

IMHO it can be closed unless there is something else specific.

**Comment by dmarcos** [comment] 2024-09-24 20:46
Thanks for testing @Utopiah Closing and can reopen if necessary

**Closed by dmarcos** 2024-09-24 20:46 UTC
