### ISSUE TITLE
a-curved-image interactivity doesn't map coordinates correctly

### ISSUE THREAD

**Issue by mosesoak** [aframevr/aframe#3693] opened 2018-07-11 20:35 UTC
**Description:**

- A-Frame Version: master
- Platform / Device: oculus go
- Reproducible Code Snippet or URL:

```html
      <a-entity laser-controls raycaster="showLine: true; far: 4; objects: .clickable" line="color: white; opacity: 0.5"></a-entity>
      
       <a-entity id="scrubber" class="not-clickable" position="0 0 0"  rotation="0 162 0" visible="true">
          <a-curvedimage change-color-on-hover class="clickable" id="scrubber-main" position="0 0 -4" rotation="0 0 0" scale="1 1 1" geometry="height: 1; openEnded: true; thetaLength: 36; thetaStart: 0; radius: 8;" material="src: #sample-image"></a-curvedimage>
      </a-entity>
```
^ Using a sample image and the `change-color-on-hover` component from the docs.

Originally I filed #3692 when having trouble getting point/click to work, but then tracked it down to using `curved-image`. Basically the pointer coordinates do not correctly map to curved surface.

The math to fix this issue might be difficult as there are a number of variables to consider:

1. Position, rotation, `radius`, `theta-length` and `theta-start` of curved image
2. Position and rotation of parent entities, as shown in the above example
3. Raycaster position offset
    (I haven't been able to change the oculus go controller model position from origin but noticed that it is possible to change the beam origin, so that might come into play here)

By tinkering I was able to set the image into odd positions where the `mouseenter` would partially register in a segment of the image, but not the entire thing.

I was also not able to find an easy solve by simplifying the example as much as possible (removing the wrapper entity, removing rotation and position, etc.).

**Comment by dmarcos** [comment] 2018-07-12 18:31
Curved image should make any difference when it comes to raycaster intersection.  It will help clarify if you provide a simple runnable example and a description of what you see vs what you expect.

**Comment by arpu** [comment] 2018-07-12 21:35
i testing this with aframe master and see some problems not intersection in the a-sphere
https://codepen.io/anon/pen/VBLqgY/?editors=1111

**Comment by mosesoak** [comment] 2018-07-13 06:10
@dmarcos Right, the ray does not intersect with the curved-image correctly. Depending on target position sometimes it will get partial intersection (like the highlight will work on a portion of the curved surface but not all of it). Sorry that I didn't have time to create a full example, but our team switched to Unity after we dropped a bunch of time on this problem. Should be fairly easy to spin up a scene with a curved image, drop the change-color-on-hover script on it, and validate.

**Comment by dmarcos** [comment] 2020-10-24 00:31
Closing due to missing link to reproduce

**Closed by dmarcos** 2020-10-24 00:31 UTC
