### ISSUE TITLE
Error on roadhog build

### ISSUE THREAD

**Issue by Benkevych** [aframevr/aframe#3536] opened 2018-04-11 14:00 UTC
**Description:**

Getting an unexpected token error on roadhog build command

```
sudo yarn build
yarn run v1.5.1
$ roadhog build
Creating an optimized production build...
Failed to compile.

index.js from UglifyJs
SyntaxError: Unexpected token name «of», expected punc «;» [./~/aframe/dist/aframe-master.js:75051,0]

error An unexpected error occurred: "Command failed.
Exit code: 1
Command: sh
Arguments: -c roadhog build
Directory: /Users/a1111/Documents/Projects/diseasenet
Output:
".
info If you think this is a bug, please open a bug report with the information provided in "/Users/a1111/Documents/Projects/diseasenet/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

- A-Frame Version: 0.8.1
- Platform / Device: macOS High Sierra
- Reproducible Code Snippet or URL:

**Comment by donmccurdy** [comment] 2018-04-11 16:16
Duplicate of https://github.com/aframevr/aframe/issues/3449 — this will be fixed on upcoming release.

**Closed by donmccurdy** 2018-04-11 16:16 UTC
