### ISSUE TITLE
Aframe inspector disappears when clicking some elements

### ISSUE THREAD

**Issue by samyH** [aframevr/aframe#5241] opened 2023-02-14 10:14 UTC
- A-Frame Version: 1.4.0
- Platform / Device: Windows 11 Chrome

I get the following error when trying to inspect certain elements in my scene:

`index.js:303 TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'd'
    |     property 'components' -> object with constructor 'Object'
    |     property 'position' -> object with constructor 'n'
    --- property 'el' closes the circle
    at JSON.stringify (<anonymous>)
    at l.value (index.js:303:24)
    at Ts (index.js:303:24)
    at js (index.js:303:24)
    at El (index.js:303:24)
    at vc (index.js:303:24)
    at bc (index.js:303:24)
    at yc (index.js:303:24)
    at ic (index.js:303:24)
    at lc (index.js:303:24)` 
    
    
Once this error happens all UI vanishes leaving just the grid and the gizmo - elements are still selectable however.

This bug makes using the inspector a chore - if anyone knows how to fix or some kind of workaround I'd appreciate it.

**Comment by dmarcos** [comment] 2023-02-14 10:49
Do you have steps to reproduce?

**Comment by samyH** [comment] 2023-02-14 12:10
I've got a lot in my scene - let me try and simplify and post something

**Comment by vincentfretin** [comment] 2023-02-14 13:37
I didn't pay attention, actually there is an explicit check for type selector here to not do stringify
https://github.com/aframevr/aframe-inspector/blob/75b03420ef944c45e937201648c532d1b6a53bd5/src/components/components/PropertyRow.js#L131-L133 so I don't think this is it.

**Comment by samyH** [comment] 2023-02-15 16:37
@vincentfretin no nothing with selector type - I have some hidden planes, which I'm using as triggers on gaze that it is happening consistently on, but when I isolate those planes with nothing else in the scene it doesn't happen - think this is going to be a difficult one to isolate - I'm on another project at the moment, but when I return to this one I'll look at this issue again.

**Comment by igniscyan** [comment] 2023-03-01 09:29
Am also having this issue, easiest reproduction I've found is to load up the 360 video example on site, and click one of the video components.

**Comment by vincentfretin** [comment] 2023-03-02 10:41
Please someone provide a link with an example where you reproduce it.

**Comment by samyH** [comment] 2023-03-02 11:22
https://aframe.io/examples/showcase/360-video/

**Comment by vincentfretin** [comment] 2023-03-02 11:36
Clicking the a-videosphere indeed gives an error
```
TypeError: e.match is not a function
aframe-inspector.min.js:7242:21
```
that may be a different issue.
It's not the same error than you reported @samyH

**Comment by samyH** [comment] 2023-03-02 11:46
@vincentfretin very true, but the same outcome of the sidebars vanishing, objects still selectable and unable to exit the inspector

**Comment by Snowirbix** [comment] 2023-03-13 14:07
@vincentfretin I just started using Aframe and I get this error ```e.match is not a function``` everytime with just a simple a-video tag.
Is there a stable version of Aframe I can use ?

**Comment by igniscyan** [comment] 2023-03-13 15:25
> @vincentfretin I just started using Aframe and I get this error ```e.match is not a function``` everytime with just a simple a-video tag.
> 
> Is there a stable version of Aframe I can use ?

I personally had to roll back to 1.1 to get the inspector fully working correctly. It appears it's an issue that has gotten worse through updates, I'm not really sure how active the development is on this library so rolling back is probably your best bet

**Comment by dmarcos** [comment] 2023-03-13 20:14
@igniscyan what problems are you having with A-Frame 1.4.1? If you can file github issues it will be super appreciated

**Comment by igniscyan** [comment] 2023-03-13 20:43
> @igniscyan what problems are you having with A-Frame 1.4.1? If you can file github issues on the inspector repo it will be super appreciated:
> 
> 
> 
> https://github.com/aframevr/aframe-inspector

I actually haven't tried 1.4.1 since I encountered the issue. Is the issue mentioned in this thread fixed there? I found while I was rolling back through versions that it would break at different points/in different components and landed on 1.1 being a place where everything worked out of the box.

**Comment by vincentfretin** [comment] 2023-03-14 10:46
Selecting an entity with a video texture is fixed in PR https://github.com/aframevr/aframe-inspector/pull/680

**Comment by vincentfretin** [comment] 2023-03-31 10:18
@samyH can you please create something on glitch even if it's a complex scene where we can reproduce your error? Otherwise the issue will never be fixed.

**Comment by tomfelder94** [comment] 2023-04-06 07:29
I have the same issue, as soon as I click on a video entity or its parent. The console shows the following:

<img width="677" alt="Screenshot 2023-04-06 at 09 27 43" src="https://user-images.githubusercontent.com/101552390/230305581-66c9d16e-54d6-4d91-97bc-9dd8cea5ef9c.png">

I can try to reproduce with a simple example on glitch later if that helps

**Comment by vincentfretin** [comment] 2023-04-06 07:47
@tomfelder94 your specific stacktrace is the https://github.com/aframevr/aframe-inspector/pull/680 issue that has been fixed. You need to create your own build of aframe-inspector to have the fix or wait for aframe 1.4.2.

**Comment by tomfelder94** [comment] 2023-04-06 07:55
thanks @vincentfretin , any rough idea when 1.4.2 is gonna be released?

**Comment by vincentfretin** [comment] 2023-04-06 08:13
I'm not the one that make releases, @dmarcos is.
If you don't want to wait, create a build like this:

```
git clone git@github.com:aframevr/aframe-inspector.git
cd aframe-inspector
npm install
npm run dist
```
get the `dist/aframe-inspector.min.js` file and put it somewhere, like in glitch assets, then reference it 
```
<a-scene inspector="url:https://cdn.glitch.global/xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/aframe-inspector.min.js?v=1644331843500">
```

**Comment by nightgryphon** [comment] 2023-06-13 21:08
I've got same issue for .obj mesh imported from blender. The mesh contains multiple submeshes (.obj contain more than one "o" commands) with different materials. When i click on such mesh the inspector UI dissapears.
To reproduce you can select a few objects in blender and export selected as .obj

**Comment by vincentfretin** [comment] 2023-06-14 07:10
@nightgryphon please provide a reproducible case on glitch with aframe 1.4.2 http://glitch.com/~aframe
Thank you!

**Comment by vincentfretin** [comment] 2023-07-03 12:01
Oops, it seems aframe-inspector 1.4.2 wasn't released @dmarcos https://github.com/aframevr/aframe/issues/5324#issuecomment-1618095099

**Comment by dmarcos** [comment] 2023-07-03 20:51
Thanks and sorry. Just published inspector 1.4.2. Let me know if there's still any issue

**Comment by Mrbside** [comment] 2023-07-04 03:08
I can confirm the bug is fixed using 1.4.2, thanks

**Comment by vincentfretin** [comment] 2023-07-04 08:37
To everyone that commented on this issue, do you still have an issue with the panels disappearing?
If no, then we can close the issue. If yes, please provide an example.

**Comment by tomfelder94** [comment] 2023-07-04 09:20
Works for me, thanks guys!

**Comment by samyH** [comment] 2023-07-04 13:33
@vincentfretin I can't seem to make it happen anymore - didn't even change the aframe version (still running 1.3) will report back if it happens again - nice job to all you guys who helped get this sorted less stress for all :)

**Comment by vincentfretin** [comment] 2023-07-04 14:07
@samyH You can close the issue then. If you have another issue on aframe 1.4.2 or above, please create an issue with a glitch example directly in [aframe-inspector](https://github.com/aframevr/aframe-inspector/) repo. Thanks.

**Closed** 2023-07-04 14:56 UTC

**Comment by Mrbside** [comment] 2023-10-06 20:23
> @samyH You can close the issue then. If you have another issue on aframe 1.4.2 or above, please create an issue with a glitch example directly in [aframe-inspector](https://github.com/aframevr/aframe-inspector/) repo. Thanks.

the bug is back in october 2023 as I just posted here https://github.com/aframevr/aframe/issues/5324#issuecomment-1751359857
