### ISSUE TITLE
360 video - Android Firefox

### ISSUE THREAD

**Issue by chiliwax** [aframevr/aframe#4950] opened 2021-10-29 14:03 UTC
**Description:**

- A-Frame Version: **1.2.0**
- Platform / Device: 
         **Android + Firefox :** 
        - Samsung galaxy s10 - android 11
        - Samsung galaxy s20 - android 11 or 12 (don't remember my bad :cry:)
        - Redmi note 10 pro - MIUI 12.5.3
- Reproducible Code Snippet or URL: 
[https://aframe.io/aframe/examples/boilerplate/360-video/](https://aframe.io/aframe/examples/boilerplate/360-video/)
[https://fuleinist.github.io/aframe-360-video/](https://fuleinist.github.io/aframe-360-video/)

**Description:**

⚠️  - Happened only on Firefox - tested versions (same on all devices): 93.2.0 / 94.0.0-beta.5

When I launch the 360 videos on these examples above I have a black screen. 
It looks like the video is launched because I have a sound from my devices.

I tried several things as a button to launch the video (as said here: https://github.com/aframevr/aframe/issues/1556#issuecomment-228410269) but nothing change, I still have the same issue...

FYI : I used Angular to reproduce it by myself and to try to solve it without any success.

If someone has an idea I should be glad to hear it :)

**Logs information:**
```log
Angular is running in development mode. Call enableProdMode() to enable production mode. core.js:28072:16
webvr-polyfill: Invalid timestamps detected: Timestamp from devicemotion outside expected range. aframe-master.js:52272:14
core:a-assets:warn Asset loading timed out in   60000 ms aframe-master.js:2201:32
THREE.Color: Unknown color transparent 2 aframe-master.js:13876:12
Use of the orientation sensor is deprecated. zone.js:1752:42
WebGL warning: tex(Sub)Image[23]D: Resource has no data (yet?). Uploading zeros. aframe-master.js:22533:18
WebGL warning: drawElementsInstanced: Tex image TEXTURE_2D level 0 is incurring lazy initialization. aframe-master.js:19142:6
WebGL warning: tex(Sub)Image[23]D: Resource has no data (yet?). Uploading zeros. aframe-master.js:22533:18
WebGL warning: drawElementsInstanced: Tex image TEXTURE_2D level 0 is incurring lazy initialization. aframe-master.js:19142:6
WebGL warning: tex(Sub)Image[23]D: Resource has no data (yet?). Uploading zeros. aframe-master.js:22533:18
WebGL warning: drawElementsInstanced: Tex image TEXTURE_2D level 0 is incurring lazy initialization. aframe-master.js:19142:6
WebGL warning: tex(Sub)Image[23]D: Resource has no data (yet?). Uploading zeros. aframe-master.js:22533:18
WebGL warning: drawElementsInstanced: Tex image TEXTURE_2D level 0 is incurring lazy initialization. aframe-master.js:19142:6
WebGL warning: tex(Sub)Image[23]D: Resource has no data (yet?). Uploading zeros. aframe-master.js:22533:18
WebGL warning: drawElementsInstanced: Tex image TEXTURE_2D level 0 is incurring lazy initialization. aframe-master.js:19142:6
WebGL warning: tex(Sub)Image[23]D: Resource has no data (yet?). Uploading zeros. aframe-master.js:22533:18
WebGL warning: drawElementsInstanced: Tex image TEXTURE_2D level 0 is incurring lazy initialization. aframe-master.js:19142:6
WebGL warning: tex(Sub)Image[23]D: Resource has no data (yet?). Uploading zeros. aframe-master.js:22533:18
WebGL warning: drawElementsInstanced: Tex image TEXTURE_2D level 0 is incurring lazy initialization. aframe-master.js:19142:6
WebGL warning: tex(Sub)Image[23]D: Resource has no data (yet?). Uploading zeros. aframe-master.js:22533:18
WebGL warning: drawElementsInstanced: Tex image TEXTURE_2D level 0 is incurring lazy initialization. aframe-master.js:19142:6
WebGL warning: tex(Sub)Image[23]D: Resource has no data (yet?). Uploading zeros. aframe-master.js:22533:18
WebGL warning: drawElementsInstanced: Tex image TEXTURE_2D level 0 is incurring lazy initialization. aframe-master.js:19142:6
WebGL warning: tex(Sub)Image[23]D: Resource has no data (yet?). Uploading zeros. aframe-master.js:22533:18
WebGL warning: drawElementsInstanced: Tex image TEXTURE_2D level 0 is incurring lazy initialization. aframe-master.js:19142:6
WebGL warning: tex(Sub)Image[23]D: Resource has no data (yet?). Uploading zeros. aframe-master.js:22533:18
WebGL warning: drawElementsInstanced: Tex image TEXTURE_2D level 0 is incurring lazy initialization. aframe-master.js:19142:6
WebGL warning: tex(Sub)Image[23]D: Resource has no data (yet?). Uploading zeros. aframe-master.js:22533:18
WebGL warning: drawElementsInstanced: Tex image TEXTURE_2D level 0 is incurring lazy initialization. aframe-master.js:19142:6
```

**Note:**
Work on IOS - Firefox / Safari / Chrome (with the same code / examples above)
Work on Android - Chrome / Samsung Browser / Huawei Browser (with the same code/examples above)
All my local tests were done on **HTTPS**

Thank's in advance :)

**Comment by pixelistik** [comment] 2021-11-29 14:08
This is probably a duplicate of #4895

**Comment by dmarcos** [comment] 2022-11-19 03:33
Is this still an issue with A-Frame 1.3.0?

**Comment by chiliwax** [comment] 2022-11-28 09:01
nop, it's look like that the 1.3.0 solve this issue :)

**Closed** 2022-11-28 09:32 UTC
