### ISSUE TITLE
mouseleave doesn't fire consistently

### ISSUE THREAD

**Issue by enjalot** [aframevr/aframe#858] opened 2016-01-19 22:26 UTC
I trigger an animation on `mouseenter` which works consistently, but the event handler for `mouseleave` does not seem to fire consistently
example: 
http://bl.ocks.org/enjalot/8be32e6f1f32920ba841

**Comment by ngokevin** [comment] 2016-01-19 22:27
Related: https://github.com/aframevr/aframe/issues/857

**Comment by dmarcos** [comment] 2016-01-19 22:33
@enjalot if you replace your ```a-cubes``` with ```a-entity```. Do you see the same problem?

**Comment by dmarcos** [comment] 2016-01-19 23:14
I don't think this is a problem with the cursor. If you wait for the animation triggered on mouseenter to finish and then you move the mouse out of the object the animation triggered on mouseleave plays consistently. I think it's a problem with having two animations playing at the same time.

**Comment by donmccurdy** [comment] 2016-10-23 18:28
If it was cursor-related, this was probably fixed by e4900e16ea9228af39d2a4fef6798393e79bd82a.

**Comment by ngokevin** [comment] 2016-11-10 10:54
mouseleave is fixed, but this is a dupe of two animations at the same time https://github.com/aframevr/aframe/issues/857

**Closed by ngokevin** 2016-11-10 10:54 UTC
