### ISSUE TITLE
trying to add to project failed

### ISSUE THREAD

**Issue by lukemcredmond** [aframevr/aframe#4732] opened 2020-11-24 01:29 UTC
**Description:**

cannot add aframe to project getting the following error
wanted: {"node":">= 4.6.0","npm":"^2.15.9"} (current: {"node":"12.18.3","npm":"6.14.8"})

- A-Frame Version: 1.0.4
- Platform / Device: Win10
- Reproducible Code Snippet or URL:

47 warn notsup Unsupported engine for aframe@1.0.4: wanted: {"node":">= 4.6.0","npm":"^2.15.9"} (current: {"node":"12.18.3","npm":"6.14.8"})
48 warn notsup Not compatible with your version of node/npm: aframe@1.0.4
49 verbose notsup Not compatible with your version of node/npm: aframe@1.0.4
49 verbose notsup Required: {"node":">= 4.6.0","npm":"^2.15.9"}
49 verbose notsup Actual:   {"npm":"6.14.8","node":"12.18.3"}
50 verbose stack Error: spawn git ENOENT
50 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
50 verbose stack     at onErrorNT (internal/child_process.js:469:16)
50 verbose stack     at processTicksAndRejections (internal/process/task_queues.js:84:21)
51 verbose cwd C:\Users\xxxxxxx\Documents\Code Projects\Firebase\project-name
52 verbose Windows_NT 10.0.19041
53 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\xxxxxxx\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "--save" "aframe"
54 verbose node v12.18.3
55 verbose npm  v6.14.8
56 error code ENOENT
57 error syscall spawn git
58 error path git
59 error errno ENOENT
60 error enoent Error while executing:
60 error enoent undefined ls-remote -h -t ssh://git@github.com/ngokevin/debug.git
60 error enoent
60 error enoent
60 error enoent spawn git ENOENT
61 error enoent This is related to npm not being able to find a file.
62 verbose exit [ 1, true ]

**Comment by dmarcos** [comment] 2020-11-24 03:36
It should work. Hard to tell what's going on without code to look at.

**Comment by lukemcredmond** [comment] 2020-11-24 07:58
> It should work. Hard to tell what's going on without code to look at.

No  code just trying to install before I write code using npm install aframe command

**Comment by dmarcos** [comment] 2020-11-24 19:42
It's working for me. I'm on Windows. Not sure what's particular about your setup

![cmd](https://user-images.githubusercontent.com/39342/100143374-146bd180-2e4a-11eb-922c-9870ddd280c4.png)

**Comment by lukemcredmond** [comment] 2020-11-24 19:49
That is wierd, ill post the top part of the log later when back in front of pc, there was some errors trying to ssh maybe that might help,

I'll try the yarn method later also

**Comment by lukemcredmond** [comment] 2020-11-25 00:39
verbose cli   'install',
1 verbose cli   '--save',
1 verbose cli   'aframe'
1 verbose cli ]
2 info using npm@6.14.8
3 info using node@v12.18.3
4 verbose npm-session ecc25b06e053a663
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 200 https://registry.npmjs.org/aframe 84ms (from cache)
8 silly pacote tag manifest for aframe@latest fetched in 161ms
9 timing stage:loadCurrentTree Completed in 15429ms
10 silly install loadIdealTree
11 silly install cloneCurrentTreeToIdealTree
12 timing stage:loadIdealTree:cloneCurrentTree Completed in 165ms
13 silly install loadShrinkwrap
14 timing stage:loadIdealTree:loadShrinkwrap Completed in 11049ms
15 silly install loadAllDepsIntoIdealTree
16 silly resolveWithNewModule aframe@1.0.4 checking installable status
17 silly fetchPackageMetaData error for debug@github:ngokevin/debug#noTimestamp Error while executing:
17 silly fetchPackageMetaData undefined ls-remote -h -t ssh://git@github.com/ngokevin/debug.git
17 silly fetchPackageMetaData
17 silly fetchPackageMetaData
17 silly fetchPackageMetaData spawn git ENOENT
18 silly fetchPackageMetaData error for document-register-element@github:dmarcos/document-register-element#8ccc532b7f3744be954574caf3072a5fd260ca90 Error while executing:
18 silly fetchPackageMetaData undefined ls-remote -h -t ssh://git@github.com/dmarcos/document-register-element.git
18 silly fetchPackageMetaData
18 silly fetchPackageMetaData
18 silly fetchPackageMetaData spawn git ENOENT
19 silly fetchPackageMetaData error for three-bmfont-text@github:dmarcos/three-bmfont-text#1babdf8507c731a18f8af3b807292e2b9740955e Error while executing:
19 silly fetchPackageMetaData undefined ls-remote -h -t ssh://git@github.com/dmarcos/three-bmfont-text.git
19 silly fetchPackageMetaData
19 silly fetchPackageMetaData
19 silly fetchPackageMetaData spawn git ENOENT
20 http fetch GET 200 https://registry.npmjs.org/deep-assign 571ms (from cache)
21 http fetch GET 200 https://registry.npmjs.org/present 563ms (from cache)
22 http fetch GET 200 https://registry.npmjs.org/super-animejs 563ms (from cache)
23 http fetch GET 200 https://registry.npmjs.org/promise-polyfill 571ms (from cache)
24 http fetch GET 200 https://registry.npmjs.org/super-three 611ms (from cache)
25 silly pacote range manifest for deep-assign@^2.0.0 fetched in 685ms
26 silly resolveWithNewModule deep-assign@2.0.0 checking installable status
27 silly pacote version manifest for present@0.0.6 fetched in 689ms
28 silly resolveWithNewModule present@0.0.6 checking installable status
29 silly pacote range manifest for super-animejs@^3.1.0 fetched in 689ms
30 silly resolveWithNewModule super-animejs@3.1.0 checking installable status
31 silly pacote range manifest for promise-polyfill@^3.1.0 fetched in 701ms
32 silly resolveWithNewModule promise-polyfill@3.1.0 checking installable status
33 silly pacote range manifest for super-three@^0.111.6 fetched in 705ms
34 silly resolveWithNewModule super-three@0.111.6 checking installable status
35 http fetch GET 200 https://registry.npmjs.org/webvr-polyfill 222ms (from cache)
36 silly pacote range manifest for webvr-polyfill@^0.10.10 fetched in 268ms
37 silly resolveWithNewModule webvr-polyfill@0.10.12 checking installable status
38 http fetch GET 304 https://registry.npmjs.org/custom-event-polyfill 1081ms (from cache)
39 http fetch GET 304 https://registry.npmjs.org/load-bmfont 859ms (from cache)
40 silly pacote range manifest for load-bmfont@^1.2.3 fetched in 867ms
41 silly resolveWithNewModule load-bmfont@1.4.1 checking installable status
42 silly pacote range manifest for custom-event-polyfill@^1.0.6 fetched in 1110ms
43 silly resolveWithNewModule custom-event-polyfill@1.0.7 checking installable status
44 timing stage:rollbackFailedOptional Completed in 4ms

getting these errors "undefined ls-remote -h -t ssh://git@github.com/xxxx" could this be a cause?

Thanks again for your help.
I have Tried with Yarn and it seemed to work but am interested into why it did not work with npm

**Comment by dmarcos** [comment] 2020-11-25 19:50
Glad it's working with yarn. Not sure what's particular about your setup. 

- Make sure your not behind a firewall that it's blocking ssh traffic to certain domains.
- Try updgrading node to 14.X.Y

**Comment by marttikaarik** [comment] 2021-01-21 13:01
Problem is in the engines section of package.json.
"npm": "^2.15.9" means "npm": ">=2.15.9 <3.0.0". Anything since 3.0.0 is considered unsupported.

**Comment by dmarcos** [comment] 2021-01-21 17:12
Thanks for the update. Are there any changes we have to do on the A-Frame side or we can close this?

**Comment by marttikaarik** [comment] 2021-01-22 14:30
I'm not the OP, but the problem is not specific to A-Frame, so you can close.
You could update package.json to get rid of the unsupported warning (that causes uninformed people, such as myself, to blame it for the failure).

**Comment by dmarcos** [comment] 2021-01-22 14:57
Thanks! Closing for now. We can reopen if necessary

**Closed by dmarcos** 2021-01-22 14:57 UTC
