### ISSUE TITLE
<a-curvedimage> not showing image

### ISSUE THREAD

**Issue by cvan** [aframevr/aframe#933] opened 2016-02-05 10:20 UTC
@vortice3D writes in aframevr/aframe-site#146:

> On my Android Phone (Moto X- 2nd Gen) <a-curveimage> is not showing any image, using Chrome nor Firefox apps. The same is true for a Nexus 7 2013 Ed and Samsung Galaxy S3.
> 
> Indeed, the framework sample "curved-mockup" is also not showing nothing at all in those same devices.
> 
> However, all works fine on desktop versions of Firefox and Chrome in Win7.

**Comment by ngokevin** [comment] 2016-02-18 01:17
Dupe of our android bugs https://github.com/aframevr/aframe/issues/956

Fixed on dev, working on publishing 0.1.2

**Closed by ngokevin** 2016-02-18 01:17 UTC
Labels: mobile, needs repro, type: bug
