### ISSUE TITLE
Camera move slowly in samsung S6 & S7 since 0.8

### ISSUE THREAD

**Issue by stephanedemotte** [aframevr/aframe#3427] opened 2018-03-09 17:33 UTC
Camera move slowly on S7, and only in vertical in S6

- A-Frame Version: 0.8
- Platform / Device: Samsung S6 & S7

[video] https://photos.app.goo.gl/t6f11QtyYpxDAODx1

**Comment by karanganesan** [comment] 2018-03-10 02:55
Also so OnePlus 3T

Chrome 65 (latest stable)
Version 0.8.0

Basic Example also same kind of slow camera https://aframe.io/examples/

**Comment by dustinkerstein** [comment] 2018-03-10 23:51
This is due to a change in Chrome m65 which breaks the Polyfill. See here for more info:

https://github.com/immersive-web/webvr-polyfill/issues/307
https://bugs.chromium.org/p/chromium/issues/detail?id=819413
https://bugs.chromium.org/p/chromium/issues/detail?id=796518
https://bugs.chromium.org/p/chromium/issues/detail?id=805146

The fix was merged a day late to make the M65 stable release, and unfortunately the fix ends up causing further issues ([819413](https://bugs.chromium.org/p/chromium/issues/detail?id=819413)).

**Comment by dmarcos** [comment] 2018-03-10 23:59
@dustinkerstein Thanks for the detailed info. 

So my understanding is that there's not anything we can do on the A-Frame side and everything will work again once M66 ships. I leave this issue open as a reference and as a reminder to verify M66 when available.

**Comment by dustinkerstein** [comment] 2018-03-11 00:03
@dmarcos That's correct. It's a Chrome platform issue that was caused by an incomplete merge (796518 depends on 805146 but it wasn't originally planned for m65).

**Comment by HyvelTjuven** [comment] 2018-03-11 11:05
Also experiencing this on Oneplus 5. 
Vertical movement is extremely slow, horizontal barely works.

Chrome 65.
Android 8.0.0
A-frame version 0.8.0

Works fine on iPhone.

**Comment by Runnermax** [comment] 2018-03-14 09:44
Happens, after the Chrome update yesterday, on the Nexus 5X too. 
Yay. \o/

Chrome 65
Android 8.1.0
Aframe Version 0.8.0

**Comment by dustinkerstein** [comment] 2018-03-14 20:25
Some more info on a separate but similar issue in Chrome M66: 

They are changing the rotationRate units in the deviceMotion API from radians -> degrees to be in line with the actual spec. This is a good thing in the long term, but unfortunately, this is going break all existing Polyfilled sites on Chrome (including all A-Frame sites using a locally hosted library). It's already been addressed in the dev version of the Polyfill, which should find it's way into A-Frame soon, but it's going to be a bit of a mess once M66 goes stable. Here are the tickets where this change is currently being tracked:

Chromium - https://bugs.chromium.org/p/chromium/issues/detail?id=541607
Polyfill / cardboard-vr-display - https://github.com/immersive-web/cardboard-vr-display/issues/18

There's a tiny bit of hope that they decide to tweak how they implement this change (there's a suggestion about changing the spec so that it provides a "units" parameter) but most likely all Polyfill dependent sites will need to upgrade to support Chrome M66+.

**Closed** 2018-03-15 05:14 UTC
Labels: needs verification
