### ISSUE TITLE
The touch control doesn't work in the version 0.8.1

### ISSUE THREAD

**Issue by dancespiele** [aframevr/aframe#3484] opened 2018-03-22 10:12 UTC
**Description:**

- A-Frame Version: 0.8.1
- Platform / Device: VR PRIMUS VA4
- Reproducible Code Snippet or URL: 
```html
<a-scene>
     <a-box position="-1 0.5 -3" rotation="0 45 0" color="#4CC3D9" shadow></a-box>
     <a-sphere position="0 1.25 -5" radius="1.25" color="#EF2D5E" shadow></a-sphere>
     <a-cylinder position="1 0.75 -3" radius="0.5" height="1.5" color="#FFC65D" shadow></a-cylinder>
     <a-plane position="0 0 -4" rotation="-90 0 0" width="4" height="4" color="#7BC8A4" shadow></a-plane>
     <a-sky color="#ECECEC"></a-sky>                
     <a-camera position="0 1.6 0" look-controls></a-camera>
</a-scene>
```

It touch control worked in the version 0.7.1. I this new version doesn't works
Also I tried something like
```html
<a-entity id="rig"
          movement-controls
          position="25 0 25">
  <a-entity camera
            position="0 1.6 0"
            look-controls="pointerLockEnabled: true"></a-entity>
</a-entity>
```
but without success.

**Comment by donmccurdy** [comment] 2018-03-22 16:55
Talking in Slack, for clarity the second code snippet with `movement-controls` is a red herring I think; that's aframe extras and no current release of aframe-extras works with aframe 0.8.0 yet.

**Comment by donmccurdy** [comment] 2018-03-22 16:58
Extra details... we're talking about a vrprimus VA4 device, which has a joystick included.

Are you sure you don't need any other components but `look-controls` to get this working in 0.7.1? And the joystick moves the camera around, not just rotates it? I'm not sure how `look-controls` would have moved the camera in 0.7.1 unless this device is faking 6DOF pose or something...

**Comment by dancespiele** [comment] 2018-03-22 17:11
If use the same code in a version 0.7.1 the joystick works. If you for example click without glasses the button icon to go to VR you will see that after if you try to move the camera touching it doesn't work with 0.8.1 but it works in 0.7.1. The joystick just rotate it.

**Comment by machenmusik** [comment] 2018-03-22 19:13
FYI -- I ran into something on another experiment where previous code that directly manipulated the camera Object3D rotation don't work anymore with look-controls in 0.8.x, because look-controls now uses its own internal pitchObject and yawObject and overwrites the Object3D... so whatever code the joystick was previously using may need to modify the pitchObject and yawObject rotation instead

**Comment by machenmusik** [comment] 2018-03-22 19:14
snippet from relevant tick handler:
```  tick: function (t, dt) {
    if (!this.data.enabled) { return; }
    // With latest master, it is recommended to manipulate object3D rotation directly.
    var rotation = this.el.object3D.rotation;
    // FIX: with A-Frame 0.8.x, need to modify pitchObject of look-controls, if present.
    var lookControls = this.el.components['look-controls'];
    if (lookControls) { rotation = lookControls.pitchObject.rotation; }
    if (!rotation) { return; }
    if (this.directionX || this.directionY) {
      // Remember, object3D rotation is in radians!
      rotation.x += this.data.dx * THREE.Math.DEG2RAD * this.directionY;
      if (lookControls) { rotation = lookControls.yawObject.rotation; }
      rotation.y += this.data.dy * THREE.Math.DEG2RAD * this.directionX;
    }
  }```

**Comment by dancespiele** [comment] 2018-03-22 21:39
@machenmusik then is it a bug to fix or I have to implement the above code, sorry but I don't understand very well, it is right that I'm really beginner with this library.

**Comment by machenmusik** [comment] 2018-03-22 21:50
None of us have the hardware you do, so part of the complication here is that we don't understand the mechanism that was working previously, but no longer does with 0.8.x - if it was using aframe-extras, I don't think @donmccurdy has updated for 0.8.x, so that is expected; if it was using some other component that directly modified rotation, at present that needs modifications similar to what is posted above.  (Plain A-Frame does not, to my understanding, support joystick input without other components, so not sure if that hardware is generating other events when the joystick moves, for example...)

**Comment by dancespiele** [comment] 2018-03-22 21:57
Then in my case I will continue to use the 0.7.1 version until aframe-extra is updated. If I have time I will look into the commits if I can understand which changes broke it.

**Comment by machenmusik** [comment] 2018-03-22 22:00
OK - then perhaps the right thing to do here is to create an issue in aframe-extras repository referencing this one, then close this one here and await resolution from aframe-extras.

**Comment by donmccurdy** [comment] 2018-03-22 22:01
The master branch of aframe-extras may work now, with a syntax like this:

```html
<a-entity id="rig"
          movement-controls
          position="25 0 25">
  <a-entity camera
            position="0 1.6 0"
            look-controls="pointerLockEnabled: true"></a-entity>
</a-entity>
```

But the core issue is that i don't know if this device's joystick is generating gamepad axis events, dpad events, MouseMove events, or what. If it did in fact work with only `look-controls` before, then it may be faking MouseMove, in which case aframe-extras will not help — i'm relying on `look-controls` for mouse movement as well. 😐

**Comment by donmccurdy** [comment] 2018-03-22 22:03
Oh, to clarify, if it was just rotating the screen (and not moving the player) before then it was probably causing either mouse or touch events... I think aframe-extras is unrelated here sorry.

**Comment by dancespiele** [comment] 2018-03-22 22:51
@machenmusik this is not regarding with aframe-extras, in the version 0.7.1 it works without use aframes-extra.
@donmccurdy I have to test aframe-extra if my joystick works and I can move around the scenery, it would be great :+1:

**Comment by dmarcos** [comment] 2019-02-02 00:06
@dancespiele Closing due to lack of info / hardware / example to reproduce. Try 0.8.2 and a camera rig as described above. Please comment if this is still an issue. Happy to reopen.

**Closed by dmarcos** 2019-02-02 00:06 UTC
