### ISSUE TITLE
raycaster-intersection event missing details 

### ISSUE THREAD

**Issue by DevinBayly** [aframevr/aframe#4834] opened 2021-03-23 23:01 UTC
**Description:**

I'm running into the same issue that is on stackoverflow at this link 
https://stackoverflow.com/questions/61944027/aframe-how-to-get-intersected-elements-from-raycaster-intersection-event 

The expected behavior is to have the box element represented in the console.log message that is shown when the `raycaster-intersection` event is triggered, but instead we see the `event.detail.els` is empty

```
player hit something 
{…}
​
els: Array []
​
intersections: Array []
​
<prototype>: Object { … }
index.js:24:15
```

- A-Frame Version: 1.2.0
- Platform / Device: firefox browser
- Reproducible Code Snippet or URL: 
index.html
```
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <title>Hello, WebVR! • A-Frame</title>
    <meta name="description" content="Hello, WebVR! • A-Frame" />
    <script src="https://aframe.io/releases/1.2.0/aframe.min.js"></script>
  </head>
  <body>
    <script src="index.js"></script>
    <a-scene background="color: #ECECEC">
      <a-entity collider-check="" id="rig" position="0 0 0" player="">
        <a-entity
          id="camera"
          look-controls=""
          wasd-controls="acceleration:2"
          camera=""
          position=""
          rotation=""
        >
          <a-entity
            raycaster="objects: .collidable"
          ></a-entity>
        </a-entity>
      </a-entity>
      <a-box
             raycaster-listener
        class="collidable"
        position="-1 0.5 -3"
        rotation="0 45 0"
        color="#4CC3D9"
        shadow
      ></a-box>
      <a-sphere
        position="0 1.25 -5"
        radius="1.25"
        color="#EF2D5E"
        shadow
      ></a-sphere>
      <a-cylinder
        position="1 0.75 -3"
        radius="0.5"
        height="1.5"
        color="#FFC65D"
        shadow
      ></a-cylinder>
      <a-plane
        position="0 0 -4"
        rotation="-90 0 0"
        width="4"
        height="4"
        color="#7BC8A4"
        shadow
      ></a-plane>
    </a-scene>
  </body>
</html>
```
index.js
```
AFRAME.registerComponent('player',{
  init() {
    console.log("creating player")
    let el = this.el
    let scene = el.sceneEl
    window.addEventListener("keydown",(e)=> {
      let sign = 1
      if (e.shiftKey) {
        sign=-1
      }
      if (e.code.match(/space/i)) {
        el.object3D.position.y += .1*sign
      }
    })
  }
})

// raycasting collisin check, add this to something and it will alert when the raycaster hits something
//
AFRAME.registerComponent('collider-check', {
  dependencies:['raycaster'],
  init: function () {
    this.el.addEventListener('raycaster-intersection',function(e) {
      console.log('player hit something',e.detail)
    })
  }
})

AFRAME.registerComponent('raycaster-listener',{
  init:function (){
    this.el.addEventListener('raycaster-intersected',function(e){
      console.log("was intersected on",e)
    })
  }
})
```

**Comment by dmarcos** [comment] 2021-03-23 23:52
Link to runnable code to reproduce? I recommend https://glitch.com/edit/#!/aframe

**Comment by DevinBayly** [comment] 2021-03-24 00:12
Here's a glitch with the code, sorry for not throwing this in for starters.

https://ancient-cliff-laundry.glitch.me/

**Comment by dmarcos** [comment] 2021-03-24 00:38
It's working for me: https://glitch.com/edit/#!/resilient-giant-starburst?path=index.js%3A32%3A9

![image](https://p199.p4.n0.cdn.getcloudapp.com/items/NQuwk8QA/24135d32-d9ef-4719-8319-88c6b068afca.gif?v=2bc8bdee237bc5d829c791ada4473e15)

**Comment by dmarcos** [comment] 2021-03-24 00:42
On the collided entity the `raycaster-intersected` fires and you have a reference to the entity with the raycaster in  `e.detail.el`

On the entity with the collider the `raycaster-intersection` event fires and you have `evt.detail.els` defined with the list of collided entities

**Comment by DevinBayly** [comment] 2021-03-24 01:01
Interesting! I also have the correct behavior in your glitch link, but not on my own. I'll look more at this later.

**Comment by dmarcos** [comment] 2021-03-24 01:02
It looks A-Frame behave as expected. Closing for now. Let me know how it goes and we can reopen if necessary

**Closed by dmarcos** 2021-03-24 01:02 UTC

**Comment by DevinBayly** [comment] 2021-03-24 01:09
Yup looks fine actually, I dunno what the story was. Thanks!! @dmarcos

**Comment by floe** [comment] 2021-03-28 20:11
Came across this issue while debugging a similar problem. @dmarcos, when I try your example on Glitch, I get log messages along the lines of `was intersected on <unavailable>` - there seems to be no event to handle. I get the same when trying to get plain old "click" events using mouse emulation - any suggestions why the events just show up as `<unavailable>`?

**Comment by dmarcos** [comment] 2021-03-29 18:18
@floe Are you talking about [this example](https://glitch.com/edit/#!/resilient-giant-starburst?path=index.js%3A31%3A65)? I don't see any of the errors you describe. Steps to reproduce?

**Comment by floe** [comment] 2021-03-29 18:49
Yes, that's the one I meant. I've been testing your unmodified example with Chrome 89 and Firefox 86 in the meantime, and this only happens in Firefox:
![firefox](https://user-images.githubusercontent.com/90756/112884274-9a857680-90cf-11eb-8ebe-2f0b203f063b.png)
Chrome, for comparison:
![chrome](https://user-images.githubusercontent.com/90756/112884742-28616180-90d0-11eb-9bab-1ac1f4a25a96.png)

**Comment by dmarcos** [comment] 2021-03-29 18:57
`<unavailable>` is a strange error message. Just tried in Firefox 86 / Windows and cannot reproduce the issue (see below). Maybe some extension you have installed in your browser could be messing things up? 

![image](https://p199.p4.n0.cdn.getcloudapp.com/items/nOuoB4rD/71ad4f05-8fc5-429f-ba3c-a2fcc99f9ca3.gif?source=viewer&v=3f184e94cf149a9caaa454f33b6778f9)

**Comment by floe** [comment] 2021-03-30 10:03
Turns out this is a known Firefox bug that only appears on the standalone console window: https://bugzilla.mozilla.org/show_bug.cgi?id=1136995

Sorry for the noise ;-)
