### ISSUE TITLE
HLS m3u8 video stream does not work with a-videosphere Safari 9 and iOS 9 mobile Safari

### ISSUE THREAD

**Issue by liuxiaoyue** [aframevr/aframe#1416] opened 2016-04-28 01:31 UTC
hello！ I met the same problem， same issues 1021 (https://github.com/aframevr/aframe/issues/1021),
i think, this is not a limitation of iOS,i find a example that can play, but, Internal testing products，so i can't public sorry! I try to modify aframe texture, use THREE.Texture, end up in faliure! Can be modified？ thanks！

**Comment by dmarcos** [comment] 2016-06-03 01:28
iOS might be able to play m3u8. The problem is using that video stream in the context of a WebGL texture. Please reopen If you can provide a working example.

**Comment by liuxiaoyue** [comment] 2016-06-08 09:50
This issue has been resolved，thanks！

**Comment by invaderhd** [comment] 2016-10-06 13:40
@liuxiaoyue did you find a solution? Can you share it

**Comment by radenui** [comment] 2017-02-22 18:01
Seems like this issue has been resoved (or worked around) in other contexts: 
- For [THREE](https://github.com/mrdoob/three.js/issues/9754#issuecomment-268186791)
- For [GoogleVr](https://github.com/googlevr/vrview/pull/105)

I couldn't figure out yet how to build the required custom material to handle such a video format in a-frame, but I think the hard work has been done already.

**Comment by dmarcos** [comment] 2017-02-22 18:39
@radenui thanks for letting us know

**Comment by machenmusik** [comment] 2017-02-22 19:30
so how does one know when bgra fix is required?  

wondering whether it makes more sense to enable detection and remediation in core/default shaders (so if similar problem arises for different elements, can set bgra property or similar)

**Comment by radenui** [comment] 2017-02-23 08:56
Seems like there are actually 2 problems:
- FlipY  on OSX and iOS (fixed by `vUV = vec2( uv.x, 1.0 - uv.y );`),
- Channel R and B mixed on iOS (fixed by `gl_FragColor = texture2D( texture, vUV  ).bgra;`) [issue comment here](https://github.com/mrdoob/three.js/issues/9754#issuecomment-266309206)

**Comment by machenmusik** [comment] 2017-02-23 10:54
are you sure? `FlipY disabling in my tests was required for MacOs Safari 10 also.`
https://github.com/mrdoob/three.js/issues/9754#issuecomment-273515995

**Comment by machenmusik** [comment] 2017-02-23 10:55
(need to understand also if this is just for video, or also for image, canvas, etc.)

**Comment by robinnorth** [comment] 2017-03-29 15:51
Anyone have any insights as to how to go about turning the workaround proposed at https://github.com/mrdoob/three.js/issues/9754#issuecomment-268186791 into an A-Frame material? This is an issue affecting a project I'm hoping to use A-Frame on, but I'm a bit stuck on how to implement a fix for this.

**Comment by robinnorth** [comment] 2017-03-30 14:18
Looking at this some more, I also wonder if it should be patched in core as @machenmusik suggests.

Following the lead of VR View (see googlevr/vrview/pull/105), the `loadVideo` method of the `material` system could set the necessary texture properties required for the fix. Borrowed code from VR View:

```javascript
if (Util.isSafari() && videoType === VideoType.HLS) {
  // fix black screen issue on safari
  videoTexture.format = THREE.RGBAFormat;
  videoTexture.flipY = false;
} else {
  videoTexture.format = THREE.RGBFormat;
}
```

I suppose then each of the core shaders would then need to implement the same logic as VR View, i.e. choosing between `THREE.MeshBasicMaterial` and `THREE.ShaderMaterial`, depending on whether or not the texture source is an HLS video playing on Safari. Borrowed code from VR View:

```javascript
if (texture.format === THREE.RGBAFormat && texture.flipY === false) {
  material = new THREE.ShaderMaterial({
    uniforms: {
      texture: { value: texture }
    },
    vertexShader: [
      "varying vec2 vUV;",
      "void main() {",
      "	vUV = vec2( uv.x, 1.0 - uv.y );",
      "	gl_Position = projectionMatrix * modelViewMatrix * vec4( position, 1.0 );",
      "}"
    ].join("\n"),
    fragmentShader: [
      "uniform sampler2D texture;",
      "varying vec2 vUV;",
      "void main() {",
      " gl_FragColor = texture2D( texture, vUV  )" + (Util.isIOS() ? ".bgra" : "") + ";",
      "}"
    ].join("\n")
  });
} else {
  material = new THREE.MeshBasicMaterial({ map: texture });
}
```

_or_, perhaps there should be a new core `video-material` shader that is recommended especially for use with videos that implements this logic?

Does that make sense, @dmarcos? I couldn't work out how to fix this with just a custom shader material (using `registerShader` in my app), as the `ShaderMaterial` fix needs to have access to the video texture that the `material` system has loaded.

**Comment by dmarcos** [comment] 2017-03-30 14:38
I would try first to make a core shader `video`. Can we expose the video texture to custom shaders? If tha's hard or not posible we can maybe try something like `video-material` approach

**Comment by machenmusik** [comment] 2017-03-30 14:46
had anyone confirmed that only video on iOS (and HLS video, not MP4 video) suffers from the defect?  there is not just one shader appropriate for all video, and if other significant BGRA sources exist it may be worth adding BGRA support directly to core shaders, controlled by bgra boolean property for example

**Comment by robinnorth** [comment] 2017-03-30 15:07
I've certainly only experienced this issue with HLS on iOS, MP4 video worked perfectly for me, as does MPEG-DASH via Shaka Player on other platforms. Sadly, HLS is the only adaptive bitrate solution you can use on iOS.

@dmarcos I think you and I are talking about the same thing -- a core shader in A-Frame to handle video textures.

**Comment by machenmusik** [comment] 2017-03-30 15:42
@dmarcos i think the question is, when it is too late to change the texture format?

**Comment by machenmusik** [comment] 2017-03-30 15:45
@robinnorth there is not just one shader appropriate for all video really, although you may only be using one, they would all need the change

**Comment by robinnorth** [comment] 2017-03-30 16:36
OK, I've been able to get a custom video shader to display HLS video correctly on iOS and macOS Safari after patching the `loadVideo` method of the `material` system in A-Frame core to set
```
texture.flipY = false;
 texture.format = THREE.RGBAFormat;
```
when in Safari.

Here's my custom shader code (based on the `flat` core shader):

```javascript
AFrame.registerShader( 'video-shader', {
    schema: {
        color: { type: 'color' },
        fog: { default: true },
        height: { default: 256 },
        offset: { type: 'vec2', default: { x: 0, y: 0 } },
        repeat: { type: 'vec2', default: { x: 1, y: 1 } },
        src: { type: 'map' },
        width: { default: 512 },
        wireframe: { default: false },
        wireframeLinewidth: { default: 2 }
    },

    /**
     * Initializes the shader.
     * Adds a reference from the scene to this entity as the camera.
     */
    init: function( data ) {
        if ( IS_SAFARI ) {
            this.material = new THREE.ShaderMaterial( {
                uniforms: {
                    texture: { type: 't', value: this.map }
                },
                vertexShader: [
                    'varying vec2 vUV;',
                    'void main() {',
                    '	vUV = vec2( uv.x, 1.0 - uv.y );',
                    '	gl_Position = projectionMatrix * modelViewMatrix * vec4( position, 1.0 );',
                    '}'
                ].join( '\n' ),
                fragmentShader: [
                    'uniform sampler2D texture;',
                    'varying vec2 vUV;',
                    'void main() {',
                    '	gl_FragColor = texture2D( texture, vUV  )' + (IS_IOS ? '.bgra' : '') + ';',
                    '}'
                ].join( '\n' )
            } );
        } else {
            this.material = new THREE.MeshBasicMaterial( getMaterialData( data ) );
        }
        utils.material.updateMap( this, data );
    },

    update: function( data ) {
        this.updateMaterial( data );
        utils.material.updateMap( this, data );
    },

    /**
     * Updating existing material.
     *
     * @param {object} data - Material component data.
     */
    updateMaterial: function( data ) {
        var material = this.material;
        data = getMaterialData( data );
        Object.keys( data ).forEach( function( key ) {
            material[key] = data[key];
        } );
        material.uniforms = {
            texture: { type: 't', value: material.map }
        };
    }
} );

/**
 * Builds and normalize material data, normalizing stuff along the way.
 *
 * @param {object} data - Material data.
 * @returns {object} data - Processed material data.
 */
function getMaterialData( data ) {
    return {
        fog: data.fog,
        color: new THREE.Color( data.color ),
        wireframe: data.wireframe,
        wireframeLinewidth: data.wireframeLinewidth
    };
}
```

I haven't been able to figure out how to do this without patching core though, as `flipY` really needs to be `false` before any video textures are loaded, due to this WebKit bug: https://bugs.webkit.org/show_bug.cgi?id=163866

**Comment by machenmusik** [comment] 2017-03-30 17:21
> patching the loadVideo method of the material system in A-Frame core to set `...` when in Safari.
@robinnorth those workarounds should only be applied when you are playing native HLS video though, right?  otherwise you break MP4 etc. ?

**Comment by robinnorth** [comment] 2017-03-30 19:10
@machenmusik yes, you are correct. It's only HLS video that suffers from the bug in Safari. VR View handles this by checking the file extension of the video source to see if it's `m3u8` and thus HLS (see my [earlier comment](aframevr/aframe/issues/1416#issuecomment-290424762) that summarises their implementation).

**Comment by machenmusik** [comment] 2017-03-30 20:00
more generally speaking it is not safe to bake the behavior into the shader without parameters, since an app may legally switch between playing MP4 and HLS - also, that check should probably also look for mimetypes since not all HLS streams use .m3u8 suffix

**Comment by machenmusik** [comment] 2017-03-30 20:22
another thought - do you need to flip Y in shader, can you invert Y scale of playback surface?  the bgra accommodation is the thing that absolutely needs shader changes

**Comment by robinnorth** [comment] 2017-03-31 08:07
This shader could be modified to check the source of the video texture applied whenever it changes (in the shader's `update` method) and then set the vertex and fragment shaders according to whether or not the HLS fix is required.

I suppose you could invert the Y scale of the playback surface (and then invert the face that the texture is rendered on), but in both the Three.js and VR View  examples, they've just flipped Y in the shader.

**Comment by quickhand** [comment] 2017-04-04 09:25
Any progress on this, or a workable workaround? I have to put out a major project on Friday that was originally going to use an a-videosphere with HLS on iOS. I have the advantage of knowing that it won't switch to MP4 in this implementation. Any ideas?

**Comment by machenmusik** [comment] 2017-04-04 15:26
I believe there is a workaround described in a previous comment.  I don't think anyone has submitted a PR for the necessary core changes yet, so you may need to use a forked version in the interim.

**Comment by quickhand** [comment] 2017-04-05 08:34
I've tried the shader listed above. It's not working for me. I've already patched the core. With my new patched core, If I use 'flat' shader on my videosphere, the video plays on iOS, but upside down and weirdly colored. So the core appears to be patched correctly. Now, the shader's job is to unflip it and color it correctly, if I understand. But if I use this shader, I get blank screen in both ios and desktop safari. So there must be some issue with the shader.

**Comment by robinnorth** [comment] 2017-04-05 17:12
@quickhand In the short term, you need to define `IS_SAFARI` and `IS_IOS` to be able to use my example shader code (they're constants that get defined elsewhere in my app):

```javascript
const IS_IOS = /iP(hone|ad|od)/i.test( navigator.userAgent ),
    IS_SAFARI = /^((?!chrome|android).)*safari/i.test( navigator.userAgent );
```

In the longer term, if a PR is welcome for the core changes required for `loadVideo` (cc @machenmusik, @dmarcos), I can submit one, as I'll need this fix for my project too.

**Comment by quickhand** [comment] 2017-04-06 00:02
@robinnorth I had already defined the constants, so it's not that. Still nothing appears. It's baffling. No errors in the console, and  I don't even know how to go about debugging it. I'm getting desperate, as my project has to launch tomorrow :-/ Thanks for your help, and let me know if you have any ideas how to approach this.

**Comment by robinnorth** [comment] 2017-04-06 08:08
@quickhand can you put together a JSFiddle test case? Also, I've just looked back at my prototype and realised I'm using just a plain `a-sphere` for some reason. My usage is (I'm using aframe-react):

```jsx
<Entity
    primitive="a-sphere"
    geometry={{ radius: 5000 }}
    material={{ src: '#video', shader: 'video-shader' }}
    scale="1 1 -1"
    rotation="0 90 0"
/>
```

It's also worth making sure you've defined `utils = AFRAME.utils` before the shader definition, and also that the shader is defined before you try and use it.

**Comment by quickhand** [comment] 2017-04-06 10:20
Yes, I had defined utils = AFRAME.utils as well. And I am also using a plain a-sphere. Also using aframe-react :)

As I said, release is tomorrow, and two days later I leave my job, and the country. So I won't be able to mock up a test case for a while. Thanks for all the help, but I had to give up and switch to .mp4 on iOS. Amusingly, I'm now using HLS on everything except Apple systems. I chose HLS over MPEG-DASH because of the lack of Apple support (and used hls.js to add support to non-apple browsers). So much for that! Safari is the bane of my existence.

**Comment by aminasyeda** [comment] 2017-04-06 20:09
@robinnorth: A JSFiddle would really help to know how you are putting together the custom video-shader.  I have the same issue. HLS on safari and mobile renders black screen for the video though the audio works. Appreciate your help.

**Comment by machenmusik** [comment] 2017-05-12 22:07
There is now support merged into latest master for HLS on iOS 10 with Mobile Safari.

Unfortunately my understanding is that said support will not work on earlier versions (e.g. iOS 9) and no further work is planned there.

Should we close this one now?

**Comment by robinnorth** [comment] 2017-05-16 08:57
Nice work, @machenmusik. Really happy to see this make it into core! I think this can be closed now, as iOS 9 support doesn't seem possible

**Comment by ngokevin** [comment] 2019-02-01 23:33
https://github.com/aframevr/aframe/issues/1416#issuecomment-301196774

**Closed by ngokevin** 2019-02-01 23:33 UTC
