### ISSUE TITLE
obj-model as child weird position/duplication

### ISSUE THREAD

**Issue by msj121** [aframevr/aframe#2424] opened 2017-02-21 03:51 UTC
I have noticed that using "a-obj-model" in a scene as a child of another primitive leads to sometimes incorrect positioning or duplication of the object.

I currently cant write an example because I am running into CORS issues on codepen. Does anyone have a link to a ".obj" file that is accessible/embeddable anywhere?

**Comment by dmarcos** [comment] 2020-10-26 23:08
Closing due to lack of info to reproduce.

**Closed by dmarcos** 2020-10-26 23:08 UTC
