### ISSUE TITLE
VR mode on iOS 13.4.1 does not work

### ISSUE THREAD

**Issue by dax72** [aframevr/aframe#4554] opened 2020-04-14 21:50 UTC
Gyroscope movement does not work, it works fine before ios13.4.1 update or without turning on vr mode.

- A-Frame Version: 1.04
- Platform / Device: IOS 13.4.1 - iPhone and iPad

**Comment by machenmusik** [comment] 2020-04-14 23:52
Hi, can you try the branch in PR #4548 and see if that fixes it?

**Comment by dax72** [comment] 2020-04-15 07:36
is there a dist ready to download?

**Comment by dmarcos** [comment] 2020-04-15 21:11
I couldn't find any relevant changes on the Safari release notes:

https://developer.apple.com/documentation/safari_release_notes

**Comment by dax72** [comment] 2020-04-15 22:20
I just tried on another iPad (iPad Pro 12,9""), v13.4.1...same problem! Motion sensor does not work when you click VR button.

**Comment by dmarcos** [comment] 2020-04-15 22:26
We should probably disable cardboard / stereo mode on iPads

**Comment by dax72** [comment] 2020-04-15 22:44
and on iPhone? currently I can confirm that it does not work on iPhone and iPad with iOS13.4.1.
VR mode on iPad has no sense..but on iPhone it's necessary

**Comment by kowalus23** [comment] 2020-04-15 22:46
Got same issue,  with my older iphone for tests with iOS 13.3 it does work properly, but newest 13.4.X it doesn't... as far as i checked `DeviceMotionEvent.requestPermission()` doesn't seem to work right, it asks about permission, right after with my app it reloads page and and my typical promise that checks if it's gyroscope or if the device support gyroscope it saying "false" for iPhone with newest iOS :/  previous version was ok.

Also checked with DeviceOrientationEvent, doesn't help :(

**Comment by dmarcos** [comment] 2020-04-15 22:48
On iPad we can disable. On iPhone we can keep for now. What’s your audience? Can you share details on your application? We see Cardboard usage decline and harder and harder to come by. Polyfilled VR comes with a lot of issues like this one where things break when browser APIs and policies change.

**Comment by dax72** [comment] 2020-04-15 23:13
We create VR games/apps for clients and they require iPhone compatibility

**Comment by dmarcos** [comment] 2020-04-15 23:15
Is iPhone compatibility via Magic Window mode enough? Do you have any metrics of cardboard usage you can share?

**Comment by dax72** [comment] 2020-04-16 07:48
Magic Window mode it's not enough, they need stereo mode.
I think the percentage of iPhone/cardboard is not relevant but clients require the compatibility iPhone/android and without it they do not market products.

Safari iOS from a development point of view is a nightmare because there is
no webVR/webXR support but for big companies it is not their problem, they want it to work on iOS too :(

**Comment by dmarcos** [comment] 2020-04-16 15:27
@dax72 Thanks for the info. Is your client decision based on any audience metrics?

**Comment by dax72** [comment] 2020-04-16 18:39
@dmarcos Unfortunately I don't have access to their audience metrics, but I have more clients that are asking to me to fix this iOS bug

**Comment by dmarcos** [comment] 2020-04-16 18:46
@dax72 Are they willing to pay to fix the issue?

**Comment by andreyrd** [comment] 2020-04-18 17:30
For what it's worth, this also affects magic window tracking, not just VR mode.

**Comment by andreyrd** [comment] 2020-04-18 17:48
Ok, did some investigating. 🕵🏻‍♂️

This was a regression in Webkit, reported on 2020-03-31: https://bugs.webkit.org/show_bug.cgi?id=209831
And patched same day by the reporter: https://github.com/WebKit/webkit/commit/13e78b2bad4fb6f8c8a152e9a3cfc07c910dc858

Unfortunately, considering that the changeset which *introduced* the bug was in December 2019: https://trac.webkit.org/changeset/253357/webkit
And the bug only showed up just now in 13.4.1, it seems it's gonna take a _really long time_ to see the patch fixing it make it's way into iOS.

**Comment by dmarcos** [comment] 2020-04-18 18:00
Thanks for investigating. Super appreciated. Magic window still works for me on examples:

https://aframe.io/aframe/examples/

it’s a different code path

**Comment by andreyrd** [comment] 2020-04-18 18:05
Oh, interesting! That's probably because our team is currently stuck on 0.9.2 for other reasons, which is using the webvr-polyfill / device motion api for magic window?

So scratch that. Can confirm that on latest aframe, magic window is fine.

**Comment by dmarcos** [comment] 2020-04-18 18:08
Since iOS 13, Safari requires permission to access DeviceMotion. 0.9.2 doesn’t have the request logic. It predates iOS 13

**Comment by andreyrd** [comment] 2020-04-18 18:12
Yeah, we manually call `DeviceMotionEvent.requestPermission()`.

**Comment by jwjordan** [comment] 2020-05-12 16:54
Does this pull request fix what is needed for aframe to work properly with iOS 13.4 in cardboard mode? https://github.com/immersive-web/cardboard-vr-display/pull/42
If so, what's the process for getting that incorporated?  Does that PR have to get merged into immersive-web, and then immersive-web gets merged into a new point release for aframe?

**Comment by dmarcos** [comment] 2020-05-12 17:53
@jwjordan Yes, best would be for that PR to merge and then for the [webvr-polyfill](https://github.com/immersive-web/webvr-polyfill/blob/master/package.json#L49) to incorporate. A-Frame would pick a [new version of the polyfill](https://github.com/aframevr/aframe/blob/master/package.json#L52)

**Comment by jsantell** [comment] 2020-05-13 19:36
webvr-polyfill 0.10.12 now has the changes from upstream cardboard-vr-display

**Comment by dmarcos** [comment] 2020-05-13 19:52
@jsantell Yeah! Thank you very much. Super appreciated. I bumped the polyfill on master.

**Closed** 2020-05-13 19:52 UTC

**Comment by jsantell** [comment] 2020-05-13 20:53
shout out to @jwjordan @ivnnv @machenmusik for the research & patches :tada:

**Comment by dmarcos** [comment] 2020-05-13 21:08
Yeah. Thanks everybody 👏

**Comment by jwjordan** [comment] 2020-05-14 16:34
Checked out master and tested in a VR model inside Ideaspace, and I can confirm this fixed the cardboard mode on the latest version of iOS (13.4.1) in my specific instance.  Thanks a ton everyone!

**Comment by levmillr** [comment] 2020-05-15 14:59
Awesome! When does 1.0.5 release? :)

**Comment by dmarcos** [comment] 2020-05-15 16:06
It’ll be 1.1.0 in a few days depending on how QA goes. In the meantime you can use [master builds](https://cdn.jsdelivr.net/gh/aframevr/aframe@cd01cec35a01e03eb2d6a9272500a53de31d3828/dist/aframe-master.min.js)

**Comment by levmillr** [comment] 2020-05-15 16:13
Nice even better! I hope it goes well.  Thank you @dmarcos and thankyou to everyone who worked on this

**Comment by andreyrd** [comment] 2020-05-19 17:28
And of course...everything works just like normal again in iOS 13.5 beta 5 using 1.0.4...

**Comment by dmarcos** [comment] 2020-05-20 07:15
Thanks for reporting

**Comment by NomisGnos** [comment] 2020-05-28 14:10
I can confirm commit cd01cec works.

I assume commit a326ceb will continue to have this update.

**Comment by jgutierro** [comment] 2020-06-11 07:32
Hello @dmarcos and @NomisGnos I opened a new issue and finally was solved! https://github.com/aframevr/aframe/issues/4618#issuecomment-642433783

Thank you so much!
