### ISSUE TITLE
See a text through a plain with opacity=1

### ISSUE THREAD

**Issue by joeloliveira7** [aframevr/aframe#3236] opened 2017-11-16 19:57 UTC
I think there's a issue with text transparency/opacity in the lastest master build. I see a text through a plain with opacity=1.
In 0.7.0 seems fine.

- A-Frame Version: https://rawgit.com/aframevr/aframe/f533f84/dist/aframe-master.min.js
- Platform / Device: Chrome browser
- Reproducible Code Snippet or URL: 
[ex.txt](https://github.com/aframevr/aframe/files/1480023/ex.txt)

**Comment by dmarcos** [comment] 2017-11-17 20:38
@joeloliveira7 Can you share a working example that reproduces the problem?

**Comment by wmurphyrd** [comment] 2017-12-08 23:16
I'm seeing the same thing on master I've been working with (3b6d48a6) and also the latest master (c2f08cf0)

On 0.7.0, the text in the far background is occluded by the nearer objects

![image](https://user-images.githubusercontent.com/10034859/33783761-a8d3f8ec-dc23-11e7-883b-160ccb4e6395.png)

On master it appears in front of them:

![image](https://user-images.githubusercontent.com/10034859/33783776-b977138c-dc23-11e7-9d64-7af814285b9b.png)


https://glitch.com/edit/#!/lewd-ferryboat?path=index.html:7:64

**Comment by ngokevin** [comment] 2017-12-08 23:31
Interesting, anyone fancy doing a bisect?

**Comment by dmarcos** [comment] 2017-12-09 00:18
Without trying this might be the culprit: https://github.com/aframevr/aframe/commit/c1403a27c6ad465ff337c9399365e0da67903112

**Comment by ngokevin** [comment] 2017-12-09 00:46
Earlier I tried setting both to `false` with no affect, but maybe that doesn't work either (maybe needs an update flag, dunno).

**Comment by ngokevin** [comment] 2017-12-09 00:47
They both default to `true` already with/without the properties, so it'd be weird.

**Comment by PButcher** [comment] 2017-12-10 03:27
@dmarcos is right. By removing those changes, text renders behind objects again.

**Comment by wmurphyrd** [comment] 2017-12-10 19:44
Possibly related:

Text placed on a child of an entity with transparency is always rendered behind the entity, even when the Z position is significantly closer to the camera. Occurs on master but not on v0.7.0

Glitch above updated to show this behavior as well: https://glitch.com/edit/#!/lewd-ferryboat?path=index.html:17:84

**Comment by wmurphyrd** [comment] 2018-01-16 17:40
Ok with c1403a2 reverted, I can toggle `material.depthTest` from the console and the behavior changes appropriately. 

The problem is that `text.updateBaseMaterial` is not called with the complete `text.data` but [with a subset](https://github.com/aframevr/aframe/blob/c1403a27c6ad465ff337c9399365e0da67903112/src/components/text.js#L172) that [never contains](https://github.com/aframevr/aframe/blob/c1403a27c6ad465ff337c9399365e0da67903112/src/components/text.js#L157-L164) `text.data.depthTest`/`text.data.depthWrite`

Just need to update the declaration of `shaderData` and it should work as intended.

**Comment by wmurphyrd** [comment] 2018-02-04 12:21
@ngokevin @dmarcos I hear the 0.8.0 release is soon. I think you will get a lot of issues filled from this if it remains. I'm on holiday, but I have a long train journey tomorrow when I think I could tackle it.

**Comment by gabrieljbaker** [comment] 2018-02-05 06:27
@wmurphyrd my project is full of text and these problems so let me know if you want me to help test anything.

**Comment by wmurphyrd** [comment] 2018-02-05 08:37
Looks like this was fixed in ff24dbdccd97c798033c2005c521009b4ae55196

https://glitch.com/edit/#!/horn-sparrow?path=index.html:1:0

Should be OK to close this issue

**Closed** 2019-01-31 22:56 UTC
