### ISSUE TITLE
Experience is not gyroscopically interactive on chrome version 68

### ISSUE THREAD

**Issue by Gauzz** [aframevr/aframe#3731] opened 2018-08-13 11:38 UTC
**Description:**

Web VR experiences are not working on chrome 68 screen appears to be frozen and drag gesture has to be used to interact with experience.

- A-Frame Version: 0.8.2

- Platform / Device: chrome 68/ android

- Reproducible Code Snippet or URL: https://aframe.io

**Comment by primedcore** [comment] 2018-08-13 15:25
Saw the same problem. Sometimes, instead of this, I have the same problem as #3476 which was supposed to be fixed by using the latest version of A-Frame and Polyfill on Chrome 66. Nevertheless, I have Chrome 68 with latest versions of both A-Frame and Polyfill. On some web VR apps, I have the same problem. Take, for example, https://vivid.unit9.com which on Android 8 it freezes position on Firefox latest version, and on (mobile) Chrome latest it's extremely sensitive (as mentioned in #3476).

**Comment by primedcore** [comment] 2018-08-13 15:27
https://konterball.com works fine on Firefox Android, but the A-Frame camera goes crazy when running on Chrome Android.

**Comment by dmarcos** [comment] 2018-08-13 18:13
@primedcore FWIW Neither https://vivid.unit9.com/ nor https://konterball.com are made with A-Frame and use old versions of THREE and the WebVR Polyfill. The authors need to update to more modern versions. Nothing we can do from the A-Frame side.

**Comment by dmarcos** [comment] 2018-08-13 18:31
I tried with Chrome for Android 66, 68, 69 and 70 on a Pixel 2 and cannot reproduce any of the issues described with the A-Frame examples: https://aframe.io/aframe/examples/

**Comment by primedcore** [comment] 2018-08-14 06:43
Double-checked, I presumed something was wrong with these sites instead of my client. However, not even https://aframe.io examples work for me. When I run most of them on Android Chrome, I still get the error mentioned in #3476. Should I comment there? Or open a new issue?

**Comment by Gauzz** [comment] 2018-08-14 07:05
@dmarcos Yeah I double checked it.
Chrome version : 68.0.3440.91
And I am facing this issue on Lenovo Android 6.0 
and Moto g5 android 7.1.2
 I only have this two devices for testing.

**Comment by dmarcos** [comment] 2018-08-14 20:50
@primedcore Can you check your Chrome browser version? What device?

**Comment by dmarcos** [comment] 2018-08-14 20:51
@primedcore I think that the problem you're describing is also different than the original filed issue where the gyro does not seem to work. Can you open a separate issue?

**Comment by dmarcos** [comment] 2018-08-14 20:53
@Gauzz Can you check this URL? https://aframe.io/aframe/examples/showcase/anime-UI/

**Comment by Gauzz** [comment] 2018-08-15 04:39
https://aframe.io/aframe/examples/showcase/anime-UI/
This also appears to be frozen.

**Comment by Gauzz** [comment] 2018-08-15 04:40
@dmarcos One more thing if I host a scene locally on http server it works fine but if I change it to https I need to drag  to interact with it.

**Comment by dmarcos** [comment] 2018-08-15 14:42
That’s weird. if any restriction I would expect it to be applied to HTTP over HTTPS

**Comment by dmarcos** [comment] 2018-08-15 14:46
What about this sample: 
https://webvr.info/samples/03-vr-presentation.html?polyfill=1

**Comment by Gauzz** [comment] 2018-08-15 15:58
Yeah https://webvr.info/samples/03-vr-presentation.html?polyfill=1 is working.

**Comment by dmarcos** [comment] 2018-08-15 19:15
What about this one? https://immersive-web.github.io/webvr-polyfill/examples/

**Comment by azmartone** [comment] 2018-09-20 00:14
So what does that mean that the webvr-polyfill examples are working?

**Comment by nnittoori** [comment] 2018-10-07 14:09
> @dmarcos One more thing if I host a scene locally on http server it works fine but if I change it to https I need to drag to interact with it.

I am facing the same problem as well. Runs on my local on a Http Server but when it's deployed to https server, I have to drag it to interact with it. I had to touch it once after the scene loads to enable Gyroscope in Android Chrome v69

**Comment by ngokevin** [comment] 2018-11-13 08:47
dupe: https://github.com/aframevr/aframe/issues/3411

**Closed by ngokevin** 2018-11-13 08:47 UTC
