### ISSUE TITLE
App crashes at uniforms.fogColor.value.copy( fog.color );  when uniforms.fogColor.value is null

### ISSUE THREAD

**Issue by LoriKougiou** [aframevr/aframe#4671] opened 2020-08-31 12:23 UTC
**Description:**
I have written an web game-application with a-frame and I'm using -among others - the aframe environment component . 
When rendering an entity that includes the aframe environment component  my app crashes and I get the following error: 
![Capture](https://user-images.githubusercontent.com/44337997/91718596-58796e00-eb9c-11ea-8fe9-5a2c4c64e49a.PNG)

This issue is resolved if I change the following line in aframe-master.js (line 32470)
`uniforms.fogColor.value.copy( fog.color );`
with this 
`if ( uniforms.fogColor.value ) uniforms.fogColor.value.copy( fog.color );`

But that way the error will not be fixed permanently since it will be reproduced everytime someone reinstalls the npm packages. Can somebody help me fix this? 

- A-Frame Version:  1.0.4
- Platform / Device: Google Chrome on Windows 10 Desktop
- Reproducible Code Snippet or URL:

**Comment by dmarcos** [comment] 2020-08-31 16:28
Simple example to reproduce? [glitch is great](https://glitch.com/~aframe)

**Comment by LoriKougiou** [comment] 2020-08-31 17:15
@dmarcos Thanks for your reply!
I actually did manage to reproduce the error here [(glitch)](https://glitch.com/~env-comp-test) , but I realized it's coming from a different component, the particle system component, since the app works just fine after I remove the latter from the environment entity. I quickly found that a newer version of the component called [aframe-particle-system-component-fog-fix](https://www.npmjs.com/package/aframe-particle-system-component-fog-fix) has been released, which supposedly exposes only a subset of the ShaderParticleEngine API. I had not made the switch, but after uninstalling the old one and installing the new, nothing changed.

**Comment by dmarcos** [comment] 2020-08-31 23:31
Best is to contact the [aframe-particule-system-component](https://github.com/IdeaSpaceVR/aframe-particle-system-component/issues/55) maintainers. I'm not familiarized with their code base.

**Comment by LoriKougiou** [comment] 2020-09-01 08:55
You are right, thank you, will do!

**Comment by dmarcos** [comment] 2020-10-23 21:03
Closing this since there's nothing actionable on A-Frame side. Issue has to be addressed on [aframe-particule-system-component](https://github.com/IdeaSpaceVR/aframe-particle-system-component/issues/55)

**Closed by dmarcos** 2020-10-23 21:03 UTC
