### ISSUE TITLE
aframe is causing images to shake rapidly (see the video attached) 

### ISSUE THREAD

**Issue by Fede-viale** [aframevr/aframe#5036] opened 2022-04-07 14:02 UTC
On Android devices, across all browsers, some aframe examples shake like crazy at the smallest movement. We experimented this issue even when the mobile devices were totally still.

- A-Frame Version: 1.1.0 
- Platform / Device: Android (all, but tested on One Plus 5, Xiaomi Redmi Note 9 Pro, Pixel 1, Galaxy S10 , Galaxy S20)
- Reproducible Code Snippet or URL:  attached video to reproduce the issue.
 

https://user-images.githubusercontent.com/98468287/162217230-3a385be8-b0d9-455a-97af-fb1c5649f794.mp4

**Comment by dmarcos** [comment] 2022-04-08 15:52
It could be sensor resetting / drift. I don’t think much can be done on the A-Frame side.

It doesn’t seem to be affecting normal operation right once you grab the phone in your hand, correct?

**Comment by Fede-viale** [comment] 2022-04-08 16:28
when you grab the phone in your hand it's almost imperceptible to see. But if you looking for it, you'll see it. 

Are you sure there is nothing to do on A-Frame side?

**Comment by dmarcos** [comment] 2022-04-08 16:29
FWIW I cannot reproduce the issue on a Pixel 3 and the examples on the site 

https://aframe.io/aframe/examples/

I noticed the report is files against 1.1.0. You should be using 1.3.0

**Comment by Fede-viale** [comment] 2022-04-08 16:44
When we tested we used the example in the following link -> https://aframe.io/examples/showcase/sky/ 

We opened the link using chrome 100 and the only thing we did was opened the link in the browser. 

We're tetsing right now in a Samsung Galaxy S10 now on Chrome 100. The result is the same. The experience shakes.

**Comment by dmarcos** [comment] 2022-04-08 16:45
Is the experience functional? you mention noise is imperceptible on normal operation right?

**Comment by Fede-viale** [comment] 2022-04-08 16:52
Yes, It's imperceptible when you're on movement. but, if you pay attention you could see it anyway!

**Comment by dmarcos** [comment] 2022-04-08 16:59
Thanks. By functional I mean a user will be able to use the experience without issue or discomfort.

**Comment by dmarcos** [comment] 2022-04-08 17:12
This is probably not a super high priority. The tracking logic is here:

https://github.com/aframevr/aframe/blob/master/vendor/DeviceOrientationControls.js

You’re welcome to have a look and explore solutions. Maybe implementing some kind of filter is possible to eliminate noise.

**Comment by dmarcos** [comment] 2022-04-08 17:17
Some filter code could be useful as starting point:

https://github.com/immersive-web/cardboard-vr-display/blob/main/src/sensor-fusion/complementary-filter.js

**Comment by dmarcos** [comment] 2022-04-11 02:03
Some interesting reference https://stackoverflow.com/questions/25744984/implement-a-kalman-filter-to-smooth-data-from-deviceorientation-api

**Comment by dmarcos** [comment] 2022-11-21 01:28
I'm not sure we can do much on the A-Frame side. This doesn't affect normal operation. I'm open to suggestions if someone has more insight and ways to improve. I'm closing for now and can reopen if necessary

**Closed by dmarcos** 2022-11-21 01:28 UTC
