### ISSUE TITLE
OBJ model won't load

### ISSUE THREAD

**Issue by nikolas7892** [aframevr/aframe#2222] opened 2016-12-28 03:11 UTC
So I'm trying to simply load a obj model and a material to a basic <a-scene> ... It is a 3d model at the following dimension ( 19.2 MB (20,156,958 bytes)) ... Is it too big for the scene? 

- A-Frame Version:
0.4.0

- Platform/Device:

web

- Reproducible Code Snippet or Demo URL [highly encouraged]:

<html>

<head>

<script src="https://aframe.io/releases/0.4.0/aframe.min.js"></script>

</head>
<body>
<a-scene>
  <a-assets>
    <a-asset-item id="crate-obj" src="model_mesh.obj"></a-asset-item>
    <a-asset-item id="crate-mtl" src="model_mesh.obj.mtl"></a-asset-item>
  </a-assets>
</a-scene>
</body>
</html>

**Comment by mkungla** [comment] 2017-01-01 02:38
Can you describe your problem more precisely, are your `headers` accept loading this issue can we reproduce that? Perhaps you should post it to stackoverflow instead...

**Comment by donmccurdy** [comment] 2017-01-01 19:21
20mb is not too large. The problem is likely something invalid in the model itself, or use of some feature that THREE.OBJLoader doesn't support yet. Usually it's the first. [Here](https://github.com/mrdoob/three.js/issues?utf8=%E2%9C%93&q=is%3Aissue%20objloader) are some examples of others' issues with the OBJ format.

To debug what's going on, you'll want to look at the JS Console and include that output with any bug reports. If that doesn't work, we'll need to see the model, preferably in a live demo, to be able to help.

***

Meta: I'm not sure if SO will take questions along these lines, since it's just about impossible to differentiate  between questions of the form "my model doesn't work" until you open the black box of the file itself. Maybe we could add a paragraph to [Why does my asset not load](https://aframe.io/docs/0.4.0/introduction/faq.html#why-does-my-asset-e-g-image-video-model-not-load) explaining specifically how to debug a model that isn't rendering.

In the meantime, I'd vote to close this issue until there's a bit more information.

**Comment by dmarcos** [comment] 2017-05-12 00:10
@nikolas7892 I'm going to close this issue. Please reopen if you can provide additional info

**Closed by dmarcos** 2017-05-12 00:10 UTC
Labels: needs answers / feedback
