### ISSUE TITLE
Safari iOS: On fullscreen get "undefined is not an object (evaluating 'e.display.isPresenting')"

### ISSUE THREAD

**Issue by studiouniverse** [aframevr/aframe#2849] opened 2017-07-06 19:46 UTC
On enter fullscreen (when tapping fullscreen-goggle-button) get "undefined is not an object (evaluating 'e.display.isPresenting')" when using Safari iOS.

The VR continues to work, but rotating the phone back to portrait does not clear the Aframe dual-vision VR mode until page refresh.

```
aframe-master.min.js:303:4802
a-scene.js:309
TypeError: undefined is not an object (evaluating 'e.display.isPresenting')
```

- A-Frame Version: 0.6.0
- Platform / Device: iPhone 7 iOS 10.3.1 Safari
- Reproducible Code Snippet or URL: http://aframe.io (first demo that comes up), also tested on personal code using https://aframe.io/releases/0.6.0/aframe.min.js

**Comment by jaredpike** [comment] 2017-07-22 18:57
The console error seems unrelated to the issue. But to fix it, line 309 in `src/core/scene/a-scene.js` should be `evt.detail.display.isPresenting`.

**Comment by dmarcos** [comment] 2020-10-26 23:07
Closing because no longer reproduces in newer versions of A-Frame / iOS.

**Closed by dmarcos** 2020-10-26 23:07 UTC
Labels: mobile
