### ISSUE TITLE
trackpadtouchstart event for oculus browser isn't working

### ISSUE THREAD

**Issue by ifanjuang** [aframevr/aframe#4461] opened 2020-02-15 09:28 UTC
Hello dmarco, first, i want to thank you for developping and sharing this wonderfull tool!
i got some issue trying developping a simple webapp using oculus go:
trackpadtouchstart and trackpadtouchend events doesn't detect on oculus browser release 8.0.5.197835181 for oculus go.
would you please check the issue? thank you again. and have a nice day.

- A-Frame Version: 1.0.4
- Platform / Device: oculusgo / oculus browser 8.0.5.197835181
- Reproducible Code Snippet or URL:
AFRAME.registerComponent('controller', {
init: function () {
this.el.addEventListener('trackpadtouchstart', function (evt) {
evt.stopPropagation();
document.querySelectorAll(".link").forEach(function(el) {
el.object3D.visible = true;
});
<...>
<a-entity id="controller" controller
tracked-controls="controller: 0; idPrefix: OpenVR"
oculus-go-controls="hand: right"
daydream-controls="hand: right"
laser-controls="hand: right"
line="color: white; opacity: 0.5"
raycaster="objects:.link; far: 50"
</a-entity>

**Comment by dmarcos** [comment] 2020-02-24 16:02
It needs link to reproduce

**Comment by dmarcos** [comment] 2020-10-23 23:12
Closing due to lack of link to reproduce and probably not applicable. Notice that the [Oculus touch controllers](https://aframe.io/docs/1.0.0/components/oculus-touch-controls.html#events) don't have a trackpad and the event is not expected to fire.

**Closed by dmarcos** 2020-10-23 23:12 UTC
