### ISSUE TITLE
Orientation bug in Android 4.4.4 webkit browser...

### ISSUE THREAD

**Issue by michael829** [aframevr/aframe#1645] opened 2016-07-21 16:10 UTC
**Description:**

Today when i test demo on https://github.com/aframevr/awesome-aframe, I found that all the components's demo in my phone are bad!  This is big trouble becase last time in a month ago them are very well!
Now, I test the example in https://aframe.io/examples/ , also bad!
what happen?? when i put my phone horizontal, and click webVR button into VR mode, the screen's orientation is displays vertically.. I mean that screen split in two pictures in horizontal, but every picture displayed vertically, and DeviceMotionEvent also works bad!

the error is like this:
![wrong_01](https://cloud.githubusercontent.com/assets/9690703/17029900/c03e1cb8-4f9f-11e6-8223-57137300e9ec.jpg)

![wrong_02](https://cloud.githubusercontent.com/assets/9690703/17029523/1a745ef6-4f9e-11e6-8ef1-52f583e2a508.jpg)

In fact the right result should be like this:
![right_01](https://cloud.githubusercontent.com/assets/9690703/17029530/1cb28ecc-4f9e-11e6-8b67-b5576bf63d4f.jpg)

![right_02](https://cloud.githubusercontent.com/assets/9690703/17029921/dafb6cc2-4f9f-11e6-84e5-111402698fb9.jpg)

I have some test, and find that if I put my phone horizontal before the web complete! then it works fine in horizontal, but i can't rotate my phone to vertically, becase the problem will happen again! if I put my phone horizontal after the web complete, it works bad with wrong orientation!!

er.....someone understand????? this bug not happen in iphone's safari!~

- A-Frame Version: Latest version
- Platform/Device: Android 4.4.0 Sumsung Galaxy Note2 N7100

**Comment by dmarcos** [comment] 2016-07-21 16:57
It seems that is a problem of your specific device and the DeviceMotion API right? The examples in the website have not changed in the last month

**Comment by michael829** [comment] 2016-07-22 02:54
oh no...not just my device... I have test  some other device ....and all bad! so.. is the file "https://aframe.io/aframe/dist/aframe.js" or file "https://aframe.io/aframe/dist/aframe.min.js" had modified??? 
And i have test some other example at "https://github.com/aframevr/awesome-aframe", I find some example use other file address like "http://drawvr.com/tron/aframe.min.js"..the problem also happen...so I don't know if the last version have the problem or the bug always exist... (in fact i remember last test the demos are fine in one or two month ago! but now i'm not sure!!  ~~(*.*)~~~)

Thanks for reply..... please Identify the problem. in Android device, chrome..version?? er... my device's chrome version is 51...other device's version unknow. But the examples all rendered well!!

step:
1. put your android device vertically and visit examples at https://aframe.io/examples/showcase/anime-UI/ or other website.
2. when the webpage load complete, click "vr mode" button.
3. put your device horizontal!  <== running bad! two pictures split along Xaxis but every picture's orientation along Yaxis...

**Comment by mkungla** [comment] 2016-07-22 09:50
@michael829 
> oh no...not just my device... I have test some other device ....and all bad!

can you post 
1. Android Versions
2. Which mobile browser
you tested and have this problem. 

@dmarcos I can reproduce  this on Android 4.4.4 browsers with WebKit engine, Firefox works still fine.
So probably problem is coming from some latest updates for android 4.x. Since when I now powered up my testing (also Samsung) phone, it  made lot of updates including "Android System updates" and both Android Browser and Chrome got updated and indeed after these updates seems that orientation is messed up on all WebKit browsers, while it was working before just fine. Definitely worth investigating since this problem now persists on `master`.

**Comment by michael829** [comment] 2016-07-22 11:42
oh Thanks god...!~  this problem are happen to Android webkit browser....my tested device are android and browser are webkit browser... no firefox..you know, most people are use webkit browser... so I didn't expect it works fine on Firefox and have no test on Firefox... so sorry...

And.. I have't update my device since last june....my Android version is Android 4.4.4...Chrome version is 51.0.2704.81 ...

Thank you for reply...very thank you!~

**Comment by mkungla** [comment] 2016-08-04 00:48
@dmarcos this can be closed. Just tested again with same device and this is fixed in master.

**Comment by dmarcos** [comment] 2016-08-04 01:04
@mkungla thanks for checking. @michael829 please reopen if this is still a problem

**Closed by dmarcos** 2016-08-04 01:04 UTC
