### ISSUE TITLE
Missing support for non-screen generic WebXR input sources

### ISSUE THREAD

**Issue by fordacious** [aframevr/aframe#4769] opened 2021-01-13 05:28 UTC
Currently there is support for WebXR screen select events, but no support for non-screen generic input sources. This could be constructed as a basic input source with specializations built on top of it (e.g. vive, oculus, wmr etc...)

**Comment by dmarcos** [comment] 2021-01-13 11:14
Thanks for filing. Not sure what the issue is. A-Frame comes with built-in support for all [headset controllers](https://aframe.io/docs/1.1.0/introduction/interactions-and-controllers.html#sidebar). Can you elaborate your particular use case?

**Comment by fordacious** [comment] 2021-01-13 16:54
Say I create a WebXR app and want to be able to receive input from all WebXR controllers / input sources (even unnamed or custom devices without known input profiles). In WebXR you would simply detect input sources, read their locations, which hand they are on, and detect select events from sources. This will work with all current and future input sources as this is the standard. In A-Frame, as far as I can tell, there is no way to do this.

**Comment by fordacious** [comment] 2021-01-13 16:58
My particular use-case is that I'm trying to get moonrider playable with hand tracking, which would require no modification were generic input sources supported ;)

**Comment by dmarcos** [comment] 2021-01-13 19:15
> 
> 
> Say I create a WebXR app and want to be able to receive input from all WebXR controllers / input sources (even unnamed or custom devices without known input profiles). In WebXR you would simply detect input sources, read their locations, which hand they are on, and detect select events from sources. This will work with all current and future input sources as this is the standard. In A-Frame, as far as I can tell, there is no way to do this.

That's what [laser-controls](https://aframe.io/docs/1.1.0/components/laser-controls.html#sidebar) is for. Implementing your own is easy. Add all the controllers you want to support as [laser controls do](https://github.com/aframevr/aframe/blob/master/src/components/laser-controls.js#L19). If a controller is not detected it will fall back to the generic one. Future controllers need dedicated components to present the correct model and define button mappings or they will be presented as generic.

**Comment by dmarcos** [comment] 2021-01-13 19:29
> 
> 
> My particular use-case is that I'm trying to get moonrider playable with hand tracking, which would require no modification were generic input sources supported ;)
> 
> But this applies to any a-frame app which requires no more input than pointing and clicking, OR can be progressively enhanced based on input modality.

You can do it by adding [hand-tracking-controls](https://github.com/aframevr/aframe/blob/master/src/components/hand-tracking-controls.js) to the [controller component](https://github.com/supermedium/moonrider/blob/4bd2e75ff5dd0df3ccda8806e8809e6c8b617aab/src/components/controller.js#L28).

This is personal opinion. Moonrider with hand-tracking might not be a great experience due to latency, oclussion and limited field of view where the hands are tracked.

I'm closing this because I don't think there's anything actionable on the A-Frame side. Looking forward to seeing what you make. For further questions you're more than welcome to use the [discord or slack servers](https://aframe.io/community/)

**Closed** 2021-01-13 19:32 UTC

**Comment by fordacious** [comment] 2021-01-13 19:58
Hand tracking in this case is not joint tracking specifically, simply generic hand location tracking with selection events (which devices like Quest and HoloLens wire up to).

I'll give the lase-controls a shot and see if it addresses the issue.

**Comment by dmarcos** [comment] 2021-01-13 20:36
> 
> 
> Hand tracking in this case is not joint tracking specifically, simply generic hand location tracking with selection events (which devices like Quest and HoloLens wire up to).
> 
> I'll give the lase-controls a shot and see if it addresses the issue. Does the generic fallback (and thus laser-controls) respond to WebXR onSelect events, or does it use the gamepad API?

`generic-tracked-controller-controls` relies on the [generic webx input profile](https://github.com/immersive-web/webxr-input-profiles/tree/master/packages/registry/profiles/generic) reading input from the associated gamepad. The `selectstart` / `selectend` are ignored as they're redundant.

The built-in [hand-tracking-controls component](https://aframe.io/docs/1.1.0/components/hand-tracking-controls.html#sidebar) has logic to detect pinch gestures based on the joint poses emitting the `pinchstarted` and `pinchended` events. 

As [per spec](https://www.w3.org/TR/webxr-hand-input-1/#physical-hand-input-source) we should rely on the [generic-hand-select](https://github.com/immersive-web/webxr-input-profiles/blob/master/packages/registry/profiles/generic/generic-hand-select.json) profile. A-Frame would read input from the first button of the gamepad as described in the profile. Not sure if that's exposed in the Oculus browser at the moment. I would have to check. We can accommodate implementation.

**Comment by fordacious** [comment] 2021-01-13 20:48
Hand profiles and generic profiles are not exposed as gamepads. Hence this will never work.

**Comment by dmarcos** [comment] 2021-01-13 20:50
@fordacious [generic-hand-select profile](https://github.com/immersive-web/webxr-input-profiles/blob/master/packages/registry/profiles/generic/generic-hand-select.json#L13) exposes a gamepad with a single button. Is that a mistake?

**Comment by fordacious** [comment] 2021-01-13 20:53
Ah interesting. That looks like it might actually be a mistake in the side of the current browser implementation in that case!

**Comment by fordacious** [comment] 2021-01-13 20:53
The issue still stands for [generic-button](https://github.com/immersive-web/webxr-input-profiles/blob/master/packages/registry/profiles/generic/generic-button.json) btw which does not have a gamepad mapping

**Comment by dmarcos** [comment] 2021-01-13 20:55
I also see a gamepad defined for [generic-button](https://github.com/immersive-web/webxr-input-profiles/blob/master/packages/registry/profiles/generic/generic-button.json#L13)

**Comment by fordacious** [comment] 2021-01-13 21:20
ok thanks for the help. Looks like what is currently encoded in Chromium might not match the input profiles repo. I'm going to consult with Chromium people and see if it is a mistake there. If so I can make the fix in the browser.

**Comment by dmarcos** [comment] 2021-01-13 21:23
Awesome, thanks so much for helping. Let me know if there's anything we need to adjust on the A-Frame side.

**Comment by fordacious** [comment] 2021-01-13 22:18
According to the (WebXR gamepads spec)[https://immersive-web.github.io/webxr-gamepads-module/#xrinputsource-interface] these input profiles should not have gamepads exposed.

> The gamepad attribute is a Gamepad that describes the state of any buttons and axes on the XR input source. If the XR input source does not have at least one of the following properties, the gamepad attribute MUST be null:

- A single button and a gripSpace
- More than one button
- One or more axes

In this case, hands (and other input sources) will lack gamepad objects.

In the case of hands, only the first condition is met, which is sufficient for tracking and onSelect events but not gamepad.

**Comment by fordacious** [comment] 2021-01-13 23:03
On consulting with Chromium developers, we came to the conclusion that there are cases where the gamepad must NOT have a value, there is no case where the gamepad MUST have a value. Hence the decision to not for hands or generic-button to not have gamepads

**Comment by dmarcos** [comment] 2021-01-13 23:39
@fordacious Are there going to be other hand profiles besides (generic-hands-profile)[https://github.com/immersive-web/webxr-input-profiles/blob/master/packages/registry/profiles/generic/generic-hand-select.json#L13]?

No other input is going to be provided by the browser besides `selectstart / selectend` events? Is it going to be up to content to infer other gestures from joints? In the case of Hololens there were taps, pinches, bloom... How are those going to be exposed to WebXR?

**Comment by fordacious** [comment] 2021-01-14 01:07
There is already generic-hand-select-grasp, expose gestures through the gamepad API. I will be submitting a patch to have it expose the gamepad correctly.

As for other gestures, there may be more hand related input profiles. The general trend seems to be to determine gestures from tracked joints. 

But yeah, in conclusion, there may not be gamepad for input sources so it would be good to respond to select events if there is no gamepad. I'll add gamepad to generic-hand-select-grasp which requires is but it is missing.
