### ISSUE TITLE
glTF v2.0 model disappears and fails to animate with play-all-model-animations component

### ISSUE THREAD

**Issue by stephenrobertsuk** [aframevr/aframe#3036] opened 2017-09-09 22:13 UTC
I am able to load a static glTF (v2.0), but when `play-all-model-animations` component is applied, the geometry no longer renders and the console fills with:

```
THREE.Matrix3: .getInverse() can't invert matrix, determinant is 0
```

The glTF v2.0 model I am using is a simple cube rotating, scaling, and translating - exported from blender with embedded buffers using [KhronosGroup glfTF-Blender-Exporter](https://github.com/KhronosGroup/glTF-Blender-Exporter) master (5ffd6ef). If not a bug with the animations component in aframe, could be one with the exporter, or the three.js gltf loader itself.

I have also investigated that the glTF _does_ render in [babylonjs sandbox](http://sandbox.babylonjs.com/), but not in [threejs viewer](https://gltf-viewer.donmccurdy.com/).

- A-Frame Version: current master clone (dist/aframe-master.js - 0cceca4) 
- Platform / Device:  Latest Official Chrome - Version 60.0.3112.113 (Official Build) (64-bit)/ MacOSX Sierra 10.12.6
- Reproducible Code Snippet or URL: (**Codepen**): 

https://codepen.io/stephenrobertsuk/pen/qXePxd

cube glTF: https://s3.amazonaws.com/bug-figures/v2-locrotscale-cube-embedded-buffers.gltf

**Comment by donmccurdy** [comment] 2017-09-09 22:18
Thanks for the details! 

I can [reproduce the problem in three.js too](https://gltf-viewer.donmccurdy.com/#model=https://s3.amazonaws.com/bug-figures/v2-locrotscale-cube-embedded-buffers.gltf), so it's not specific to A-Frame. Might be THREE.GLTFLoader, or might be the exporter... will try to figure out what's going on and report back.

Also, could you include the `.blend` file?

**Comment by stephenrobertsuk** [comment] 2017-09-09 22:24
Sure:
https://s3.amazonaws.com/bug-figures/cube.blend
Blender Version 2.79 (2.79 2017-09-04)

**Comment by donmccurdy** [comment] 2017-09-10 03:57
One observation, if the interpolation mode in Blender is changed to "linear", the animation plays normally. There seems to be some issue in THREE.GLTFLoader with playing cubicspline animation.

[cube_linear.zip](https://github.com/aframevr/aframe/files/1290245/cube_linear.zip)

**Comment by donmccurdy** [comment] 2017-09-10 04:54
I think we THREE.GLTFLoader is not interpreting cubic spline output values [according to the spec](https://github.com/KhronosGroup/glTF/blob/master/specification/2.0/README.md#appendix-c-spline-interpolation).

The output data looks like this for the `scale` channel, where each keyframe is a 9-float set.

```
[0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1.0448137521743774, 1.0448137521743774, 1.0448137521743774, 0, 0, 0, 0, 0, 0, 1.0448137521743774, 1.0448137521743774, 1.0448137521743774, 0, 0, 0, 0, 0, 0, 1.0448137521743774, 1.0448137521743774, 1.0448137521743774, 0, 0, 0 ]
```

Based on the error being thrown, three.js has interpreted this to give scales of `0 0 0`, which creates a degenerate matrix. There may be some conversion necessary, within GLTFLoader, to format the keyframes in the way that three.js expects.

@takahirox I noticed https://github.com/mrdoob/three.js/pull/10032; is this something you are familiar with from working with MMD?

**Comment by donmccurdy** [comment] 2017-09-20 14:42
Filed https://github.com/mrdoob/three.js/issues/12233, as this issue is really in GLTFLoader, and closing the issue here.

**Closed by donmccurdy** 2017-09-20 14:42 UTC
