### ISSUE TITLE
VR appears broken for iOS devices. Tested on iPad/iPhone. Confirmed on example at aframe.io

### ISSUE THREAD

**Issue by dlipats** [aframevr/aframe#4929] opened 2021-09-11 03:25 UTC
1. Visit the 360 (sky) example at https://aframe.io/examples/showcase/sky/ with an iPad or iPhone using Safari.
2. Press the VR button in the lower right corner.
3. The screen should split in to two. Everything looks OK at first.
4. Rotate the device 360*. At about a 90* angle both left/right cameras turn white. This is unrecoverable. There is no way to rotate over 90* in any direction without the screens turning white.

iPad Debugging at https://aframe.io/examples/showcase/sky/ shows 262 webgl/shader errors. Output attached.

- A-Frame Version: 1.2.0
- Platform / Device: iPhone / iPad
- Reproducible Code Snippet or URL: https://aframe.io/examples/showcase/sky/

[Console.txt](https://github.com/aframevr/aframe/files/7147138/Console.txt)

No rendering issue with Android.

**Comment by kylebakerio** [comment] 2021-09-19 13:33
https://github.com/aframevr/aframe/issues/4814

**Comment by ephb** [comment] 2021-09-24 19:08
@kylebakerio this is not related as the rendering breaks on iPhone as well. Confirmed with Safari 15, iOS 15 on iPhone 12 Pro.

There seem to be a few problems with threejs shaders in Safari 15 on Metal.

[Aframe particle system is also affected](https://github.com/IdeaSpaceVR/aframe-particle-system-component/issues/61#issue-1006651073)

**Comment by kylebakerio** [comment] 2021-09-24 19:36
Might be the same as this? https://aframevr.slack.com/archives/C0GG937RN/p1632419833000600

**Comment by ephb** [comment] 2021-09-24 19:44
Do you have a working link for the A-Frame slack invite? Unfortunately I cant access it and https://aframe.io/slack-invite/ seems to be broken.

**Comment by kylebakerio** [comment] 2021-09-25 10:05
https://join.slack.com/t/aframevr/shared_invite/zt-f6rne3ly-ekVaBU~Xu~fsZHXr56jacQ

**Comment by kylebakerio** [comment] 2021-09-27 11:06
https://aframevr.slack.com/archives/C0GG937RN/p1632729229007400

**Comment by ephb** [comment] 2021-12-01 21:57
Still broken on iOS 15.2. I tested again since another issues disappeared with 15.2.

**Comment by vincentfretin** [comment] 2022-09-10 16:53
See #5102 that will fix the VR cardboard on iPhone.

**Comment by dmarcos** [comment] 2022-11-19 03:16
This should be fixed on master? Can anyone verify?

**Comment by vincentfretin** [comment] 2022-12-02 12:30
I tested it in an example here https://github.com/n5ro/aframe-extras/issues/383#issuecomment-1335159873
on the iPad 16.1.1 with mobile version selected in address bar, I see the stereo rendering. If you have the page in desktop version (the default), it just render black.
So yeah I guess it's fixed? See also my comment https://github.com/aframevr/aframe/issues/4814#issuecomment-1335154961

**Comment by dmarcos** [comment] 2023-11-14 10:40
We have now deprecated cardboard mode. Closing this but can reopen if necessary

**Closed by dmarcos** 2023-11-14 10:40 UTC
