### ISSUE TITLE
click/ray cast  issue

### ISSUE THREAD

**Issue by lijualivenow** [aframevr/aframe#4648] opened 2020-07-23 02:43 UTC
I found tap/ray cast issue on 1.0.4, 1.0.3 versions, but perfectly detecting on 0.9.2. If objects are very small, difficult tap. Here is code

```
  <a-camera
    id="camera"
    position="0 8 8"
    raycaster="objects: .cantap"
    cursor="
      fuse: false;
      rayOrigin: mouse;">
  </a-camera>
```

```
dragon.addEventListener('click', function (e) { 
         //console.log('dragon click '); 
          OnClickDragon(e.target);
        });
```

- A-Frame Version: 1.0.4, 1.0.3
- Platform / Device:  Android (Chrome , Firefox) (8th wall)

**Comment by dmarcos** [comment] 2020-07-23 16:52
Without link to reproduce it will be hard to investigate. Can you reproduce without 8th Wall?

**Comment by dmarcos** [comment] 2020-10-21 22:51
Closing due to lack of code to reproduce. We can reopen if more info becomes available.

**Closed by dmarcos** 2020-10-21 22:51 UTC
