### ISSUE TITLE
core:a-entity:warn Tried to remove `Object3D` of type:  mesh which was not defined.

### ISSUE THREAD

**Issue by asandersSAP** [aframevr/aframe#4139] opened 2019-04-25 09:26 UTC
**Description:**
On every entity loaded into the scene I get a console warning: 
`core:a-entity:warn Tried to remove `Object3D` of type:  mesh which was not defined.  aframe.min.js:23:633`

which is a mess with multiple entities. May you check? maybe it's just a small fix

Just tell me if you need more information
thanks!

- A-Frame Version:  0.9.1 
- Platform / Device: MacOS, every Browser

**Comment by dmarcos** [comment] 2019-04-25 14:42
If you provide a link with simple case to reproduce we can look into it. Glitch is a good option: https://glitch.com/~aframe

**Comment by dmarcos** [comment] 2020-10-24 00:23
Closing due to lack of link to reproduce

**Closed by dmarcos** 2020-10-24 00:23 UTC

**Comment by wyzwon** [comment] 2023-01-04 22:23
@dmarcos
[Here's my go at what they meant.](https://issue-4139-demo.glitch.me/)

In this example the page uses an obj without a texture and sets a color at object creation. I was actually still getting a warning without the obj loaded as I had given the wrong file link and received a 404 error but the warning still appeared.

**Comment by wyzwon** [comment] 2023-01-18 01:29
Digging into the code a little, I have traced this back to when "update" is called in the 'obj-model' component. Update calls "resetMesh()" which calls "el.removeObject3D('mesh')" which evidently doesn't have a mesh. I don't know enough about this part of the code to know if update ever needs to reset a mesh or if it's safe to remove that line entirely.
