### ISSUE TITLE
Screenshot images differ from the view and transparency of objects increases

### ISSUE THREAD

**Issue by IntraNoctem** [aframevr/aframe#5126] opened 2022-09-27 08:21 UTC
Screenshot results differ from the current view in the following points:
- AspectRatio in embedded scenes
- Sky brightness
- and most interesting: transparency of objects increases

On the left side you see the screenshot png and on the right the scene from the glitch example mentioned below:

![opacity-comparison](https://user-images.githubusercontent.com/57447403/192468895-ba6d16ee-5cee-40cb-9e00-c9ed5b1ce60c.png)

Using a camera clone instead of the default camera solves the aspectRatio and brightness issues in our case, but we found no solution for the transparency. 

- A-Frame Version: 1.3.0
- Platform / Device: Any
- Reproducible Code Snippet or URL: https://glitch.com/edit/#!/bitter-incredible-hunter

**Comment by kylebakerio** [comment] 2022-10-05 20:42
I also experienced this recently.

**Comment by kfarr** [comment] 2022-10-27 02:14
duplicate of https://github.com/aframevr/aframe/issues/5014

**Comment by dmarcos** [comment] 2022-11-19 03:33
Closing as dup of https://github.com/aframevr/aframe/issues/5014

**Closed by dmarcos** 2022-11-19 03:33 UTC
