### ISSUE TITLE
Bug with loading of <a-assets> 

### ISSUE THREAD

**Issue by tomfelder94** [aframevr/aframe#5251] opened 2023-02-23 07:16 UTC
**Description:**

We found a bug in which the loading of images is not correctly handled. Because of this, the loading screen is always waiting until the timeout is fired. I attached a very simple code below, you just need to add a random image ("image.jpg") to reproduce (not reproducible on glitch, image needs to be local).

The issue seems to be in the following part of the a-assets code:

line 47 and following:
``` javascript
// Wait for <img>s.
imgEls = this.querySelectorAll('img');
for (i = 0; i < imgEls.length; i++) {
   imgEl = fixUpMediaElement(imgEls[i]);
   loaded.push(new Promise(function (resolve, reject) {
      // Set in cache because we won't be needing to call three.js loader if we have.
      // a loaded media element.
      THREE.Cache.add(imgEls[i].getAttribute('src'), imgEl);
      imgEl.onload = resolve;
      imgEl.onerror = reject;
   }));
}
```
We are not handling the case if the image has already been loaded, in this case promise is never being resolved. We should use something like the following in the promise:

``` javascript
if (imgEl.complete) {
    resolve();
} 
```

Is this a known issue or are we missing something? I could create a PR for that if you wish.

- A-Frame Version: 1.4.1
- Platform / Device: Chrome, Macbook Pro 2019 (Intel)
- Reproducible Code Snippet or URL:

``` html
<html>
<head>
    <script src="https://aframe.io/releases/1.4.1/aframe.min.js"></script>
</head>
<body>
    <a-scene>
        <a-assets timeout="10000">
            <!-- You got until the count of 10 to load else the show will go on without you. -->
            <img src="image.jpg">
        </a-assets>
        <a-box position="-1 0.5 -3" rotation="0 45 0" color="#4CC3D9"></a-box>
        <a-sphere position="0 1.25 -5" radius="1.25" color="#EF2D5E"></a-sphere>
        <a-cylinder position="1 0.75 -3" radius="0.5" height="1.5" color="#FFC65D"></a-cylinder>
        <a-plane position="0 0 -4" rotation="-90 0 0" width="4" height="4" color="#7BC8A4"></a-plane>
        <a-sky color="#ECECEC"></a-sky>
    </a-scene>
</body>
</html>
```

**Comment by dmarcos** [comment] 2023-02-23 12:57
How is local different? Are you serving your image through a web server? https://aframe.io/docs/1.4.0/introduction/faq.html#why-does-my-asset-e-g-image-video-model-not-load

**Comment by tomfelder94** [comment] 2023-02-23 13:59
It is a matter of network speed and timing, that's why my glitch example was not working, sorry. If the image is small enough/ network fast enough, the image is loaded before we wait on the onload event and therefore causing the issue. I could reproduce it with the following glitch example: https://glitch.com/edit/#!/erratic-like-ocean?path=index.html%3A11%3A19 

It does not happen always but sometimes does (in particular when cache is cleared), as it is a matter of timing.

Can you reproduce?

**Comment by gftruj** [comment] 2023-02-23 20:34
> (in particular when cache is cleared)

Couldn't reproduce with a fiddle, now i see why :D
Happens for me each hard reload on windows chrome / edge, for some reason works on firefox (tried with your [glitch](https://erratic-like-ocean.glitch.me/))

**Comment by dmarcos** [comment] 2023-02-23 21:04
Can you try with a master build: https://cdn.jsdelivr.net/gh/aframevr/aframe@3d281849d480293d10badca644584806c3f4906a/dist/aframe-master.min.js

**Comment by gftruj** [comment] 2023-02-23 21:59
Same, ctrl-F5 (on chrome even the first load) results in a blue screen until `a-assets` timeouts ([remixed glitch](https://glitch.com/edit/#!/aframe-issues-5251-gtj?path=index.html%3A4%3A10), [preview](https://aframe-issues-5251-gtj.glitch.me//) on windows10 chrome / edge)

**Comment by tomfelder94** [comment] 2023-02-24 07:04
I tried with the master build, same issues. The thing that fixes it is if we check if the loading of the image is already complete with something like below

```javascript
if (imgEl.complete) {
    resolve();
} 
```

**Comment by dmarcos** [comment] 2023-02-24 11:34
Thanks! Yeah we can add such line:

```
  if (imgEl.complete) { 
    resolve(); 
    return;
 } 
```

PR welcome.

**Comment by tomfelder94** [comment] 2023-02-24 12:19
Alright, will create a PR

**Comment by dmarcos** [comment] 2023-02-26 12:41
@tomfelder94 thanks so much!

**Comment by tomfelder94** [comment] 2023-02-27 14:26
Created the PR: https://github.com/aframevr/aframe/pull/5252 

Wasn't sure if I was supposed to commit the dist files...

**Comment by dmarcos** [comment] 2023-02-28 13:44
Fixed by https://github.com/aframevr/aframe/issues/5251

**Closed by dmarcos** 2023-02-28 13:44 UTC
