### ISSUE TITLE
a-animation calling setAttribute never update

### ISSUE THREAD

**Issue by aminesysy** [aframevr/aframe#1819] opened 2016-08-18 10:55 UTC
Hi, i tried updating a-animation from, to attributes with `animationEl.setAttribute('to','0 0 1')`
but it never goes right!
after calling aSceneEl.appendChild(animationEl) , it always take the first value and never the updated value
- A-Frame Version:0.3.0
- Platform/Device:Kali Linux 2.0 / Chrome Version 50.0.2661.86 (64-bit)

**Comment by fuleinist** [comment] 2016-08-24 12:34
I am having the same issue and I believe a-animation will not respond to data change via setAttribute.

You can try to use component api to bind an a-animation to the object. which has been explained in https://aframe.io/docs/0.3.0/guides/build-with-components.html

Sample Script:
```
  /**
   * Setup fade-in + fade-out.
   */
  setupFadeAnimation: function () {
    var data = this.data;

    if (data.target.is('set-image-animation-ready')) { return; }

    // Create animation.
    var animation = document.createElement('a-animation');
    var animationData = {
      attribute: 'material.color',
      begin: 'set-image-fade',
      direction: 'alternate',
      dur: data.dur,
      repeat: 1,
      from: 'white',
      to: 'black'
    };
    Object.keys(animationData).forEach(function (attr) {
      animation.setAttribute(attr, animationData[attr]);
    });

    // Append animation.
    data.target.appendChild(animation);
    data.target.addState('set-image-animation-ready');
  }

```

**Comment by ngokevin** [comment] 2016-08-24 18:16
https://github.com/ngokevin/aframe-animation-component might respond to updates

**Comment by eng1neer** [comment] 2017-05-18 16:56
I wonder what is the reason a-animation does not respond to updates? Will this be fixed or is it so by design?

**Comment by ngokevin** [comment] 2017-05-18 18:28
I've been trying to maintain https://github.com/ngokevin/kframe/tree/master/components/animation more, but I haven't fully finished my most recent update.

**Comment by ngokevin** [comment] 2018-04-04 11:37
We've deprecated a-animation. Try https://github.com/ngokevin/kframe/tree/master/components/animation and file issues, and component will be merged in in the future.

The component will respond to updates

**Closed by ngokevin** 2018-04-04 11:37 UTC
