### ISSUE TITLE
Gyroscope problem rotation reset at 0-180 degrees

### ISSUE THREAD

**Issue by AdemKab** [aframevr/aframe#4815] opened 2021-03-03 12:04 UTC
**Description:**

- A-Frame Version: 1.0.4
- Platform / Device: IOS/Android
- Reproducible Code Snippet or URL: https://youtu.be/j9EVPYR8zl8

this is aframe/arjs project 
i have a problem with gyroscope when i tilt the phone up the video rotate 180 degrees and back
any ideas or workarounds will be appreciated

**Comment by dmarcos** [comment] 2021-03-03 15:22
Can you reproduce without ar.js?

**Comment by dmarcos** [comment] 2022-11-21 02:08
This seems a problem introduced by ar.js. I cannot reproduce with a standalone A-Frame example. Closing but can reopen if necessary.

**Closed by dmarcos** 2022-11-21 02:08 UTC
