### ISSUE TITLE
Instructions for cardboard/landscape are missing when entering VR

### ISSUE THREAD

**Issue by masom** [aframevr/aframe#1213] opened 2016-03-21 18:33 UTC
**Description:**
Instructions on rotating the device into landscape / into cardboard are now missing.

- A-Frame Version: master
- Platform/Device: Android, iOS

**Comment by dmarcos** [comment] 2016-03-21 18:41
@cvan Anything in the top of your mind?

**Comment by cvan** [comment] 2016-03-21 21:42
I haven't changed anything here yet. I am in #1132 but haven't touched it. I will investigate though.

**Comment by cvan** [comment] 2016-03-23 01:44
Investigated this a bit and figured out a solution. A slight regression occurred (I think when the code was moved to a component): On iOS, the orientation modal doesn't appear until you rotate to landscape then rotate to portrait again. If the device is in portrait mode when VR mode is entered, the orientation modal doesn't show up. (In A-Frame 0.1.2, this works as expected.)

On Android, the orientation modal never shows up. There's an explicit check for only iOS; that's because it's assumed that iOS is the only mobile platform where the Fullscreen API isn't supported. This is mostly true (except Windows phone; I know, not a big deal here). Anyway, I have a fix for this too.

**Comment by ngokevin** [comment] 2016-03-23 02:00
FWIW, it was working at least until 2 weeks ago https://github.com/aframevr/aframe/pull/1111

**Comment by cvan** [comment] 2016-03-23 02:07
From what I found, it works only when you rotate to landscape immediately after entering VR mode then go back to portrait. Anyway, not sure which commit caused it; I didn't bother bisecting. But I've got a fix on the way, and it addresses a few other edge cases. And a few others, but I'm going to open up separate PRs for those.

**Comment by ngokevin** [comment] 2016-03-23 02:09
Yeah, I think that's always been an issue. https://github.com/aframevr/aframe/issues/879

**Comment by cvan** [comment] 2016-03-23 02:29
> Yeah, I think that's always been an issue. #879

ah, well then this bug is a dupe

**Closed** 2016-03-24 01:00 UTC
Labels: mobile, regression
