### ISSUE TITLE
[hand-controls] VR hands 180 rotation offset Chrome 86

### ISSUE THREAD

**Issue by thedart76** [aframevr/aframe#4718] opened 2020-11-11 22:53 UTC
**Description:**

Apparently, on Chrome version `86.0.4240.198` the VR hands from `hand-controls` have a `180`° rotation offset around the `X` axes.

![vr-hands-180-rotation-offset-chrome-86](https://user-images.githubusercontent.com/30973948/98873591-9cc49c80-2470-11eb-9c0a-d86e21bcbf84.png)

- A-Frame Version:
`1.0.3` and `1.0.4` 

- Platform / Device:
Oculus Rift / Rift S

- Reproducible Code Snippet or URL:
[https://vr-hands-180-rotation-offset-chrome-86.glitch.me/](https://vr-hands-180-rotation-offset-chrome-86.glitch.me/)

**Comment by dmarcos** [comment] 2020-11-12 04:00
Unfortunately I can't test this since [I cannot run WebXR + Rift on any of my machines](https://github.com/aframevr/aframe/issues/4709)

**Comment by GMartigny** [comment] 2020-12-09 19:18
I don't reproduce this issue on a Valve Index (chrome 87, steam VR beta).

**Comment by dmarcos** [comment] 2022-01-07 13:18
I think this issue should be now fixed. Everything should work as expected with A-Frame 1.2.0. We can reopen if necessary

**Closed by dmarcos** 2022-01-07 13:18 UTC
