### ISSUE TITLE
aframe vr model mobile camera has a high delay

### ISSUE THREAD

**Issue by xujunjie21** [aframevr/aframe#4654] opened 2020-07-27 04:02 UTC
**Description:**
In the VR model of aframe, I found that when the screen is rotated on the mobile phone, the image is very slow and the camera has a high delay. At the same time, VR model cannot be used in sumsang

- A-Frame Version: 1.0.4
- Platform / Device: ios 11 / sumsang
- Reproducible Code Snippet or URL:

`      <a-scene  inspector="https://cdn.jsdelivr.net/gh/aframevr/aframe-inspector@master/dist/aframe-inspector.min.js">
         <a-assets>
            <video id="video" ref="video" style="display:none"
                   autoplay loop crossorigin="anonymous" playsinline webkit-playsinline>
               
               <source type="video/mp4"
                       :src="story.play_section.url" />
            </video>
         </a-assets>

         <a-camera ref="camera"  position="0 1.6 0" wasd-controls-enabled="false" arrow-key-rotation look-controls  cursor="rayOrigin: mouse">

            <a-entity video-controls="src:#video;distance:0;size:7.8"  look-at="#camera"></a-entity>

            <a-entity geometry="primitive: plane; height: 4.2; width: 1.5" material="color: #91F3D5" position="-3.6 0.3 -3" seryu-menu>
            </a-entity>
         </a-camera>
         <a-videosphere src="#video" rotation="0 180 0"></a-videosphere>
      </a-scene>`

**Comment by dmarcos** [comment] 2020-07-27 16:59
Do you have a link to simple test case to reproduce?

**Comment by xujunjie21** [comment] 2020-07-29 01:31
> 您是否有指向要复制的简单测试用例的链接？

sry .I run in a local environment and have no external address. It is found that when the mobile phone rotates, there will be a delay of about 1 second under the VR model. After turning the mobile phone, it is obvious that the camera slowly corrects the position

**Comment by dmarcos** [comment] 2020-07-29 01:42
Can you produce a test case on https://glitch.com/~aframe? Without code we can run it's hard to understand the problem and help. I cannot reproduce what you describe on any of the [A-Frame examples](https://aframe.io/aframe/examples/)

**Comment by dmarcos** [comment] 2020-10-23 21:07
Closing due to lack of code to reproduce the issue. We can reopen if more info becomes available.

**Closed by dmarcos** 2020-10-23 21:07 UTC
