### ISSUE TITLE
Samsung S7 Edge distorted VR Mode

### ISSUE THREAD

**Issue by nicolomessina** [aframevr/aframe#3273] opened 2017-12-06 17:48 UTC
I have a problem in how VR mode is generated in A-Frame 0.7.0 in my Samsung Galaxy S7 Edge. It worked good with A-Frame 0.3.2. Now, with A-Frame 0.7.0, it appears in this way:

![32493841-a6199282-c3bf-11e7-87d3-7662c42292f9](https://user-images.githubusercontent.com/15125922/33676441-08512b42-dab6-11e7-9e73-57fcbf8a52f9.png)

- A-Frame Version: 0.7.0
- Platform / Device: Chrome / Samsung S7 Edge
- Reproducible Code Snippet or URL:

**Comment by dmarcos** [comment] 2017-12-06 17:54
Can you describe the issue? I cannot see the problem from the images

**Comment by nicolomessina** [comment] 2017-12-06 17:59
This is correct:
![screenshot_20171206-185515](https://user-images.githubusercontent.com/15125922/33676901-4f55db04-dab7-11e7-9f26-b6760d3eb7fb.png)

This is incorrect:
![screenshot_20171206-185617](https://user-images.githubusercontent.com/15125922/33676902-4f718282-dab7-11e7-9dcc-40b747b723f2.png)

When I put mobile phone inside a cardboard I see everything doubled. Screen is divided in bad way.

**Comment by dmarcos** [comment] 2017-12-06 18:03
This is a duplicate of https://github.com/aframevr/aframe/issues/3223

**Closed by dmarcos** 2017-12-06 18:03 UTC
