### ISSUE TITLE
CORS issue

### ISSUE THREAD

**Issue by sanjay-bhuva** [aframevr/aframe#4145] opened 2019-04-30 21:19 UTC
**Description:**

- A-Frame Version: 0.9.1
- Platform / Device: Chrome/74.0.3

I am facing a situation, where I do not want to add *Origin: www.domain.com* to request header while getting an image using *a-sky* and *a-image*.

For example, in my case - 
```
<!-- is working -->
<img src="image_source">

<!-- CORS error -->
<img src="image_source" crossorigin="anonymous">
```

I tried with below solutions I found but none of them worked.

1. Try to remove crossOrigin from *ImageLoader*
```
if (window.THREE)  {
  window.THREE.ImageLoader.prototype.crossOrigin = ''
}
```

2. Try to set crossOrigin via FileLoader
```
if (window.THREE)  {
  window.THREE.FileLoader.prototype.setRequestHeader('crossOrigin', '')
}
```

3. Use *a-assets* to load image

```
<script src="https://aframe.io/releases/0.9.1/aframe.min.js"></script>

<a-scene>
    <a-assets>
        <img id="sky" src=image_source">
    </a-assets>
    <a-sky src="#sky"></a-sky>
</a-scene>
```

Is there any way to prevent *aframe* to adding *crossOrigin="anonymous"* in header?

**Comment by rich311** [comment] 2019-05-01 16:17
The end behavior is that when aframe is referencing images from an S3-backed CloudFront distribution the crossOrigin sent ends up CloudFront sending a CORS error: 

> Access to image has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

A workaround here is to hard-code an Origin header on the CloudFront origin to override the one sent by aframe, but it would be ideal to control the aframe origin directly to not have to do this hack. Especially since CloudFront only allows one Origin header, which limits your application to one domain.

**Comment by dmarcos** [comment] 2019-05-01 19:13
FWIW in the code above I see syntax errors. It should be `<img>` instead of `<image>` and `crossOrigin` instead of `corrsOrigin`. Can you share a link with a full example to reproduce? glitch.com/~aframe is a good option.

**Comment by sanjay-bhuva** [comment] 2019-05-01 19:29
Edited `image` to `img` @dmarcos in first part of the code examples , but `crossOrigin`  looks good (it's not `corrsOrigin`).

**Comment by dmarcos** [comment] 2019-05-01 19:30
See:

`window.THREE.ImageLoader.prototype.corssOrigin = ''`

**Comment by sanjay-bhuva** [comment] 2019-05-01 19:32
Updated @dmarcos . I will create a demo and will the reproducable example soon.

**Comment by jlavie** [comment] 2019-06-10 22:52
Hello,

Did you find any issue for your problem?
I'm trying to play images from Cloudfront and i have some CORS policy

You can see the problem here
https://codepen.io/petitlardon/pen/ewYpGo

When i'm downloading this image in my project, everything works fine

Many thanks for any help

**Comment by dmarcos** [comment] 2019-06-10 22:59
@jlavie The server that host the images has to be CORS configured. Look for [Cloudfront CORS configuration](https://medium.com/@dmitter/amazon-cloudfront-and-cors-57dd43cdfd30). I'm closing this issue since I don't think there's nothing actionable on the A-Frame side. We can reopen if necessary.

**Closed by dmarcos** 2019-06-10 22:59 UTC
