### ISSUE TITLE
Material attributes related with map doesn't update with setAttribute

### ISSUE THREAD

**Issue by arturitu** [aframevr/aframe#3257] opened 2017-11-27 18:25 UTC
If you try to update offset or repeat parameter of a material don't update correctly.

- A-Frame Version: 0.7.0
- Platform / Device: All
- Reproducible Code Snippet or URL: https://spiffy-pear.glitch.me/

```

        self.el.setAttribute('material', 'offset', {
          x: 0,
          y: 0
        });
        self.el.setAttribute('material', 'repeat', {
          x: 1,
          y: 1
        });

        self.el.setAttribute('material', 'opacity', 1);

        // Remove this code comment to see how it works
        // var material = self.el.object3D.children[0].material;
        // material.map.offset.x = 0;
        // material.map.offset.y = 0;
        // material.map.repeat.x = 1;
        // material.map.repeat.y = 1;

```

**Comment by Vamoss** [comment] 2018-02-01 22:01
Did you find a solultion for this issue?

**Comment by jan-thoma** [comment] 2018-02-13 12:13
Can confirm this issue

**Comment by hurda21** [comment] 2018-03-12 21:21
Having the same issue. Any suggestions?

**Comment by jan-thoma** [comment] 2018-03-19 07:42
I can't find the issue in the source. I wrote a material component from scratch, maybe this helps.

````
AFRAME.registerComponent('mesh-standard-material',
{
    schema:
    {
        /* Shared */

        flatShading: {type: 'boolean', default: false},
        depthTest: {type: 'boolean', default: true},
        depthWrite: {type: 'boolean', default: true},
        wireframe: {type: 'boolean', default: false},
        side: {type: 'string', default: 'front'},
        fog: {type: 'boolean', default: true},
        opacity: {type: 'number', default: 1},

        /* Shader */

        color: {type: 'color', default: '#cccccc'},
        emissive: {type: 'color', default: '#000000'},
        metalness: {type: 'number', default: 0},
        roughness: {type: 'number', default: 0},

        /* Texture */

        map: {type: 'string'},
        mapRepeat: {type: 'vec2', default: {x: 1, y: 1}},
        mapOffset: {type: 'vec2', default: {x: 0, y: 0}},

        /* Normal map */

        normalMap: {type: 'string'},
        normalMapRepeat: {type: 'vec2', default: {x: 1, y: 1}},
        normalMapOffset: {type: 'vec2', default: {x: 0, y: 0}},
        normalScale: {type: 'vec2', default: {x: 1, y: 1}},

        /* displacementMap */

        displacementMap: {type: 'string'},
        displacementScale: {type: 'number', default: 1},
        displacementBias: {type: 'number', default: 0},

        /* EnvMap map */

        envMap: {type: 'string'},
        envMapRefraction: {type: 'boolean', default: false}
    },
    init ()
    {
        this.textureLoader = new THREE.TextureLoader()
        this.material = null
        this.el.addEventListener('model-loaded', () =>
        {
            setTimeout(() =>
            {
                this.createOrUpdateShader({})
            }, 1)
        })
    },
    update (oldData)
    {
        this.createOrUpdateShader(oldData)
    },
    createOrUpdateShader (oldData)
    {
        const newData = AFRAME.utils.diff(oldData, this.data)

        if (!this.material)
        {
            this.material = new THREE.MeshStandardMaterial()
        }

        this.material.flatShading = this.data.flatShading
        this.material.depthTest = this.data.depthTest
        this.material.depthWrite = this.data.depthWrite
        this.material.wireframe = this.data.wireframe

        switch(this.data.side)
        {
            case 'front':
                this.material.side = THREE.FrontSide
                break

            case 'back':
                this.material.side = THREE.BackSide
                break

            case 'double':
                this.material.side = THREE.DoubleSide
                break
        }

        this.material.fog = this.data.fog
        this.material.opacity = this.data.opacity
        this.material.transparent = (this.data.opacity < 1)
        this.material.color = new THREE.Color(this.data.color)
        this.material.emissive = new THREE.Color(this.data.emissive)
        this.material.metalness = this.data.metalness
        this.material.roughness = this.data.roughness
        this.material.normalScale = this.data.normalScale
        this.material.displacementScale = this.data.displacementScale
        this.material.displacementBias = this.data.displacementBias

        this.createOrUpdateMap(newData, 'map')
        this.createOrUpdateMap(newData, 'normalMap')
        this.createOrUpdateMap(newData, 'displacementMap')
        this.createOrUpdateEnvMap(newData)
        this.createOrUpdateMaterial()
    },
    createOrUpdateMap (newData, key)
    {
        if (newData[key])
        {
            const map = this.textureLoader.load(newData[key])
            map.wrapS = THREE.RepeatWrapping
            map.wrapT = THREE.RepeatWrapping
            this.material[key] = map
        }

        if (this.material[key] && !this.data[key])
        {
            this.material[key].dispose()
            this.material[key] = null
        }

        if (newData[key + 'Repeat'] && this.data[key])
        {
            this.material[key].repeat.set(newData[key + 'Repeat'].x, newData[key + 'Repeat'].y)
        }

        if (newData[key + 'Offset'] && this.data[key])
        {
            this.material[key].offset.set(newData[key + 'Offset'].x, newData[key + 'Offset'].y)
        }
    },
    createOrUpdateEnvMap (newData)
    {
        if (newData.envMap)
        {
            const teq = this.textureLoader.load(newData.envMap)
            const seq = THREE.ShaderLib['equirect']
            const meq = new THREE.ShaderMaterial({
                fragmentShader: seq.fragmentShader,
                vertexShader: seq.vertexShader,
                uniforms: seq.uniforms,
                depthWrite: false,
                side: THREE.BackSide
            })

            this.material.envMap = teq
        }

        if (this.data.envMap)
        {
            this.material.envMap.mapping = (this.data.envMapRefraction) ? THREE.EquirectangularRefractionMapping : THREE.EquirectangularReflectionMapping
        }

        if (this.material.envMap && !this.data.envMap)
        {
            this.material.envMap.dispose()
            this.material.envMap = null
        }
    },
    createOrUpdateMaterial ()
    {
        this.el.object3D.traverse((child) =>
        {
            if (child instanceof THREE.Mesh)
            {
                child.material = this.material
                child.material.needsUpdate = true
            }
        })
    }
})
````

**Comment by donmccurdy** [comment] 2018-03-21 03:31
thanks @jan-thoma! The root of the issue is here:

https://github.com/aframevr/aframe/blob/master/src/utils/material.js#L32

^in which we're returning early if the _url_ of a texture map hasn't changed. but I think it will require some reworking to do the right thing.

**Comment by jan-thoma** [comment] 2018-03-21 08:02
I think this also applies to this issue #3387 here too.

**Comment by dmarcos** [comment] 2022-01-10 14:01
Fixed by https://github.com/aframevr/aframe/pull/4985

**Closed by dmarcos** 2022-01-10 14:01 UTC
