### ISSUE TITLE
gyroscope last version chrome 

### ISSUE THREAD

**Issue by Adilmar** [aframevr/aframe#3471] opened 2018-03-18 03:04 UTC
**Description:**

- A-Frame Version: v0.8.0
- Platform / Device: Android
- Reproducible Code Snippet or URL: 

in the last version it does not work

**Comment by timokorkalainen** [comment] 2018-03-21 11:47
When not in VR mode, that is. While in VR, everything works perfectly. The issue is made worse by the look-controls touch mode not allowing vertical rotation, thus making zenith and nadir areas inaccessible on Android devices while not in VR.

**Comment by dancespiele** [comment] 2018-03-22 23:26
In my case, in VR mode in Chrome only the gyroscope works vertically.

**Comment by dmarcos** [comment] 2018-03-22 23:28
That's a known Chrome bug that will be fixed in m66. See https://github.com/aframevr/aframe/issues/3458

**Comment by dmarcos** [comment] 2018-03-22 23:29
Closing as a duplicate.

**Closed by dmarcos** 2018-03-22 23:29 UTC
