### ISSUE TITLE
A-frame Random page reloads/refresh

### ISSUE THREAD

**Issue by CallumMitchellRV** [aframevr/aframe#2782] opened 2017-06-15 16:54 UTC
I've been working on a VR game within A-Frame. When I started testing on devices (iPhone 7/iPhone 7 Plus running Safari, and Samsung Galaxy S6 running Chrome), I began to notice the page would randomly refresh, which is an issue for us, as it restarts the game.

This is happening with the demos on their website, as well as our self-hosted game.

Has anyone experienced this issue, and/or know what the issue or the solution is?

- A-Frame Version: 0.5.0
- Platform / Device: iPhone 7/7 Plus
- Reproducible Code Snippet or URL: [https://aframe.io/examples/hello-metaverse/]

**Comment by dmarcos** [comment] 2017-06-15 17:42
It restarts randomly, while interacting with the scene, in 2D mode, in VR mode?

**Comment by CallumMitchellRV** [comment] 2017-06-16 07:29
It hasn't happened once on a desktop (am I correct in saying that 2D is desktop). We've only had this page refresh issue on devices, most regularly in VR mode. I believed it was an issue on our end, until we started testing on a-frame.io examples, and it happened there too.

**Comment by dmarcos** [comment] 2017-06-16 07:53
I can't reproduce on my iPhone 7 Plus with https://aframe.io/examples/hello-metaverse/.
@CallumMitchellRV Do you think we can close this? Is it still a problem for you?

**Comment by CallumMitchellRV** [comment] 2017-06-16 08:00
We're still very much having this issue on multiple devices on a-frame's own projects. Admittedly, on the iPhone 7 Plus it's less regular than the iPhone 7, sometimes 5 minutes, sometimes 1 minutes. I recommend leaving your phone in the VR mode until it happens. If you notice that i's no longer in VR mode, a page refresh has occurred. 

I'm very much in need of a solution or an explanation to this, so I'm not prepared to close this issue at this point.

**Comment by dmarcos** [comment] 2017-06-16 08:03
@CallumMitchellRV Can you try with master branch and see if it still reproduces?

**Comment by jonnyharper** [comment] 2017-06-16 08:18
Hi, I'm having the same issue. On the basic Hello Web VR example, if I just leave my iPhone sat for a few minutes, I'm booted out of VR mode and the attached logs in console.

![screen shot 2017-06-16 at 09 16 04](https://user-images.githubusercontent.com/2477827/27218114-b1f4f248-5274-11e7-86c4-97fbc68d7006.png)

**Comment by CallumMitchellRV** [comment] 2017-07-03 12:01
So after getting an unminified version of the files, I have found out that there is an issue with the iOSWakeLock function (lines 80195 and 80195 of aframe-master.js from v0.5.0).

	function iOSWakeLock() {
		var timer = null;

		this.request = function() {
			if (!timer) {
				timer = setInterval(function() {
					window.location = window.location;
					setTimeout(window.stop, 0);
				}, 30000);
			}
		}

		this.release = function() {
			if (timer) {
				clearInterval(timer);
				timer = null;
			}
		}
	}

From what I can gather, it is a function to keep the screen from timing out. This has not worked for us and we've had to change phone settings to accomplish this. This also explains why it only occurs on iOS. If anyone can shed any light on why this might be happening that would be great. In the meantime, I've commented this out.

**Comment by cvan** [comment] 2017-07-24 22:29
@CallumMitchellRV thanks for filing this issue. sorry that it's fallen through the cracks. what are your screen-lock settings on your iPhone? the stock, default settings?

**Comment by CallumMitchellRV** [comment] 2017-07-25 07:10
@cvan All of the iPhones with this issue had their display settings set to never auto-lock.

**Comment by klaasman** [comment] 2017-08-02 11:52
I'm experiencing the same issue, after every 30s without interaction in VR-mode, the app will reload itself. I'm on iOS 11.0.

**Comment by prayasht** [comment] 2018-01-25 01:57
Hi 👋 ,

I am currently running into this issue on iPhone X (Safari) and my MacBook Pro Retina 2015 and 2016 (on Google Chrome). The refresh happens exactly 30 seconds after instantiating the app. Steps to reproduce:

- Visit https://aframe.io/examples/hello-metaverse/ via Google Chrome.
- Go into Inspect Mode, and toggle mobile mode. Pick any iPhone model.
- Now wait around 30 seconds, and you will see that the page refreshes.

Same thing is happening when I load my app up in VR mode on my iPhone. The page refreshes exactly after 30 seconds, and there are no logs at the moment it happens to tell me why it's happening. 

Note that the app does NOT refresh if I pull it up on an Android (in VR mode), so this is definitely a problem with iOS.

After digging around some previous issuea and commits, [this line](https://github.com/aframevr/aframe/commit/b4015f545f2de429831b2b25d1f13f33b378db96#diff-d34a955ba8629d299284e4ac5b85579fR50) seems to be the culprit. It sets the `window.location` to `/`, which is what was refreshing the page. I've commented that line out in my production bundle, but I still don't really understand the issue with it.

If anyone can shed some light on this, it would be much appreciated! :)

**Comment by jsantell** [comment] 2018-03-16 20:45
I've uncommonly heard similar reports on using WebVR polyfill and it comes down to the wakelock.

**Comment by moyashipan** [comment] 2018-05-15 13:35
Hi, I'm having the same issue on iOS 11.

However, [NoSleep.js](https://github.com/richtr/NoSleep.js) that similar to wakelock.js of A-frame is successfully working. 😃 
I compared NoSleep.js and wakelock.js, then found the following difference.

### NoSleep.js
It plays the video for iOS 11.
https://github.com/richtr/NoSleep.js/blob/01b379d53cd89c15052b7ab92da319812b7c823b/src/index.js#L3-L7

### wakelock.js of A-frame
It does NOT play the video for iOS 11.
https://github.com/aframevr/aframe/blob/619d57c9a41efe127052897e734322cc67c25e5b/vendor/wakelock/wakelock.js#L67-L68

Does anyone think that replacing with NoSleep.js is a good idea?

**Comment by dmarcos** [comment] 2018-05-15 16:27
Cool @moyashipan. Thanks for verifying

**Closed by dmarcos** 2018-05-15 16:27 UTC
