### ISSUE TITLE
Simple way to prevent animation loop from including "Begin" delay on every iteration?

### ISSUE THREAD

**Issue by softpunch** [aframevr/aframe#1602] opened 2016-07-04 06:23 UTC
**Description:**
I'm guessing this is an intentional feature, 
but it would be _great_ if there were a way to disable it or easily work around it.

The "Begin" property for animations is chained to the actual animation loop.
If Begin is set to "5000", and if the animation is set to loop indefinitely, 
there will be a 5000ms pause between each iteration of the loop.
## 

I think TweenJS addresses this. In addition to allowing "wait" time to be chained into a loop (essentially, the same as "begin"), TweenJS has the option to begin a looped animation "paused" and simply wait to fire it.

Is there a simple way to delay the start of a looped animation in AFrame _without_ incorporating that delay time into every iteration of the loop?

Thanks!
- A-Frame Version: 0.2.0
- Platform/Device: Mac OS 10.11

**Comment by msimpson** [comment] 2016-07-05 13:39
> I think TweenJS addresses this.

Sadly, it does not.

> Is there a simple way to delay the start of a looped animation in AFrame without incorporating that delay time into every iteration of the loop?

Only if you write your own mechanism to replace what is currently used within [`a-animation`](https://github.com/msimpson/aframe/blob/d023bcb88cb5aa22a3d8af25eab591992dfeb0cd/src/core/a-animation.js#L142).

In general, this is a duplicate of #1401. And note: `delay` has been added instead of using `begin` as a delay (in master). Although, `delay` in this case would behave the same and a wait is incurred upon every loop. This is simply how tween.js is written.

**Comment by softpunch** [comment] 2016-07-07 00:33
Ah, I didn't see #1401 when I searched. Sorry bout that. I appreciate the update though!

**Comment by ngokevin** [comment] 2016-07-21 18:03
I can address at https://github.com/ngokevin/aframe-animation-component

**Comment by softpunch** [comment] 2016-07-21 22:12
I've been running setTimeouts to control certain animations as a workaround.
Not ideal.

**Comment by ngokevin** [comment] 2018-04-04 11:35
We've deprecated a-animation. Try https://github.com/ngokevin/kframe/tree/master/components/animation and file issues, and component will be merged in in the future.

The component will not include delay in every iteration. If you want to add delay before each iteration, can control the animation with a bit of JS

**Closed by ngokevin** 2018-04-04 11:35 UTC
