### ISSUE TITLE
360 video is broken

### ISSUE THREAD

**Issue by machenmusik** [aframevr/aframe#3288] opened 2017-12-13 00:39 UTC
https://aframe.io/aframe/examples/boilerplate/360-video/ works.
https://a-frobot.github.io/aframe/examples/boilerplate/360-video/ only shows black.

**Comment by machenmusik** [comment] 2017-12-13 00:41
https://a-frobot.github.io/aframe/examples/test/videosphere/ is also broken and only shows black.

**Comment by mkungla** [comment] 2017-12-13 01:29
duplicate of #3287

**Comment by ngokevin** [comment] 2017-12-13 01:31
Reports that this can be fixed with `material.side` = `back`. Perhaps the negative Z scale thing isn't working out anymore?

**Comment by machenmusik** [comment] 2017-12-13 03:57
@mkungla it's not a duplicate in the sense that text being broken is separate from 360 video being broken, right?  although the root cause may be the same.  @ngokevin hmm, so that isn't great... hadn't seen any reason for that to break with newer three.js?

**Comment by machenmusik** [comment] 2017-12-21 15:00
So what did we decide to do here, change videosphere to use `side:back`, or make negative scale work again?  (If the former, we probably want to note negative scale change as potentially breaking)

**Comment by dmarcos** [comment] 2017-12-21 15:04
We bumped a-frame to r89. Is this still a problem?

**Comment by dmarcos** [comment] 2017-12-21 15:10
Yep, it seems to reproduce on master.

**Comment by machenmusik** [comment] 2017-12-21 15:11
(Sadly, yes)

**Comment by ngokevin** [comment] 2017-12-21 22:44
https://github.com/mrdoob/three.js/pull/12787

You need to try to not use negative scale anymore

**Comment by vincentfretin** [comment] 2018-01-28 10:59
I found this issue when trying to use aframe master on my project.
I confirm the issue is related to mrdoob/three.js#12787
I have lots of the following warnings too:
`
THREE.Matrix4: .getInverse() can't invert matrix, determinant is 0
THREE.Matrix3: .getInverse() can't invert matrix, determinant is 0
`
because of `frontFaceCW` calculation in mrdoob/three.js#12787 (I tested to set it to false and do my own aframe build, the warnings and the black texture issue are gone)

You need `material="side:back; ..."` and a negative scale like scale="-1 1 1" otherwise the texture is flipped. But I still have warnings `.getInverse() can't invert matrix, determinant is 0`.

**Comment by dmarcos** [comment] 2018-01-28 12:28
@vincentfretin Thanks for investigating. It would be great if you have some bandwidth to open a PR with the fix.

**Comment by machenmusik** [comment] 2018-01-28 17:30
My recollection is that changes are needed to `a-sky`, `a-videosphere`, and `a-curvedimage` although I haven't had time yet for PR.  But I haven't seen that matrix error yet

**Comment by vincentfretin** [comment] 2018-01-29 07:45
The matrix warnings are probably related to other entities in my scene, may not be related to a sphere geometry.

**Comment by vincentfretin** [comment] 2018-02-02 15:41
@dmarcos @machenmusik 
https://github.com/aframevr/aframe/pull/3370

**Closed** 2018-02-02 19:07 UTC
Labels: regression
