### ISSUE TITLE
Positional audio stuttering on Oculus Quest 2

### ISSUE THREAD

**Issue by vtrykoz** [aframevr/aframe#4976] opened 2021-12-03 12:16 UTC
**Description:** Experiencing positional sound artefacts (some annoying stuttering/noisiness). It's getting worse as you come closer to sound in vr mode on quest 2. Here's a simplest reproducible code (sound positioned at green sphere): https://vtrykoz.github.io/vraudiotest/
Any ideas how to fix it? If needed I can upload video also.

- A-Frame Version: 1.2.0
- Platform / Device: Oculus Quest 2
- Reproducible Code Snippet or URL: https://vtrykoz.github.io/vraudiotest/

**Comment by dmarcos** [comment] 2021-12-03 21:45
There's an issue reported on THREE that might be related: https://github.com/mrdoob/three.js/issues/22884

**Comment by vtrykoz** [comment] 2021-12-04 07:18
@dmarcos , also this one, looks exactly like currently on A-Frame's side, https://github.com/mrdoob/three.js/issues/20920

**Comment by dmarcos** [comment] 2021-12-04 15:50
https://github.com/mrdoob/three.js/issues/20920 should by fixed in A-Frame 1.2.0

https://github.com/mrdoob/three.js/issues/22884 seems like a new regression

**Comment by vtrykoz** [comment] 2021-12-04 16:19
Will wait for a fix, cause now sound component is practically broken

**Comment by dmarcos** [comment] 2022-01-12 14:55
In master our `super-three` fork should not be affected by https://github.com/mrdoob/three.js/issues/22884. We kept the old matrix decomposition code that https://github.com/mrdoob/three.js/pull/22362 is reintroducing.

If that's the root issue I believe this should be fixed in master. Can anyone confirm? @vtrykoz 

You can find links to latest master builds in the commit message https://github.com/aframevr/aframe/commits/master

This one for example should work: https://cdn.jsdelivr.net/gh/aframevr/aframe@abadfc803609941f29d3db6f96e2b2bddc780d2f/dist/aframe-master.min.js

Thanks everybody for the patience.

**Comment by vtrykoz** [comment] 2022-01-12 16:53
@dmarcos Yes, this one works really good 👍

**Comment by vtrykoz** [comment] 2022-01-12 16:53
https://vtrykoz.github.io/vraudiotest

**Comment by dmarcos** [comment] 2022-01-12 22:41
Awesome, thank you for verifying so quickly.

Closing this since it's fixed on master.

**Closed by dmarcos** 2022-01-12 22:41 UTC
