### ISSUE TITLE
Touch causes "click" to be called twice

### ISSUE THREAD

**Issue by ravisreelalan** [aframevr/aframe#3297] opened 2017-12-14 20:19 UTC
On touch enabled devices, tapping the screen causes the click event to be called twice - once due to a TouchEvent and once due to a MouseEvent. Need a mechanism to fire only 1 event.

click/touch the red sphere in -
http://asc-702-ubuntuvm.main.ad.rit.edu/VR/electrostatics/index.html

Click causes single change of color. Touch causes 2 changes.

**Comment by ngokevin** [comment] 2017-12-14 20:42
Thanks for filing!

**Comment by Kezzsim** [comment] 2018-04-10 23:44
So I don't foresee this being 'fixed' anytime soon, thankfully with a little user patience it can be avoided~

So if you have control over the listener method, like if you register a `cursor-listener` method yourself you can make a boolean globally for the dom's overall click method to have it wait a few seconds before setting that boolean to true and allowing your methods to execute:
```javascript
var isDelayed = false;
  $("html").on("click", function() {
    setTimeout(function() {
      isDelayed = true;
    }, 1000)
if (isDelayed) {
 //execute
}
```

In other circumstances, like on a page where we use the A-Frame Link component you can affect object attributes such that they won't double click and misbehave. Link has an `on` prop which defaults to `click`:
```javascript
link.setAttribute('link', {
 "href": "#",
 "title": marker,
 'image': preview,
 'on': "blah"
 });
setTimeout(function() {
 link.setAttribute('link', {
 'on': "click"
 });
 }, 1000);
```

Users who like to click frantically might panic, but most won't notice the subtle delay that waits just long enough to prevent A-Frame Mobile's invisible thumb from clicking on it

**Comment by wmurphyrd** [comment] 2018-04-11 00:09
@kezzsim you're seeing this still in 0.8.0? I thought I had fixed this one

**Comment by Delidragon** [comment] 2018-08-27 11:30
Any progress? Or new ideas for a workarounds?

**Comment by dmarcos** [comment] 2019-02-01 06:52
@Kezzsim Can you still reproduce with Chrome m66+ / A-Frame 0.8.2 ?

**Comment by dmarcos** [comment] 2019-02-05 22:49
I can't reproduce this anymore. Android m71 does not fire `MouseEvents` when tapping the screen. I only see one `TouchEvent` (touchstart)

**Comment by dmarcos** [comment] 2019-02-05 23:46
This does not reproduce anymore in master: https://cdn.jsdelivr.net/gh/aframevr/aframe@98d539057a452f4181b9856d21487bde1fc636ca/dist/aframe-master.min.js

Closing but can reopen if you can provide an example that breaks with build above.

**Closed by dmarcos** 2019-02-05 23:46 UTC
Labels: bug

**Comment by khlevon98** [comment] 2019-02-25 13:33
Hi guys, in aFrame 0.8.2 this problem was fixed, but in aFrame 0.9.0 this problem exists. When you first time touch on cube it trigger click event twice, in second time it calls once, but when you move scene and have registered mouseleave event, after that wen you click on cube it again calls click event twice, you can test it in this example 

https://codepen.io/khlevon98/full/GzObKR

**Comment by dirkk0** [comment] 2020-02-24 17:29
A similar behaviour seems to occur in the Oculus Browser on the Quest with A-Frame 1.0.4.
Here's a demo and a workaround similar to the one @Kezzsim provided.
https://curious-electric.com//w/experiments/aframe/minimal-quest-event-bug/

I am not sure if i should file another bug or if this is really related.

**Comment by rowbottomn** [comment] 2020-06-14 22:47
On 1.0.4 on iOS, click even triggers sound twice.
