### ISSUE TITLE
Broken controls components

### ISSUE THREAD

**Issue by wyzwon** [aframevr/aframe#4850] opened 2021-04-20 14:32 UTC
**Description:**
Controllers are not displaying or responding to events.
This applies to both the vive-controls and hand-controls components but not laser-controls

The demo code mostly consists of a blank A-Frame scene but I have thrown event handlers on them that should create little cubes in response to triggerdown events.

- A-Frame Version: 1.2.0
- Platform / Device: HTC Vive (gen 1)
- Reproducible Code Snippet or URL: [Glitch page](https://aframe-issue-4850-broken.glitch.me/)

A demo of laser controls working with otherwise identical code [here](https://aframe-issue-4850-working.glitch.me/)

These components worked for my headset back when I was using WebVR through Firefox including while running 1.2.0

**Comment by dmarcos** [comment] 2021-04-20 15:51
What browser?

**Comment by dmarcos** [comment] 2021-04-20 16:14
Is this example working for you? https://aframe.io/aframe/examples/showcase/tracked-controls/

**Comment by wyzwon** [comment] 2021-04-21 03:20
I have been using Chrome but I have now confirmed the issue is also present when running Edge. Firefox still never loads and Opera insists on entering full screen mode, but those are probably entirely different issues.

The tracked-controls example does not work either.

**Comment by wyzwon** [comment] 2021-04-23 11:21
I was reading through the page on [laser-controls](https://aframe.io/docs/1.2.0/components/laser-controls.html) and noticed this line:

> These controller components get activated if its respective controller is connected and detected via the Gamepad API. Then the model of the actual controller is used.

My wands do not show up as Vive wand models, they show up as spheres. Is this a default model? Does this mean my controllers are not being identified properly?

**Comment by dmarcos** [comment] 2021-04-23 18:18
It looks it's falling back to the default controller for some reason. 

I can't debug on my side because [WebXR for Chrome hasn't worked on my machines for a while](https://github.com/aframevr/aframe/issues/4709). 

You can help debug if you have some time to spare. It would be super appreciated.

I would put a breakpoint here

https://github.com/aframevr/aframe/blob/master/src/systems/tracked-controls-webxr.js#L81

and see what's the profile of the detected controllers in the `this.controllers` variable.

**Comment by wyzwon** [comment] 2021-04-28 09:05
For both versions of the demo I was able to see this result:

> 0: "htc-vive"
> 1: "generic-trigger-squeeze-touchpad"

In the laser-controls demo the hands were still spheres

**Comment by wyzwon** [comment] 2021-05-14 01:51
Out of curiosity I had a friend test the demos with a Quest 1. I asked what the controllers looked like and if they could place cubes with the trigger event.

The hand-controls behaved normally displaying the expected low poly hand model. In the laser-controls, the controllers showed up as the expected quest controller model, but the model appeared to be pitch black. The triggerdown event worked for both demos.

**Comment by dmarcos** [comment] 2021-05-14 02:19
That sounds like expected behavior. Laser controls is a darkish scene. Model color depends on lighting. You can also check https://aframe.io/aframe/examples/showcase/ui/

**Comment by wyzwon** [comment] 2021-05-14 03:59
I didn't explicitly define any lights in the scene so that makes sense to me, though it is odd then that the default spheres I see are bright white. If I get a chance I'll ask them to try a scene with an ambient light added. The main takeaway is the confirmation that the problem within the scope of this issue is limited to the Vive.

**Comment by wyzwon** [comment] 2021-05-24 08:09
So I finally traced the issue to its root. The components are looking for the id "htc-vive-controller-mv" when they should be looking for "htc-vive". changing this also fixes the model for laser-controls which had been falling back to "generic-trigger-squeeze-touchpad"

That said, @dmarcos I went to change this and submit it to master but you appear to have fixed this before I even filed this official bug report: f6b3de9ce5e7c7631dad7f05106fa010e523e537 😅

Unless there is a new official release imminent, would it be possible to get a new minor version 1.2.x with this change released?

**Comment by dmarcos** [comment] 2021-05-24 08:35
@wyzwon Thanks for investigating and glad it's working. Notice you can always use [master builds](https://cdn.jsdelivr.net/gh/aframevr/aframe@52136de6a863f32d8cb806b65c3c3223f6b0f8a3/dist/aframe-master.min.js).  You can see [commit messages](https://github.com/aframevr/aframe/commits/master) for link to the latest

**Comment by dmarcos** [comment] 2021-05-24 08:37
This was fixed by https://github.com/aframevr/aframe/commit/f6b3de9ce5e7c7631dad7f05106fa010e523e537 
Closing and can reopen if necessary.

**Closed by dmarcos** 2021-05-24 08:37 UTC
