### ISSUE TITLE
gltf-model not working?

### ISSUE THREAD

**Issue by Vesper0704** [aframevr/aframe#5255] opened 2023-03-07 04:39 UTC
**Description:**

- A-Frame Version: 1.4
- Platform / Device: macbook air M1; chrome
- Reproducible Code Snippet or URL:
```html
<a-scene background="color: #ECECEC">
        <a-assets timeout="100">
            <!-- <a-asset-item id="cityModel"
                src="https://cdn.aframe.io/test-models/models/glTF-2.0/virtualcity/VC.gltf"></a-asset-item>
            <a-asset-item id="controllerModel" src="./steam_controller/scene.gltf"></a-asset-item>
            <a-asset-item id="birdModel" src="./phoenix_bird/scene.gltf"></a-asset-item> -->
            <a-asset-item id="danceModel" src="./dance/scene.gltf"></a-asset-item>
        </a-assets>
        <a-entity gltf-model="#danceModel" scale="0.5 0.5 0.5" position="0 0 -1.5"></a-entity>
</a-scene>
```

I have followed the tutorial and the model is rendered successfully. However, the animation doesn't work as anticipated. I checked the `.gtlf` and the `animation` attribute exists. 
Is there anything I missed?
Thanks.

**Comment by Vesper0704** [comment] 2023-03-07 04:56
Sorry I miss the `animation-mixer` component. However, the animation is totally a mess...
This is the initial state:
<img width="321" alt="image" src="https://user-images.githubusercontent.com/64687700/223324020-504602ea-bc8f-449e-94ce-f0d52e7e9733.png">
And after I animated it:
<img width="495" alt="image" src="https://user-images.githubusercontent.com/64687700/223324177-9f4a0bfc-08c6-4c5d-a9a4-153f6381db13.png">
The model is downloaded from https://sketchfab.com/3d-models/levi-captured-by-volograms-c8d83162bf2d4c98bac1c0402c72e888.

This is the changed part:
`<a-entity gltf-model="#danceModel" scale="0.5 0.5 0.5" position="0 0 -1.5" animation-mixer="loop: once"></a-entity>`

**Comment by dmarcos** [comment] 2023-03-07 08:33
Might want to check your model on https://gltf-viewer.donmccurdy.com/

**Comment by Vesper0704** [comment] 2023-03-08 01:49
Thanks! The gltf model I downloaded has a `buffer` attribute and needs a `scene.bin`, but I can not load it. Is there any way to solve it?
```json
  "buffers": [
    {
      "byteLength": 179834296,
      "uri": "scene.bin"
    }
  ],
```

**Comment by Vesper0704** [comment] 2023-03-08 02:08
Thanks! I checked the model and it is messy as well, so it is the wrong source model... I'll find another one.

**Comment by dmarcos** [comment] 2023-03-10 17:33
It seems the issue is in the model side and nothing actionable in A-Frame. Closing but can reopen if necessary.

**Closed by dmarcos** 2023-03-10 17:33 UTC

**Comment by Vesper0704** [comment] 2023-03-13 01:56
I download another model from [glTF-Sample-Models](https://github.com/KhronosGroup/glTF-Sample-Models) , and it passed the gltf-viewer check. However, the animation is still a mess. It should be like [this](https://github.com/KhronosGroup/glTF-Sample-Models/blob/master/2.0/AnimatedMorphSphere/screenshot/screenshot.gif), but using gltf-model and animation-mixer, the model just jitters or shifts suddenly rather than reshaping smoothly.
There is no error in console, and the model indeed loads completely.
