### ISSUE TITLE
Stereoscopic VR mode deviated for all examples.

### ISSUE THREAD

**Issue by EricHsuYC** [aframevr/aframe#4813] opened 2021-03-03 00:56 UTC
**Description:**

- A-Frame Version:
Current example version
- Platform / Device:
Android/Pixel 4a
- Reproducible Code Snippet or URL:
https://aframe.io/examples/showcase/helloworld/

![171844](https://user-images.githubusercontent.com/17045080/109735794-49808080-7bfe-11eb-8d16-e5075056b76b.jpg)

**Comment by dmarcos** [comment] 2021-03-03 01:13
On ARCore Android devices the stereo view is rendered natively by Android and not by A-Frame. It looks like an Android bug in your particular device / android / browser version or configuration. FWIW I cannot reproduce on Pixel 3 / Chrome 88 / Android 11

**Comment by tgandor** [comment] 2021-05-05 12:35
Interesting. On a Galaxy S9 / Firefox I'm getting "double vision". VR in youtube work correctly (but it's easier, probably, since it's a 2D image warp). I'll try again later, because it would be very cool to have such a library to play with!

**Comment by dmarcos** [comment] 2021-05-05 19:54
> 
> 
> Interesting. On a Galaxy S9 / Firefox I'm getting "double vision". VR in youtube work correctly (but it's easier, probably, since it's a 2D image warp). I'll try again later, because it would be very cool to have such a library to play with!

FWIW, Firefox doesn't ship with a WebXR implementation. Use Chrome

**Comment by dmarcos** [comment] 2022-11-21 02:07
This looks like a problem specific to Firefox that doesn't ship the WebXR API. I recommend using Chrome. Closing and can reopen if necessary.

**Closed by dmarcos** 2022-11-21 02:07 UTC
